### PR TITLE
[WIP] RepositorySet / Pool Split & Load only explicitly referenced package data

### PR DESCRIPTION
**Pull request by naderman**
This is a fixed version of https://github.com/composer/composer/pull/3994

Todo:
- [ ] RepositorySetTest
- [ ] don't use object state to construct pool in RepositorySet
- [x] move request name collection logic into request - solver should take repo set
- [ ] evaluate if RepositorySet and CompositeRepository should be merged
- [ ] refactor policy to work with repositoryset in addition to pool
- [ ] remove uses of small pools from installer
- [ ] this should be empty: `grep -ri "pool" src/ | grep -v "src/Composer/DependencyResolver"`

### CODE REVIEW

**Comment by stof** [comment]
Can you add a test covering the broken case ?

**Comment by naderman** [comment]
@stof yes I will, there are also more bugs.

**Comment by naderman** [comment]
@Seldaek so I incremented the plugin api version to 2.0.0 for this, as the calls to plugins have changed to use repository sets rather than pools. This means all plugins will stop working when updating to this version - any idea how we would handle updating to this version? Afterall if we merge something like this into master it immediately breaks all installs using plugins. So we need some smoother way to upgrade, but I'm not sure what that would be.

**Comment by staabm** [comment]
@naderman would it be possible to ship a Adapter class which can translate between API V1 & V2?
This could be used for plugins which rely on V1 automatically.

**Comment by naderman** [comment]
No that's really not possible due to the nature of these changes, otherwise I would have suggested that already.

I imagine we'll have to do another release and announce that this breaking change is coming, and then anyone relying on old plugins will need to stick to the release, while master is updated with these changes.

**Comment by Seldaek** [comment]
I think yes we need to do a soft migration process of some kind for this, so maybe we need to delay this a little while, which sucks. On the other hand, I guess we should take the opportunity to look at the plugin API in depth and break anything else that needs breaking (cc @nevvermind).

**Comment by Seldaek** [comment]
@naderman what about what we discussed regarding having DefaultPolicy not dependent on a Pool btw? It would be nice if it could be used to sort packages standalone, but it doesn't seem to have change yet here.

**Comment by naderman** [comment]
Should check if this resolves https://github.com/composer/composer/issues/6840

**Comment by naderman** [comment]
Closing this in favour of the new PR which is based on current composer.

**Pull request closed without merging**
