### PR TITLE
Update PHPStan to 1.8.3

### PR DESCRIPTION
**Pull request by ondrejmirtes**

### CODE REVIEW

**Comment by stof** [comment]
The update of the php-8.1 baseline looks wrong, as the CI fails.

**Comment by ondrejmirtes** [comment]
Looks like it is!

**Comment by Seldaek** [comment]
Thanks, merged as 9bb436ec2 (please target 2.4 branch next time ;)

**Comment by Seldaek** [comment]
Thanks, merged as 9bb436ec2 (please target 2.4 branch next time ;)

**Comment by Seldaek** [comment]
Thanks, merged as 9bb436ec2 (please target 2.4 branch next time ;)

**Pull request closed without merging**
