### PR TITLE
Feature proposal: sorting keys by logical blocks

### PR DESCRIPTION
**Pull request by andrey-helldar**
In continuation of the [discussion](https://github.com/ergebnis/composer-normalize/issues/779), this PR was created.

Only the order of the elements has been changed. Codestyle has remained the same.

### CODE REVIEW

**Comment by andrey-helldar** [comment]
Just attaching the https://github.com/composer/composer/discussions/10073 discussion so as not to search :)

PS: I will make changes in the coming days.

**Comment by andrey-helldar** [comment]
@stof, now I look at the [`dumper code`](https://github.com/composer/composer/blob/main/src/Composer/Package/Dumper/ArrayDumper.php) and understand that there is no point in making changes to it.

If you configure the dumper so that it stores the keys in the order we need, then it will have to be completely rewritten.

On the one hand, this can be done, and on the other, you can use the [`normalizer`](https://github.com/ergebnis/composer-normalize). ¯\_(ツ)_/¯

**Comment by Seldaek** [comment]
OK, seems fine to me, thanks. I agree shifting the whole dumper code isn't really worth it.

**Comment by andrey-helldar** [comment]
Thank you

**Comment by localheinz** [comment]
Thank you, @andrey-helldar!

**Pull request merged**
