### PR TITLE
Replace old deprecated packages with new one

### PR DESCRIPTION
**Pull request by yaman-jain**
1. replace package CommandEvent with \Composer\Script\Event.
2. replace package PackageEvent with \Composer\Installer\PackageEvent.

### CODE REVIEW

**Comment by Seldaek** [comment]
This code is specifically for BC with outdated handlers, I guess you did this because  your IDE told you it's using deprecated code, but IDEs aren't very smart..

**Comment by yaman-jain** [comment]
@Seldaek I think this line should be removed. By the way what does BC means? 
https://github.com/composer/composer/blob/master/src/Composer/Script/PackageEvent.php#L20

**Comment by hkdobrev** [comment]
[BC as in Backwards compatibility](https://en.m.wikipedia.org/wiki/Backward_compatibility).

**Comment by yaman-jain** [comment]
Thanks !

**Comment by Seldaek** [comment]
Well no the line shouldn't be removed, it indicates to other people that they shouldn't use the class. But we still need to use it to provide backwards compatibility.

**Pull request closed without merging**
