### PR TITLE
Centralized custom table styles

### PR DESCRIPTION
**Pull request by freezy-sk**
Centralized custom table styles for better consistency across application

### CODE REVIEW

**Comment by alcohol** [comment]
Didn't I tell you you should use/create a `TableStyle()` instance instead? :-\

**Comment by freezy-sk** [comment]
@alcohol yes, you told me that, but after analysis of that two classes and documentation, I know that this is the way it should be done. `TableStyle` has private properties because they don't want it to be extended and all styling should be done in `Table` like it's done with 3 default styles.

**Comment by alcohol** [comment]
I think you misunderstood. Don't extend `TableStyle`. Simply create an instance of it in the Application and make it available.

**Comment by freezy-sk** [comment]
Yes that's done in that custom style initialization like it's done in base Table class. It's not necessary to instanciate TableStyle on every run of Application

**Comment by alcohol** [comment]
But having a whole extra class is necessary? Not sure I follow your logic :-\

**Comment by freezy-sk** [comment]
My solution covers multiple custom styles if they should be used. It sets default style for basic Table instances so it's consistent through whole application and it's done the way it's done in base Symfony class.

**Comment by alcohol** [comment]
I give up. Go wild.

**Comment by Seldaek** [comment]
Don't really see the point of replacing 3 lines by 30lines.. sorry

**Comment by freezy-sk** [comment]
@Seldaek point is that I prepared another command which uses table and they styles should be consistent. So instead of copy-paste of table style in licenses command there was a good way to create default styling of table.

**Comment by Seldaek** [comment]
@freezy-sk ok then I would suggest adding that change together with the new command.

**Pull request closed without merging**
