### PR TITLE
Fix Travis install for PHP 7

### PR DESCRIPTION
**Pull request by stof**

### CODE REVIEW

**Comment by Seldaek** [comment]
Seems the problem fixed itself now.

**Comment by stof** [comment]
@Seldaek Travis deployed an update of the VMs, and so a newer composer. But it has been reverted today because of errors with MySQL: http://docs.travis-ci.com/user/build-environment-updates/2015-04-09/

**Comment by Seldaek** [comment]
Well the last few builds passed on PHP7 so I'd guess we're good no?

**Comment by stof** [comment]
yeah, seems so.

**Pull request closed without merging**
