### PR TITLE
Added sort-packages into config

### PR DESCRIPTION
**Pull request by hanovruslan**
#4715 Added sort-packages into config

### CODE REVIEW

**Comment by alcohol** [comment]
Please also add a way to programmatically set this new config flag while you are at it.

**Comment by alcohol** [comment]
- Needs a test: just add something to the require scenarios, make sure it runs with the config set to true, verify the result is sorted.
- Needs documentation.

**Comment by hanovruslan** [comment]
@alcohol 
```
Needs a test: just add something to the require scenarios
```

please tell in which (test?) file ?

**Comment by alcohol** [comment]
I had a look at [tests/Composer/Test/Fixtures/installer](/composer/composer/tree/master/tests/Composer/Test/Fixtures/installer), but it actually does not seem possible to write a test for this particular scenario with the current tools available I'm afraid. Was hoping that we would be able to check that given a composer.json and running require x, we could check the resulting composer.json; but alas no such use-case is yet available among the installer tests.

**Comment by alcohol** [comment]
Just some documentation will be sufficient. Check the CLI and config document.

**Comment by hanovruslan** [comment]
(Y)

**Comment by hanovruslan** [comment]
@alcohol [this](https://github.com/hanovruslan/composer/commit/38615181c64be6f4272df4a551e46a98c215f001) would be enough ?

**Comment by Seldaek** [comment]
Thanks

**Pull request merged**
