### PR TITLE
[WIP] Test on PHP 7.4 Stable

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Test on stable PHP 7.4, and use latest distributions available on travis.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Looks like we'll have to upgrade PHPUnit to test on PHP 7.4 properly.

**Comment by johnstevenson** [comment]
@GrahamCampbell There would be quite a lot of work to make it compatibile with lower PHP/PHPUnit versions.

I did this for https://github.com/composer/xdebug-handler/commit/6624d7ee1ce21572af8558e7420f8ae954a902fb which is a tiny codebase and had to handle:

- replacing setupBeforeClass/ tearDownAfterClass with different annotated methods.
- replacing deprecated asserts (like assertContains).
- changing `@expectedException` annotations to use either `setExpectedException` or `expectException` depending on the PHPUnit version.

Perhaps symfony/phpunit-bridge would be a better solution for larger codebases?

**Comment by adaamz** [comment]
@johnstevenson That is not problem. Problem is that composer is installing phpunit 4.8 for php 7.4, because phpunit has no upper bound restriction.

**Comment by johnstevenson** [comment]
@adaamz Yes, but to get xdebug-handler to work with lastest php (inc nightly) and the corresponding versions of phpunit, I had to make those changes (phpunit/phpunit": "^4.8.35 || ^5.7 || 6.5 - 8).

**Comment by adaamz** [comment]
@johnstevenson That is already there, or not?

**Comment by GrahamCampbell** [comment]
If someone wants to take over here, and finish this, that would be good. I don't have the free time needed to finish this at the moment.

**Comment by Seldaek** [comment]
Oh sorry forgot about this PR, but this was done on the 2.0 branch already so closing https://github.com/composer/composer/blob/2.0/.travis.yml

**Pull request closed without merging**
