### PR TITLE
Fix regression for artifact repository

### PR DESCRIPTION
**Pull request by fooman**
MacOS has the tendency to create resource forks when copying files to other file systems. If you copy a packaged zip into an artifact folder you can easily end up with:

```
Package-1.0.0.zip
._Package-1.0.0.zip
```

Prior versions of Composer were able to handle this and one would see a message like:

> File ._Package-1.0.0.zip doesn't seem to hold a package

I believe the regression is related to these changes https://github.com/composer/composer/commit/0db48b4f2e84ae4f177189e6a21383eabd26ea1a.

Error message received now is:

```
  [ErrorException]
  ZipArchive::close(): Invalid or uninitialized Zip object


Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Repository/ArtifactRepository.php:132
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 ZipArchive->close() at phar:///usr/local/bin/composer/src/Composer/Repository/ArtifactRepository.php:132
 Composer\Repository\ArtifactRepository->getComposerInformation() at phar:///usr/local/bin/composer/src/Composer/Repository/ArtifactRepository.php:70
 Composer\Repository\ArtifactRepository->scanDirectory() at phar:///usr/local/bin/composer/src/Composer/Repository/ArtifactRepository.php:54
 Composer\Repository\ArtifactRepository->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:185
 Composer\Repository\ArrayRepository->getPackages() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:104
 Composer\DependencyResolver\Pool->addRepository() at phar:///usr/local/bin/composer/src/Composer/Command/InitCommand.php:646
 Composer\Command\InitCommand->getPool() at phar:///usr/local/bin/composer/src/Composer/Command/InitCommand.php:685
 Composer\Command\InitCommand->findBestVersionAndNameForPackage() at phar:///usr/local/bin/composer/src/Composer/Command/InitCommand.php:394
 Composer\Command\InitCommand->determineRequirements() at phar:///usr/local/bin/composer/src/Composer/Command/RequireCommand.php:122
 Composer\Command\RequireCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:241
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:254
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:103
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:56
 require() at /usr/local/bin/composer:24
```

### CODE REVIEW

**Comment by fooman** [comment]
Thanks @alcohol - makes sense. I have made the suggested change.

**Comment by alcohol** [comment]
@fooman can you rebase this on top of 1.7? Thanks :-)

**Comment by fooman** [comment]
@alcohol okay I think this should have done it.

**Comment by Seldaek** [comment]
Thanks

**Pull request merged**
