### PR TITLE
Fix strpos deprecation notice

### PR DESCRIPTION
**Pull request by homersimpsons**
I do not exactly know the minimum reproduction, but I had this notice when executing composer. This fix the notice without altering the behaviour.

### CODE REVIEW

**Review by stof — APPROVED** [review]
this matches the way this is handle in 2.x

However, any reason you are still using Composer 1.x ?

**Comment by homersimpsons** [comment]
> However, any reason you are still using Composer 1.x ?

I do have some plugin incompatibilities that forbid me to use composer 2, furthermore upgrading those projects is not really relevant.

**Comment by stof** [comment]
Given that support for composer 1.x is deprecated in packagist.org, it might still be relevant to upgrade (after all, you decided to upgrade PHP for those projects, otherwise you would not care about the deprecation reported in PHP 8.1+).

Note that I don't know what the policy of @Seldaek and @naderman is regarding patches submitted against the 1.x branch.

**Comment by Seldaek** [comment]
I'll merge this as you did it so why not, but yeah we're not really maintaining 1.10 beyond critical security fixes, and new-PHP support is definitely not on the table, you should rely on v2 for that, or if you're stuck on an old project with old deps then most likely you're better off also using an old PHP.

**Comment by homersimpsons** [comment]
Thank you for the merge :)

I understand there won't be new-PHP support for composer.

**Pull request merged**
