### PR TITLE
Avoid using 'just' in documentation

### PR DESCRIPTION
**Pull request by svenluijten**
The word "just" can often be dropped in writing. 

- https://dev.to/marcuscreo/the-4-letter-word-word-that-makes-my-blood-boil
- https://www.glamour.com/story/why-i-quit-using-the-word-just-in-my-emails

**Edit:** I'd've edited the "Just fork it" at the bottom of the pages as well but it looks like that's part of the website, and isn't in the markdown files here. 

footer

### CODE REVIEW

**Comment by jvasseur** [comment]
This is a duplicate of #7148

**Comment by svenluijten** [comment]
Ah I didn't see that one 🙂 Looks like they didn't cover as much of the documentation though. I'll leave it up to the maintainers to decide which'll be pulled in!

**Comment by stof** [comment]
@svenluijten the website sources are at https://github.com/composer/getcomposer.org

**Comment by Seldaek** [comment]
Thanks

**Pull request merged**
