### PR TITLE
Output script command in verbose mode

### PR DESCRIPTION
**Pull request by alcohol**
Follow up on #4120

Not sure if we should only show it in verbose mode, or show by default and hide in quiet mode. Feedback/thoughts?

/cc @Seldaek @theofidry

### CODE REVIEW

**Comment by theofidry** [comment]
IMO it should be shown even in quiet mode. It is not too verbose to begin with and otherwise it would be meaningless for the use case described in #4120.

**Comment by stof** [comment]
what about the case of PHP scripts ?

**Comment by alcohol** [comment]
What exactly do you mean? Like..

```
"scripts": {
  "command": "Some\\Class::method"
}
```

?

**Comment by Seldaek** [comment]
Thanks, I added the event name in verbose mode too, I think this might become a pain for people with plugins having lots of listeners though so we might need to downgrade it to -v/-vv instead of */-v but let's see how it goes.

**Pull request merged**
