### PR TITLE
Try to symlinks on Windows systems, too

### PR DESCRIPTION
**Pull request by derula**
The symlink() function supports Windows since PHP 5.3. Most current Windows installations use NTFS, which supports symlinks.

The problem with these wrapper scripts is that they don't work as expected in some cases, for example if the bin file is a jar file.

In this case, on Windows, you will end up calling `java -jar vendor/bin/example.jar`, with example.jar really being an sh script.

So we should try to create symlinks on Windows, too. In case it doesn't work, there is still a fallback.

Or is there any reason why this isn't done?

### CODE REVIEW

**Comment by slbmeh** [comment]
> Or is there any reason why this isn't done?

I believe it's because Windows XP was still pretty common at the time of implementation.

**Comment by derula** [comment]
Hmm, but even in this case, would it not work with my proposed change as well? If executed on Windows XP (or on any file system that does not support symlinks, or on newer Windows versions when run without administrator privileges, etc.), it would create the scripts as a fallback, wouldn't it? I don't have a Windows XP box to test this on, though...

**Comment by alcohol** [comment]
It looks good, but I'm not really in a position to test unfortunately. :-(

**Comment by curry684** [comment]
Has become obsolete with #4845. As symlinks require elevation on Vista and later a symlink approach is not viable regrettably.

**Comment by derula** [comment]
@curry684 can you please clarify how #4845 makes this obsolete?

1. Junctions can only link to directories. In this case, symlinks to files are being created.
2. If a symlink cannot be created, it will automatically fall back to wrapper scripts. So the current behavior remains intact, and a feature is added that symlinks are created _if_ the process is run with elevated privileges.

I would understand if this got rejected for weird behavior (certain feature that only works if elevated, which usually never happens), but to my understanding, the general idea of this would still provide an improvement in certain cases. (Yes, I saw that there are conflicts now... I could try to fix that if anyone is still interested.)

**Comment by curry684** [comment]
Sorry didn't notice this was about files. I don't really think however one would want to always run Composer with elevation - that means you can no longer run it from an IDE for example.

In return for having to have an elevated command prompt open permanently you get a major arbitrary code execution loophole if an indirectly referenced plugin introduces post-install scripts that nest some keyloggers and DDoS bots deep in your registry, as it has unlimited privileges to do so. I think that would be irresponsible to add to Composer.

**Comment by Seldaek** [comment]
I tend to agree with @curry684 that in the current state of affairs symlinks on windows with php are not really practical. As for using jar files as binaries.. I guess in this sort of rare edge case referencing the jar direclty in the vendor/foo/bar/bin/file.jar isn't *that* bad?

**Comment by tored** [comment]
Just want to update on the symlink situation on Windows. Since Creators update for Windows 10 you have the possibility to avoid elevation if you have your system correctly configured by setting it to developer mode (or you can set the correct policy). Here is how Git for Windows handles symlinks.

https://github.com/git-for-windows/git/wiki/Symbolic-Links

Git for Windows requires however that you clone your repository with a flag to enable it for Windows.

**Pull request closed without merging**
