### PR TITLE
[DOCUMENTATION] Improve folder structure figure in "Path" type

### PR DESCRIPTION
**Pull request by carlosbuenosvinos**

### CODE REVIEW

**Comment by Seldaek** [comment]
Thanks

**Comment by philo23** [comment]
Unfortunately this seems to have caused some kind of encoding issue on the composer website: https://getcomposer.org/doc/05-repositories.md#path

> image

**Comment by carlosbuenosvinos** [comment]
I’ll take a look. I’ll try to generate the doc website, if not possible, I’ll change back to something similar.

**Comment by Seldaek** [comment]
Weird as locally it works fine for me.. something seems to go wrong on the server.

**Comment by Seldaek** [comment]
Ok found the issue, works now.

**Comment by Seldaek** [comment]
https://github.com/composer/getcomposer.org/commit/eea7f850bec28f13505e0658f77ea56e21e1541a

**Pull request merged**
