### PR TITLE
Test PHP 8.0 with lowest dependencies

### PR DESCRIPTION
**Pull request by WyriHaximus**
Refs: https://github.com/reactphp/promise/pull/161#issuecomment-624581608

### CODE REVIEW

**Comment by Seldaek** [comment]
You probably need to add --with-dependencies to the require command at https://github.com/composer/composer/blob/221d4e2a0f70d2204c2cbfe7749b33d0df671b9d/.github/workflows/continuous-integration.yml#L132 that hopefully lets it run further.

**Comment by WyriHaximus** [comment]
Yeah looks like it, the goods news it seems like no `react/promise` related issue, a few others tho: https://github.com/composer/composer/pull/8878/checks?check_run_id=657417763#step:16:206

**Comment by Seldaek** [comment]
So you think it's mis-use of the react/promise 2.x code? Because it does pass all tests with 2.x on php 7.4 so that's strange.. But maybe I can investigate locally by hooking into the react code at the point where it fails on php 8 and throwing there if it does pass in an array.

**Comment by WyriHaximus** [comment]
No clue yet to be honest. It could also be other code that isn't PHP 8 ready

**Pull request merged**
