### PR TITLE
Add Installation - Termux (Android)

### PR DESCRIPTION
**Pull request by PuneetGopinath**
Hi composer maintainers!

I just added how to install composer on termux (android) in the docs.

### CODE REVIEW

**Comment by stof** [comment]
Installing composer using packages provided by distributions is not officially supported, and so not documented in the official documentation (for instance, Debian and Ubuntu have a `composer` package providing an outdated version of composer through `apt`, but this is not documented here).

**Comment by PuneetGopinath** [comment]
Ok, Thanks

**Comment by staabm** [comment]
> package providing an outdated version

maybe it would make sense to mention/warn something simliar in the the docs...

**Comment by PuneetGopinath** [comment]
> maybe it would make sense to mention/warn something simliar in the the docs... 

Did you mean to warn/mention the version of composer available in termux?

**Comment by stof** [comment]
> maybe it would make sense to mention/warn something simliar in the the docs...

well, the doc does not even mention that such package _exists_.

**Comment by staabm** [comment]
> Did you mean to warn/mention the version of composer available in termux?

I mean mention in the readme that composer is installable over various ways (e.g. Debian and Ubuntu) which is not considered supported.

**Comment by PuneetGopinath** [comment]
> > Did you mean to warn/mention the version of composer available in termux?
> 
> I mean mention in the readme that composer is installable over various ways (e.g. Debian and Ubuntu package manager) which is not considered supported.

This is a good idea, anyway @stof doesn't accept it, so I will close this pr.

**Pull request closed without merging**
