### PR TITLE
remove dead code/class: DebugSolver

### PR DESCRIPTION
**Pull request by alcohol**
This file has not been updated in a long time and seems to contain mostly dead or no longer compatible code.

/cc @naderman can you confirm this?

### CODE REVIEW

**Comment by naderman** [comment]
Are these couple bytes really an issue? That thing was pretty useful when debugging in the solver before, and I would expect to use it again when making changes?

**Comment by naderman** [comment]
Well i guess I an always just get it from git history :-)

**Comment by alcohol** [comment]
Well hence I asked, but @Seldaek was a bit quick :d

It was referencing a lot of non-existant fields/properties though.

**Comment by Seldaek** [comment]
Yeah it didn't seem to work at all so I figured it was probably not needed.. We can revert though and update it instead? Up to you :)

**Pull request merged**
