### PR TITLE
Update 00-intro.md adding an install tutorial link for shared hosting

### PR DESCRIPTION
**Pull request by HongPong**
adding an install tutorial link for shared hosting finding the correct environment settings.

### CODE REVIEW

**Comment by alcohol** [comment]
Please no. If you're going to include something like this, make it generic and don't include commercial brands or businesses.

**Comment by HongPong** [comment]
Makes sense, but it would be best if specific vendors install tutorials can
be listed on a separate page then. There is nothing for the shared install
edge cases in the current docs and it is difficult to get the software
working without searching elsewhere.

**Comment by alcohol** [comment]
To be honest, the link you provided has little to do with composer, and much more with a hosting provider's php setup (also, holy moly 5.2). I believe composer should stay away from trying to document the entire landscape and keep the focus on managing dependencies.

**Comment by Seldaek** [comment]
Sorry but hosts have to stop misconfiguring their shit. It makes no sense to have a php on the CLI that calls in a non-CLI binary. If they provide ssh access they should support it and configure the PATH correctly.

**Pull request closed without merging**
