### PR TITLE
optimize regex by strpos checks

### PR DESCRIPTION
**Pull request by voku**
ping: https://github.com/phpstan/phpstan-src/pull/318

---
This change is [Reviewable](https://reviewable.io/reviews/composer/composer/9186)

### CODE REVIEW

**Comment by Seldaek** [comment]
https://github.com/composer/composer/pull/9187 fixed the substr vs strpos which did seem to have a minor impact, but the changes here don't really seem to do much for me in real world benchmark, while adding lots of extra complexity to the code, so I am really not sure if it's worth it. When you do a strpos it has to scan through the whole string, which is also what a preg_match does, sure it has to compile the regex first but that is cached AFAIK and on fairly large class files the strpos or preg_match I guess perform very close to each other when no match is found, while when a match is found you then end up having to scan the file twice.

**Comment by Seldaek** [comment]
Also.. this is scanning 9000 classes in about 2seconds here, so it's already pretty fast IMO.  We made sure the regexes are optimized already.

So yeah, unless there is a real solid argument for adding complexity on one of them, I'd rather not add this to all regexes "just because".

**Comment by voku** [comment]
@Seldaek understand and thanks for the explanation. Is there already something like a performance test or something like that, so that we can compare the results?

**Comment by Seldaek** [comment]
Not really, I run `composer dump-autoload -o --profile` on a few projects to see how much time is spent. Definitely could do more specific profiling if you are interested in digging more in depth, but IMO it's kinda fast enough that it doesn't need a ton of time investment.

**Pull request closed without merging**
