### PR TITLE
Delegate problem formatting to a reserved class

### PR DESCRIPTION
**Pull request by Pherserk**
In this way problems become more similar to a plain/storae object for reasons.
It is possible to work on problem formatter without change Problem behaviour.

### CODE REVIEW

**Comment by naderman** [comment]
I think it would make more sense to have one problem independent formatter and passing the problem into the getPrettyString function?

**Comment by Pherserk** [comment]
Yes should be a static method of Formatter, but it also depends on Pool that is context dependent.

**Comment by Pherserk** [comment]
Ok I Will refactor avoidib Construction dependencies

**Comment by Pherserk** [comment]
mmm.... need to change the Solver... I'll get some time :)

**Pull request closed without merging**
