### PR TITLE
`*` is not a valid version, changed to `1`

### PR DESCRIPTION
**Pull request by strayobject**
Minor documentation change.

### CODE REVIEW

**Comment by strayobject** [comment]
I might be wrong about this, if so a proper example would be nice.

For me, this does not work
```
"platform": {
  "ext-mbstring": "*"
}
```

And this does:
```
"platform": {
  "ext-mbstring": "1"
}
```

**Comment by Seldaek** [comment]
As a requirement you'd need to use `*` to match any possible version, but when declaring which version the extension has in platform config then you need a version and not a constraint, so indeed there `1` or something would make more sense, but that's not really what that piece of doc had in mind. Maybe should be a footnote if anything?

**Comment by dereuromark** [comment]
I think the `*` should be kept as general and agnostic advice over all extensions.
The main focus of these is to check existence of the extension, the exact version is often a detail less relevant here.

**Comment by stof** [comment]
When requiring an extension, setting the constraint to `1` is definitely a bad idea, as that would allow only 1.0.0 of the extension (and so will almost always fail).

**Comment by strayobject** [comment]
I have figured out that my change suggestion is in the wrong section.
I wrote the whole essay about how we are leading newcomers on the wrong path, while my use case and change pertains to
https://github.com/strayobject/composer/blob/patch-1/doc/06-config.md#platform

I wonder if it is just me who sees a mention of `platform` in the basic usage and haphazardly jumps to conclusion that this is the docs for the config section :man_facepalming: 

If it's not just me then maybe we could add a link to the config's `platform` section in the docs, otherwise, sorry I've wasted your time.

**Pull request closed without merging**
