### PR TITLE
Allow psr/log ^3.0

### PR DESCRIPTION
**Pull request by simPod**
Same as in https://github.com/composer/composer/pull/10158

### CODE REVIEW

**Comment by Seldaek** [comment]
To allow psr/log 3 we'd have to add the PHP 8 type hints IIRC?

**Comment by simPod** [comment]
@Seldaek true, I missed that composer/composer implements that interface as well.

Not sure what is the possible upgrade path here, I guess it is not possible to support (v1+v2) and v3 at the same time as method signatures are incompatible?

**Comment by stof** [comment]
you can support v1+v2+v3 at the same time with 2 conditions:

- your code requires PHP 7.2+ to have the covariance rules
- your code implements the methods with return types (to support v3) but without argument types (to support v1)

The first condition is not met in the composer 2.2 LTS branch.

**Comment by simPod** [comment]
I've changed target to master

**Comment by stof** [comment]
not having changes in the BaseIO class is wrong. It does not actually make it compatible with v3 (see the second condition I listed in my previous comment)

**Comment by simPod** [comment]
@stof yup I did but the return types are already there 🤔 So since it was compatible now I assume it still is. Removing `array` from `array $context` should not be necessary, or?

**Comment by stof** [comment]
the `array` argument type is already there in the v1 signature. So it is indeed fine to have it. the `without argument types` only applies to the new ones being added in psr/log.

> the return types are already there

indeed sorry. I looked at the wrong composer branch.

**Comment by Seldaek** [comment]
Ok let's give this a shot, I forgot it was possible with 7.2 by ignoring the $message type. Thanks!

**Pull request merged**
