### PR TITLE
Ability to use GitLab deploy tokens in composer

### PR DESCRIPTION
**Pull request by KminekMatej**
Added ability to work with GitLab deploy tokens: https://docs.gitlab.com/ee/user/project/deploy_tokens/

Deploy tokens can be specified two ways:
1) **GIT CONFIG**:
`git config --add gitlab.deploytoken.user USERNAME && git config --add gitlab.deploytoken.token TOKEN`
2) Auth.json:
```
"gitlab-token": {
    "gitlab.com": {"username": "USERNAME", "token": "TOKEN"}
}
```
(When gitlab-token in auth.json is specified just by string, its considered as private-token authentication scheme, when its an array, it gets considered as deploy token scheme, a.k.a. user / token access )

### CODE REVIEW

**Comment by KminekMatej** [comment]
Forgot to mention that this pull-request also solves the problem with cutting .git extensions from requesting schemes on Gitlab - issue #8402

**Comment by KminekMatej** [comment]
If this commit is going to be merged, its neccessary to update documentation as well - upgrade auth.json scheme and new git config keys

**Comment by Seldaek** [comment]
Seems fine to me at first sight although I will have to have a closer look next week, but please rebase/retarget the PR to 1.10 branch so it can be fixed in 1.x

**Comment by Seldaek** [comment]
At least the .git fix should go there.. The new token support perhaps is better targetted in a second PR to master.

**Comment by KminekMatej** [comment]
I just reverted the commit with GitLab deploy tokens and retargeted the original PR to branch 1.10x (so just the .git extension update should be there)
Also I just created new PR, containing jus the Gitlab deploy tokens.
Hope I didnt mess something up, cause the original PR now indicates I made 565 commits :) But thats probably some grouping or what.

**Comment by Seldaek** [comment]
The problem is you need to do a git rebase of this branch on top of the 1.10 branch, so it doesn't include all the new master commits.

**Comment by KminekMatej** [comment]
Yea, that makes sense. I cherry-picked that .git fix commit into 1.10 branch and created separate PR #8868 . Closing this one

**Pull request closed without merging**
