### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by paladox**
Bump required php version to php 5.3.3 since travis tests against 5.3.3.

### CODE REVIEW

**Comment by alcohol** [comment]
Unfortunately, 5.3.2 is the minimum requirement for --reasons--

As much as I would love to raise it to a version that isn't already declared end of life, this is something we simply cannot change without upsetting a lot of lost souls.

**Comment by paladox** [comment]
Hi well platform already has it as 5.3.3 already just the required php version is being bumped.

**Comment by alcohol** [comment]
Platform pretends that we are installing on 5.3.3 yes, also for --reasons--

That only works for this project though. This configuration is not inherited by other projects that depend on `composer/composer`.

**Comment by paladox** [comment]
Oh ok.

**Pull request closed without merging**
