### PR TITLE
Fix preg_replace usage

### PR DESCRIPTION
**Pull request by AydinHassan**
possible typo here: https://github.com/composer/composer/commit/e3ae45fa12e1791888f22af6ae1693a51c63918c

### CODE REVIEW

**Comment by alcohol** [comment]
Well spotted.

**Comment by staabm** [comment]
was fixed in https://github.com/composer/composer/commit/e3ae45fa12e1791888f22af6ae1693a51c63918c

**Comment by Seldaek** [comment]
Yeah sorry I saw your message on the commit and fixed it without looking at the new PRs :)

**Comment by AydinHassan** [comment]
np 😄

**Pull request closed without merging**
