### PR TITLE
Fix: Add missing imports

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] adds a bunch of missing imports

### CODE REVIEW

**Comment by xabbuh** [comment]
Wouldn't it be better to check why Composer didn't fail even when these imports where missing? Changes can be high that there is orphaned code that could safely be removed. Otherwise, it might be a good idea to add tests that cover these paths to make sure they actually work as intended.

**Comment by alcohol** [comment]
@xabbuh as far as I can tell, most (or all) of those are only related to references in `docblock`s.

**Comment by localheinz** [comment]
@xabbuh @alcohol 

Totally up for tests, if you'd prefer me to add them!

Here's what I could do:

* amend this PR to add imports only where missing for docblocks
* create separate PR with tests for those occasions where actual objects are created, but would currently fail because imports are missing

**Comment by alcohol** [comment]
@localheinz No need, they're all `docblock` related only (I've checked). Nothing to test here.

**Comment by localheinz** [comment]
@alcohol 

:+1: Thank you!

**Comment by xabbuh** [comment]
> @localheinz No need, they're all docblock related only (I've checked). Nothing to test here.

Then please completely ignore my comment. :)

**Pull request merged**
