### PR TITLE
Update appveyor to PHP 7.3

### PR DESCRIPTION
**Pull request by johnstevenson**

### CODE REVIEW

**Comment by Seldaek** [comment]
This fails a junction test unfortunately.

**Comment by johnstevenson** [comment]
Yeah, the weird thing is that it also fails this test using PHP 7.2 on my local machine. I'm trying to investigate this now.

**Comment by Seldaek** [comment]
Sooo should that other bugfix fix this now you think?

**Comment by johnstevenson** [comment]
Absolutely. I'll rebase on to latest 1.8 and we will see.

**Comment by johnstevenson** [comment]
Yippee!

**Comment by Seldaek** [comment]
Thanks

**Pull request merged**
