### PR TITLE
fixes #8159

### LINKED ISSUE #8159: PHP Fatal error: setDistUrl() not found
Hi there,

Until today everything worked fine. I just pulled the master of a repository required in composer.json. Today, I needed to define a commit ID to pull from this repository. After I changed to this, I do get the following PHP error when running `php composer.phar update`:

```
Fatal error: Uncaught Error: Call to undefined method Composer\Package\AliasPackage::setDistUrl() in phar:///path/to/my/composerphar/composer.phar/src/Composer/Installer.php:1223
Stack trace:
#0 phar:///path/to/my/composerphar/composer.phar/src/Composer/Installer.php(563): Composer\Installer->updateInstallReferences(Object(Composer\Package\AliasPackage), '09a3858')
#1 phar:///path/to/my/composerphar/composer.phar/src/Composer/Installer.php(229): Composer\Installer->doInstall(Object(Composer\Repository\InstalledFilesystemRepository), Object(Composer\Repository\CompositeRepository), Object(Composer\Repository\PlatformRepository), Array)
#2 phar:///path/to/my/composerphar/composer.phar/src/Composer/Command/UpdateCommand.php(163): Composer\Installer->run()
#3 phar:///path/to/my/composerphar/composer.phar/vendor/symfony/console/Command/Command.php(245): Composer\Command\UpdateCommand->execute(Object(Symfony\Compon in phar:///path/to/my/composerphar/composer.phar/src/Composer/Installer.php on line 1223
```

The commit number `09a3858` comes from a public repository, I define it like this in composer.json:
```
"somevendor/somerepo": "dev-master#09a3858 as master",
```

The composer.phar is the newest 1.8.5.

Strangely, I only get this error sometimes. The repo that causes this is not on packagist or so, but added to composer.json like 
```
  "repositories": [
    {
      "type": "vcs",
      "url":  "git@github.com:somevendor/somerepo.git"
    }
  ],
```

Best regards
Philipp

### PR DESCRIPTION
**Pull request by alcohol**
expand interface and add missing methods to aliaspackage

### CODE REVIEW

**Comment by alcohol** [comment]
Hrm this junction test seems to fail a lot on AppVeyor, for a lot of PRs.

Maybe we should look into that.

**Comment by johnstevenson** [comment]
@alcohol I agree.

Everything went well after my PRs to fix a PHP bug, but since we've been using PHP7.3.1 on Appveyor, there are random errors in the junction tests, with different things failing (like the junction tests pass, but an exception is thrown when removing the junction, because it is not a junction!).

Weird. I'll try and take a deeper look.

**Comment by alcohol** [comment]
@johnstevenson that would be great, if you could do that. I don't have a Windows development machine so anything I would do would just be blind stabs in the dark really.

**Comment by johnstevenson** [comment]
> so anything I would do would just be blind stabs in the dark really.

@alcohol Me too, and I do use Windows!

**Comment by Seldaek** [comment]
Adding the methods to aliaspackage 👍 but the interface technically is a breaking change although I really doubt it'd affect anyone maybe we rather do that part in 2.0 branch?

**Comment by alcohol** [comment]
🤷‍♂ I would just add it. Doubt it would cause much issues. Kinda need these methods.

**Comment by Seldaek** [comment]
Yeah.. I really doubt there will be any issues, so let's do it I guess.

**Pull request merged**
