### PR TITLE
Skip autoloader generation during install and update

### PR DESCRIPTION
**Pull request by mattsah**
Added no-autoloader option for install and update which skips the autoloder generation.  This has been requested by multiple users and is useful for deployment situations where one might be running composer in two stages.

See: https://github.com/composer/composer/issues/1663

### CODE REVIEW

**Comment by nifr** [comment]
awesome, thanks Jordi :+1:

**Comment by Jany-M** [comment]
Is there any way this could be integrated on a per library basis, in `composer.json`?

eg.
"require-dev": {
       "dontneed/autoloader": {
             version: "1.2.3",
            "autoloader": false
       }
}

**Comment by stof** [comment]
@Jany-M this does not make sense, as there is a single generated autoloader, not one per library

**Comment by mvl22** [comment]
Is there any equivalent of the CLI `no-autoloader` as a directive within `composer.json` itself?

(I would have thought it should be the package maintainer who determines whether their package uses autoloading, rather than the deployment.)

**Comment by Seldaek** [comment]
@mvl22 that flag's point is that you can run the dump-autoload at a later step because $reasons, but the point is not to have no autoloader at all, because IMO not using the Composer autoloader for the dependencies is kinda nonsensical overhead.

So no there is no config to persist that..

**Comment by mvl22** [comment]
> not using the Composer autoloader for the dependencies is kinda nonsensical overhead

I'm thinking of the scenario where you have a CMS that has its own autoloader definition, but there are embedded applications within the site that use Composer. In this scenario, you don't want the CMS to have an autoload.php file generated because that will take precedence if an include_path has been set in the VirtualHost. Maybe this too specific a scenario for generic support ;)

**Comment by Seldaek** [comment]
rm -rf vendor/composer is a bad idea™️. This contains installed.json which will make any further composer install go poorly if you wipe it. It may also contain packages from the composer vendor which would go even worse if they're needed.

If you really must delete files then delete `vendor/composer/autoload_*.php` and `vendor/composer/ClassLoader.php`, but really I don't see why you'd need to do that. Just don't include the vendor/autoload.php if you don't want to use it.

And include_path shenanigans yeahhh I wish that was not used anymore.. but I guess it still is :)

**Pull request merged**
