### PR TITLE
Explain Windows junctions in 05-repositories.md

### PR DESCRIPTION
**Pull request by johnstevenson**
Adds an explanation of junctions and their edge-case limitations.

### CODE REVIEW

**Comment by Seldaek** [comment]
You can't let go anymore I see ;) Thanks

**Comment by johnstevenson** [comment]
@Seldaek  Yes, I do see that I have got rather obsessed with this! And what's more I have just noticed that this should probably have said:

> **Note:** On Windows, directory symlinks are implemented using NTFS junctions
> because they can be created by non-admin users. Mirroring will always be used
> on versions below Windows 7, or if `proc_open` has been disabled on PHP versions
> less than 7.2.16 or 7.3.3 due to a PHP bug.

Perhaps you can save me by adding this yourself!

**Comment by Seldaek** [comment]
Will do ;)

**Comment by Seldaek** [comment]
So I rewrote that a bit to make it more readable:

> **Note:** On Windows, directory symlinks are implemented using NTFS junctions
> because they can be created by non-admin users. Due to a bug, on PHP versions
> less than 7.2.16 or 7.3.3 mirroring will always be used on versions below 
> Windows 7, or if `proc_open` has been disabled.

But then I realized.. without proc_open, we should never try junctions I think? Because it'll fail to create them as well.

**Comment by johnstevenson** [comment]
Yeah, very good point. We don't seem to check for that, so I need to change the new `safeJunctions` method to handle it. Do you agree?

**Comment by Seldaek** [comment]
Yeah I think that'd do.. If you wanna change the docs too I ended up aborting that change.

**Pull request merged**
