### PR TITLE
Update InstallCommand.php

### PR DESCRIPTION
**Pull request by 94noni**
Hi, small proposition to warn that running v1 can be upgraded to v2 when using the much used `composer install` command.
Feel free to close if already proposed/or not necessary, thank you,

### CODE REVIEW

**Comment by Seldaek** [comment]
Yeah we probably need to nudge people a bit stronger at some point, but I think we may still need to wait a bit.

**Comment by 94noni** [comment]
@Seldaek thank you for your answer :)

At the end of this month, it will be half a year since release of v2, do you have a roadmap or plan for the v1 official end of life datetime?
I've read https://blog.packagist.com/deprecating-composer-1-support/, back then no delay were announced
thank you :)

**Comment by Seldaek** [comment]
No we do not have a clear timeline, but v1 is still used in bigger numbers than v2, so I don't think it's very appropriate yet to call it dead, especially as some users are still unable to migrate to v2 due to plugin support etc. It's a large ecosystem, 6 months isn't that long.

**Comment by 94noni** [comment]
Friendly ping @Seldaek 
I remind this when reading https://github.com/composer/composer/issues/10340 and your tweet :)

**Comment by Seldaek** [comment]
Yeah it's probably time now, thanks

**Pull request merged**
