### PR TITLE
Search improvements

### LINKED ISSUE #10123: HgDownloader - clone fails with custom installation path (reincarnation of #2096)
My `composer.json`:

```json
{
    "repositories": [
        {
            "type": "composer",
            "url": "https://internal-hg-satis.example"
        }
    ],
    "require": {
        "php": ">=7.1",
        "internal/silverstripe-module-required": "^2.0@dev"
    },
    "extra": {
            "installer-paths": {
                    "cms/": ["silverstripe/cms"],
                    "framework/": ["silverstripe/framework"],
                    "modules/{$name}/": ["type:silverstripe-module"]
            }
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
…
OK
Checking composer version: OK
Composer version: 2.1.6
PHP version: 7.1.33
PHP binary path: /usr/bin/php
OpenSSL version: LibreSSL 2.6.5
cURL version: 7.54.0 libz 1.2.11 ssl LibreSSL/2.6.5
zip: extension present, unzip present, 7-Zip present (7z)

```

When I run this command: (`--ignore-platform-reqs` due to local enviroment, issue occurs on other machines without this argument as well)
```
composer install -vvv --ignore-platform-reqs
```

I get the following output: (full output on request)

```
Running 2.1.6 (2021-08-19 17:11:08) with PHP 7.1.33 on Darwin / 18.7.0
…
  - Installing internal/silverstripe-module-required (2.5.x-dev 63aa942b33de): Executing command (modules/silverstripe-module-required): hg clone -- 'ssh://xxx@repo.internal-hg-satis.example/source/dev.php.silverstripe.module-required/' 'modules/silverstripe-module-required'
Executing command (/Users/example/Temp/composer/modules/silverstripe-module-required): hg up -- '63aa942b33de'
Failed: [RuntimeException] Failed to execute hg up -- '63aa942b33de'

abort: no repository found in '/Users/example/Temp/composer/modules/silverstripe-module-required' (.hg not found)

    Install of internal/silverstripe-module-required failed
…
Downloading https://packagist.org/downloads/
[201] https://packagist.org/downloads/

                                                                                                                       
  [RuntimeException]                                                                                                   
  Failed to execute hg up -- '63aa942b33de'                                                                            
                                                                                                                       
  abort: no repository found in '/Users/example/Temp/composer/modules/silverstripe-module-required' (.hg not found)  
                                                                                                                       

Exception trace:
 () at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/src/Composer/Downloader/HgDownloader.php:52
 Composer\Downloader\HgDownloader->doInstall() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/src/Composer/Downloader/VcsDownloader.php:137
 Composer\Downloader\VcsDownloader->install() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/src/Composer/Downloader/DownloadManager.php:278
 Composer\Downloader\DownloadManager->install() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/src/Composer/Installer/LibraryInstaller.php:259
 Composer\Installer\LibraryInstaller->installCode() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/src/Composer/Installer/LibraryInstaller.php:135
 Composer\Installer\LibraryInstaller->install() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/src/Composer/Installer/InstallationManager.php:482
 Composer\Installer\InstallationManager->install() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/src/Composer/Installer/InstallationManager.php:418
 Composer\Installer\InstallationManager->Composer\Installer\{closure}() at n/a:n/a
 call_user_func() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/vendor/react/promise/src/React/Promise/FulfilledPromise.php:20
 React\Promise\FulfilledPromise->then() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/src/Composer/Installer/InstallationManager.php:419
 Composer\Installer\InstallationManager->executeBatch() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/src/Composer/Installer/InstallationManager.php:367
 Composer\Installer\InstallationManager->downloadAndExecuteBatch() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/src/Composer/Installer/InstallationManager.php:266
 Composer\Installer\InstallationManager->execute() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/src/Composer/Installer.php:706
 Composer\Installer->doInstall() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/src/Composer/Installer.php:543
 Composer\Installer->doUpdate() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/src/Composer/Installer.php:247
 Composer\Installer->run() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/src/Composer/Command/InstallCommand.php:137
 Composer\Command\InstallCommand->execute() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/src/Composer/Console/Application.php:317
 Composer\Console\Application->doRun() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/src/Composer/Console/Application.php:125
 Composer\Console\Application->run() at phar:///usr/local/Cellar/composer/2.1.6/bin/composer/bin/composer:67
 require() at /usr/local/Cellar/composer/2.1.6/bin/composer:24
```

And I expected this to happen:

The package to be correctly cloned. At the moment it results in the following folder structure:

```
./modules/silverstripe-module-required/modules/silverstripe-module-required/.hg
```

Whereas it should be:
```
./modules/silverstripe-module-required/.hg
```

From my understanding this happens due to …

```
Executing command (modules/silverstripe-module-required): hg clone -- 'ssh://xxx@repo.internal-hg-satis.example/source/dev.php.silverstripe.module-required/' 'modules/silverstripe-module-required'
```

… where the custom path is as well the cwd as the target of the clone. From my limited understanding this only happens if the source is a satis with a hg repository and if there is an installer (version 1.x) with a custom installation path (which has been relative in 1.x installers). I suppose this is a reincarnation of #2096 as the call to "realpath" has been removed in version 1.7.0 (with commit 1a725d5).

This issue affects ^2.0 and ^1.7.

From my understanding it should be possible to either:

* do not pass a cwd here (like in 73b269f)
* use realpath again (like it has been until 1.7.0)
* handle this in the hgutils (gitutils seems to do something similar)

### LINKED ISSUE #10324: preg_quote user data to RepositoryInterface::search where applicable
Also need to clarify and enforce that the name search can use regex chars at API level (user input should not be allowed to use regex IMO) but fulltext search cannot.

### LINKED ISSUE #10325: "composer search" should return more popular packages first (or better match namespaces in name-only mode)
Searching for 

```
composer search ^laravel -N
```

returns all sorts of packages, but `laravel/` is the most obvious example what one would like to see here.

If I search

```
composer search ^laravel/ -N
```

I get better matching results. These two queries **should behave basically in the same way**, this type of search is similar to as-you-type auto-suggest you'd get on Google or some e-commerce site.

The reason is in #10320, when you do

```
composer require larav<TAB>
```

it will auto-complete to

```
composer require laravel-
```

because it's offering more than 150 `laravel-`-prefixed packages in front of `laravel/*`.

So, either:

- sort by package downloads by default (?)
- more tightly match namespaces (namely, `laravel/` is a better match to the query `laravel` than `laravel-foo/` is)
- both (?)

### PR DESCRIPTION
**Pull request by Seldaek**
- Performance improvements by caching the /packages.json (only when searching) and /packages/list.json responses for up to 600 seconds and optimizing some code (fixes #10123)
- Add SEARCH_VENDOR search type (fixes #10325)
- Fixes and documents regex searchability at API level, preg_quote user content in search cmd (fixes #10324)

This lays groundwork to be able to further speed up #10320

### CODE REVIEW

**Comment by Seldaek** [comment]
@dkarlovi @GromNaN please have a look here :)

**Comment by Seldaek** [comment]
@GromNaN I added a second commit to hopefully really make the best of the packagist.org API (which may need to be optimized too tbh as it right now does a fairly poor SQL query for vendor search, but once Composer is using it that can be optimized later easily if needed).

**Comment by GromNaN** [comment]
That's impressing that you created a [new library](https://github.com/composer/pcre) in such short time to solve this issues.

Performance improvement is very appreciable. I go from 900ms to 300ms on a `--only-names`.

BC break? I cannot use regex to match package name (same for vendor):
```console
bin/composer search --only-name ^composer
bin/composer search --only-vendor ^composer
```

Thanks to the `--only-vendor` option, we can count **111289** vendors! That's still way too much for completion. Popularity sort would be very useful. That could be by sorting the packages in `package-list.txt` and `vendor-list.txt`.

**Comment by Seldaek** [comment]
> BC break? I cannot use regex to match package name (same for vendor):

This is intended, the regex leak was before not by design, so I fixed it. You can still use regex at the PHP API level just not at CLI level. So you should be able to search for `^composer` with `SEARCH_VENDOR` mode in #10320 to get the best results.

And yes the amount of vendors is still huge that is true.. I'll need to research how we can improve the sort order on the packagist.org API, but I need to focus on wrapping up Composer 2.2.0 first :)

**Pull request merged**
