### PR TITLE
[BUGFIX] respect PHP-CLI `error_reporting` parameter

### PR DESCRIPTION
**Pull request by xerc**
`/opt/php_8.1/bin/php -d error_reporting=8191 ~/composer u` # E_ALL & ~E_DEPRECATED & ~E_USER_DEPRECATED

### CODE REVIEW

**Comment by Seldaek** [comment]
Sorry nope, we do this on purpose.

**Comment by xerc** [comment]
may introduce via arg./flag

**Comment by Seldaek** [comment]
I don't see a need for it. We report deprecation errors without aborting the process. If you have an actual issue perhaps you should try to describe that in more details.

**Comment by xerc** [comment]
mainly because i have PHP 8.1 and PHP 7.4 runnig and compiled both with https://github.com/composer/composer/pull/10976 but there are a lot of deprecation messages in the [8] version which would be nice to hide if you do not want to patch in this specific feature into MAIN
for the example provided there ; it is relevant not to clear the (static-)cache if the database upgrade fails [sh:`&&`]

**Pull request closed without merging**
