### PR TITLE
Test for issue resulting in overly long learnt rules and solver bug exception

### PR DESCRIPTION
**Pull request by naderman**
Addresses https://github.com/composer/composer/issues/7665

### CODE REVIEW

**Comment by naderman** [comment]
completed the test case and rebased onto https://github.com/composer/composer/pull/9312 which fixes this problem too.

**Comment by Seldaek** [comment]
Think you forgot to push or forgot --force here. This is not rebased.

**Comment by naderman** [comment]
@Seldaek indeed forgot to --force, test is there now. Caveat: it's really slow, not sure that's acceptable?

**Comment by Seldaek** [comment]
What are we talking about with really slow? If really too slow we could split it into its own test perhaps with `@group slow` but it'd require refactoring the test runner a bit I guess.

Does the test really bring anything tho that's the other question..

Also it's not passing right now.

**Pull request merged**
