### PR TITLE
added ZipArchiver to actually compress zip files

### PR DESCRIPTION
**Pull request by jaypea**
the PharArchiver used to create zip files does not compress anything currently. 
when using satis with an archive directory, this new ZipArchiver saves a ton of hard disk space when the zip extension is enabled. 
fallback is the current behaviour using PharArchiver.

### CODE REVIEW

**Comment by andrerom** [comment]
@glye Regarding missing executable flags on archives made with PharArchiver *(with compression)*, maybe this would help?

**Comment by staabm** [comment]
//cc @alcohol

**Comment by alcohol** [comment]
@Seldaek was there anything at the time blocking this from being merged? Needs more review?

**Comment by Seldaek** [comment]
Seems fine I think.. mostly it just got forgotten. Thanks @jaypea!

**Pull request merged**
