### PR TITLE
Prefer the first https:// PEAR mirror; avoid http://.

### LINKED ISSUE #5069: Pear repository pear.php.net could not be loaded after upgrade to beta
Sample `composer.json`:

```
{
    "repositories": [
        {
            "type": "pear",
            "url": "https://pear.php.net"
        }
    ],
    "require": {
        "pear-pear.php.net/MDB2": "2.5.0-beta5"
    }
}
```

This **worked** with the previous snapshot, but does not work with latest `HEAD`.

Full output:

```
$ ~/devel/composer/bin/composer install
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Initializing PEAR repository https://pear.php.net
PEAR repository from https://pear.php.net could not be loaded. Your configuration does not allow connection to http://http://pear.php.net/rest/. See https://getcomposer.org/doc/06-config.md#secure-http for details.
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package pear-pear.php.net/mdb2 could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

This PEAR repository _does_ provide packages over `https://`, it is just not the default mirror. I suspect this is the issue. It would be nice if composer preferred the `https://` mirror when available.

```
$ curl https://pear.php.net/channel.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<channel version="1.0" xmlns="http://pear.php.net/channel-1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://pear.php.net/channel-1.0
http://pear.php.net/dtd/channel-1.0.xsd">
 <name>pear.php.net</name>
 <suggestedalias>pear</suggestedalias>
 <summary>PHP Extension and Application Repository</summary>
 <servers>
  <primary>
   <rest>
    <baseurl type="REST1.0">http://pear.php.net/rest/</baseurl>
    <baseurl type="REST1.1">http://pear.php.net/rest/</baseurl>
    <baseurl type="REST1.2">http://pear.php.net/rest/</baseurl>
    <baseurl type="REST1.3">http://pear.php.net/rest/</baseurl>
   </rest>
  </primary>
  <mirror host="us.pear.php.net">
   <rest>
    <baseurl type="REST1.0">http://us.pear.php.net/rest/</baseurl>
    <baseurl type="REST1.1">http://us.pear.php.net/rest/</baseurl>
    <baseurl type="REST1.2">http://us.pear.php.net/rest/</baseurl>
    <baseurl type="REST1.3">http://us.pear.php.net/rest/</baseurl>
   </rest>
  </mirror>
  <mirror host="de.pear.php.net" ssl="yes">
   <rest>
    <baseurl type="REST1.0">https://de.pear.php.net/rest/</baseurl>
    <baseurl type="REST1.1">https://de.pear.php.net/rest/</baseurl>
    <baseurl type="REST1.2">https://de.pear.php.net/rest/</baseurl>
    <baseurl type="REST1.3">https://de.pear.php.net/rest/</baseurl>
   </rest>
  </mirror>
 </servers>
</channel>
```

### PR DESCRIPTION
**Pull request by jdufresne**
Fixes #5069

### CODE REVIEW

**Comment by curry684** [comment]
:+1:

**Comment by Seldaek** [comment]
THanks

**Comment by AlexanderS** [comment]
This change breaks pear support! The ssl certificate of that pear mirror is expired:

    $ openssl s_client -connect de.pear.php.net:443 -servername de.pear.php.net 2>&1 | openssl x509 -noout -text | grep "Not After"
                Not After : Aug 21 06:07:48 2013 GMT

And because this mirror is automatically selected, it is not possible to use another mirror as workaround. 

Also note: The main pear mirror does support ssl but only does not promote it in the channel descriptions.

**Comment by barryvdh** [comment]
Isn't that a PEAR problem, which they should fix?

**Comment by Seldaek** [comment]
OK I pushed an ugly hack of a fix in https://github.com/composer/composer/commit/cb971fcb0edaa1e021279e8fb849253bd2bf52fc - @alecpl @AlexanderS can you confirm it fixes it?

**Comment by AlexanderS** [comment]
Yes, this fixes the issue. Thanks.

**Pull request merged**
