### PR TITLE
output used strategy

### PR DESCRIPTION
**Pull request by OskarStark**
I was a little bit confused, that the output is the same, regarding `-o` or `-a` option.

### CODE REVIEW

**Comment by alcohol** [comment]
While I agree more clarity could be beneficial to users here, the currently chosing phrasing seems a bit odd to me. I do not really see it as a strategy. We generate a classmap in either case, it is just that in one case, we consider the classmap to be completely authoritative.

**Comment by OskarStark** [comment]
So what is your opinion @alcohol ? Closing this PR? change the output?

**Comment by alcohol** [comment]
No need to close it, I would personally just prefer different phrasing. But this is merely my opinion.

My suggestion would be to just use the following two messages:

```
Generating optimized autoload files
```
```
Generating optimized autoload files (authoritative)
```

**Comment by OskarStark** [comment]
> My suggestion would be to just use the following two messages:

sounds good 👍

**Comment by Seldaek** [comment]
Thanks

**Pull request merged**
