### PR TITLE
Fossil VCS support for Composer

### PR DESCRIPTION
**Pull request by bohwaz**
This adds support for local and remote Fossil repositories as Composer packages.

Fossil is a popular DVCS that includes issues management, a wiki and more: https://www.fossil-scm.org/

### CODE REVIEW

**Comment by alcohol** [comment]
Looks good, I think. Cannot say I ever heard of Fossil though. But then again, we still support SVN too.

**Comment by staabm** [comment]
Misses at least some basic testcoverage

**Comment by alcohol** [comment]
Agreed.

**Comment by bohwaz** [comment]
Will add some tests asap

**Comment by bohwaz** [comment]
Done.

**Comment by Seldaek** [comment]
Thanks, looks like a fairly complete implementation.

**Pull request merged**
