### PR TITLE
Added cURL support as a Driver

### PR DESCRIPTION
**Pull request by flavioheleno**
The work is pretty rough, but is working.
It still lack of options to choose between file_get_contents driver (aka. stream driver) or curl (aka. curl driver).

### CODE REVIEW

**Comment by XedinUnknown** [comment]
Is it true that these changes could resolve the problem with pre-5.5 PHP versions and SSL, like it says [here](https://github.com/composer/composer/issues/1610#issuecomment-15032964)? If so, what is the status on this 4 year old PR? Perhaps this is done elsewhere? The issue with SSL is horrible, many PHP 5.3 or 5.4 environment can build without hacks, it appears.

**Comment by alcohol** [comment]
PHP 5.3 and 5.4 are dead.

**Comment by XedinUnknown** [comment]
PHP 5.3 - 5.5 are all dead. But that doesn't mean they're not used. Composer supports PHP 5.3. I try to push all WP developers to use Composer, and with Bedrock there's limited success. But if it's impossible to use Composer normally with pre-PHP5 versions, the whole WP community will be left behind. And believe me, I know that the WP community is full of mediocrity and really bad code and practices. But I really hope that this will change. Anyhow, usually it doesn't take much effort to keep software PHP 5.4+ compatible, and I would really like to be able to test on legacy versions too. Alas, with the SSH problems, building on PHP 5.4 is problematic.

**Comment by alcohol** [comment]
> Is it true that these changes could resolve the problem with pre-5.5 PHP versions and SSL, like it says here?

There is no actual data that suggests this to be true.

> If so, what is the status on this 4 year old PR?

It is out of sync with the repository. Also, adding cURL support has always been a controversial topic. It would be yet another PHP extension that users would have to install (though admittedly, it very often already is). Alternatively, it could be implemented in such a way that it would only be used if possible (based on presence of extension).

> But that doesn't mean they're not used.

We are not here to encourage bad behaviour. 5.3+ support is only available because that commitment was made when 1.x was originally developed. We are not building new features or functionality just to add additional support for PHP versions that are already EOL.

> But if it's impossible to use Composer normally with pre-PHP7 versions, the whole WP community will be left behind.

Drifting off-topic here, but it is perfectly doable to develop on a modern PHP version but still write code that is compatible with older PHP versions. Merely specify in your `composer.json` that your target platform is version `5.3` for example, and Composer will install dependencies as if you are running that version, even if your development machine would be running PHP `7.1` in actuality.

**Comment by jduartedj** [comment]
Curl support is a must, please add it!

**Comment by XedinUnknown** [comment]
> Merely specify in your composer.json that your target platform is version 5.3 for example, and Composer will install dependencies as if you are running that version, even if your development machine would be running PHP 7.1 in actuality. No more HTTPS issues.

That's what we've been doing. However, having to add and remove that config all the time is tedious and error prone.

**Comment by alcohol** [comment]
> having to add and remove that config all the time is tedious and error prone

Why remove it?

**Comment by jduartedj** [comment]
cUrl would solve a lot of problems, HTTPS issues (and optional config), proxy support, issues with  allow_url_fopen = false (where you can't change it) and overall security improvement. Downside is that your are trading a native solution for a plugin but in all fairness it is widely used anyway, I'm amazed it wasn't integrated into PHP 7+ as a native function!

**Comment by stof** [comment]
@jduartedj almost all builtin parts of PHP are actually built using PHP extensions. So having curl being a PHP extension makes perfect sense. Note that this extension is part of the PHP codebase directly, not a pecl extension.

**Comment by Seldaek** [comment]
Closed by https://github.com/composer/composer/pull/7904 which adds curl-multi support for the upcoming 2.0

**Pull request closed without merging**
