### PR TITLE
Improve documentation for WritableRepositoryInterface::getCanonicalPackages

### PR DESCRIPTION
**Pull request by MalteWunsch**
If I understand the API of `\Composer\Repository\WritableRepositoryInterface::getCanonicalPackages`:

```php
/**
 * Get unique packages, with aliases resolved and removed
 * @return PackageInterface[]
 */
public function getCanonicalPackages();
```

and `\Composer\Package\PackageInterface`:

```php
/**
 * Defines the essential information a package has that is used during solving/installation
 */
interface PackageInterface
{
    // ...

    /**
     * Returns the version of this package
     * @return string version
     */
    public function getVersion();
```

correctly, `getCanonicalPackages` should return multiple packages with the same name in different versions. At least we were expecting that behaviour as `\Composer\Repository\FilesystemRepository::write` makes use of it. Or am I thinking in a wrong direction?

### CODE REVIEW

**Comment by stof** [comment]
This change is breaking tests

**Comment by MalteWunsch** [comment]
Ooops. Got a segmentation fault when running the whole test suite locally, and before fixing that, I lazily wanted Travis to have a shot.

I'm not really sure why the tests are breaking, but I'd be willing to dig into that If one can assure me the API is meant the way I think, i.e. the idea of this PR is right?

**Comment by stof** [comment]
they are breaking because you are now writing too much stuff to the filesystem repository. so it looks like the current behavior was expected

**Comment by MalteWunsch** [comment]
Makes sense. So documenting would be the better PR?

**Comment by Seldaek** [comment]
Thanks

**Pull request merged**
