### PR TITLE
Add feature for issue #6892

### PR DESCRIPTION
**Pull request by swumao**
Add feature for issue #6892

### CODE REVIEW

**Comment by Seldaek** [comment]
This is not really fixing it to use the actual case from the package though, it just lowercases it. Packagist.org enforces lowercased names but if you access/publish the package differently it can very well have a different name.

**Comment by swumao** [comment]
Should I replace the package name with the Packagist.org's package name ?

**Comment by Seldaek** [comment]
Yes it should use the name from the Package instance (getPrettyName) we get back but I am not sure how easy it is to do that to be honest.

**Comment by Seldaek** [comment]
Great thanks for the update

**Comment by kubawerlos** [comment]
Thanks @swumao

**Pull request merged**
