### PR TITLE
Bump symfony/process to 2.3 - and raise minimum php to 5.3.3

### PR DESCRIPTION
**Pull request by AydinHassan**
Refs #5828 

I've only updated `composer.json` - let me know if there is something else that should be added.

### CODE REVIEW

**Comment by alcohol** [comment]
Should probably update the lock file too (`composer update --lock`)?

**Comment by alcohol** [comment]
Unable to rebase it? If it is too much work for you, we can probably do it. We just appreciate it if you could do it instead, cause it saves us the hassle.

**Comment by AydinHassan** [comment]
@alcohol no it's fine - will do it after work :)

**Comment by alcohol** [comment]
Ok. Was just checking, cause I saw you changed the target but then changed it back :-)

**Comment by AydinHassan** [comment]
I thought it was as simple as that, but I have to rebase locally and fix some conflicts, will probably be quicker to just do it again 😄

**Comment by alcohol** [comment]
Yeah, probably will be. You could use the patch. Simply take the commit diff (2 commits in this case) and apply it on a new branch:

```
git format-patch -2 HEAD --stdout > /tmp/composer.patch
git checkout -b new_branch <remotename>/1.2
git apply - < git.patch
```

**Comment by curry684** [comment]
For 2 lines redoing the change on the proper branch is always faster  😆

**Comment by AydinHassan** [comment]
@alcohol should be done now - let me know if there's anything else

**Comment by alcohol** [comment]
Thanks

**Comment by Seldaek** [comment]
Thanks but re 5.3.3 bump I don't think this matters much as of our users don't install composer via composer so this has little impact. But anyway this shouldn't reflect the minimum version required by our deps but by our own code. Composer takes care of enforcing the minimum version required by the deps.

**Pull request closed without merging**
