### PR TITLE
Fix error handling for incorrect "repositories" array

### PR DESCRIPTION
**Pull request by theravel**
This is the fix for this issue:
https://github.com/composer/composer/issues/3654

Take a look at the screenshots:

Before fix:
screenshot from 2015-01-20 13 14 18

After fix:
screenshot from 2015-01-20 13 14 33

### CODE REVIEW

**Comment by Seldaek** [comment]
Thanks

**Comment by alcohol** [comment]
Don't mean to be a wanker, but the error message you provided is misleading.

Type should not be an array. Repositories instead expects an array, not an object. Example:

```
"repositories": [
        { "type": "vcs", "url": "http://github.com/mycompany/privaterepo" },
        { "type": "vcs", "url": "http://svn.example.org/private/repo" },
        { "type": "vcs", "url": "http://github.com/mycompany/privaterepo2" }
    ]
```

Can I suggest adjusting and resubmitting the PR?

**Comment by theravel** [comment]
@alcohol "type" here is considered as repository name, not repository type. But I agree message looks misleading. Probably should we change it to:
```
Repository "type" ("vcs") should be an array, string given
```

**Comment by Seldaek** [comment]
I'll adjust it.

**Comment by alcohol** [comment]
I would just change it to, but feel free to improvise

```
Repositories should be an array of repository defintions, repository given
```

**Pull request merged**
