### PR TITLE
Fix #4183 - exclude pattern containing delimiter used throws error

### LINKED ISSUE #4183: ArchivableFilesFinder fails with some entries in .gitignore
It appears to execute regular expressons based on unescaped values in .gitignore.

For instance, adding ```\#*```

to .gitignore causes satis to fail hard.

```
[ErrorException]                    
  preg_match(): Unknown modifier '['  
                                      


Exception trace:
 () at /Users/thyde/code/cd-satis/satis/vendor/composer/composer/src/Composer/Package/Archiver/BaseExcludeFilter.php:62
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 preg_match() at /Users/thyde/code/cd-satis/satis/vendor/composer/composer/src/Composer/Package/Archiver/BaseExcludeFilter.php:62
 Composer\Package\Archiver\BaseExcludeFilter->filter() at /Users/thyde/code/cd-satis/satis/vendor/composer/composer/src/Composer/Package/Archiver/ArchivableFilesFinder.php:67
 Composer\Package\Archiver\ArchivableFilesFinder::Composer\Package\Archiver\{closure}() at n/a:n/a
 call_user_func() at /Users/thyde/code/cd-satis/satis/vendor/symfony/finder/Symfony/Component/Finder/Iterator/CustomFilterIterator.php:56
 Symfony\Component\Finder\Iterator\CustomFilterIterator->accept() at n/a:n/a
 FilterIterator->rewind() at /Users/thyde/code/cd-satis/satis/vendor/symfony/finder/Symfony/Component/Finder/Iterator/FilterIterator.php:47
 Symfony\Component\Finder\Iterator\FilterIterator->rewind() at n/a:n/a
 FilterIterator->rewind() at n/a:n/a
 PharData->buildFromIterator() at /Users/thyde/code/cd-satis/satis/vendor/composer/composer/src/Composer/Package/Archiver/PharArchiver.php:42
 Composer\Package\Archiver\PharArchiver->archive() at /Users/thyde/code/cd-satis/satis/vendor/composer/composer/src/Composer/Package/Archiver/ArchiveManager.php:160
 Composer\Package\Archiver\ArchiveManager->archive() at /Users/thyde/code/cd-satis/satis/src/Composer/Satis/Command/BuildCommand.php:410
 Composer\Satis\Command\BuildCommand->dumpDownloads() at /Users/thyde/code/cd-satis/satis/src/Composer/Satis/Command/BuildCommand.php:159
 Composer\Satis\Command\BuildCommand->execute() at /Users/thyde/code/cd-satis/satis/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
 Symfony\Component\Console\Command\Command->run() at /Users/thyde/code/cd-satis/satis/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /Users/thyde/code/cd-satis/satis/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at /Users/thyde/code/cd-satis/satis/src/Composer/Satis/Console/Application.php:52
 Composer\Satis\Console\Application->doRun() at /Users/thyde/code/cd-satis/satis/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /Users/thyde/code/cd-satis/satis/bin/satis:9
```

### PR DESCRIPTION
**Pull request by alcohol**
Added test to reproduce #4183

Not sure on what the best way to fix it would be..

* Escape any delimiter characters used in the pattern?
* Use a different delimiter?

/cc @Seldaek @stof

### CODE REVIEW

**Comment by staabm** [comment]
Using a different delimiter does sound like a good idea. someone will collide with it again ;-).

could we do a `preg_quote` instead?

**Comment by alcohol** [comment]
I think `preg_quote` would escape too much (I did consider it for a moment). I think escaping the delimiter is the most elegant solution.

**Comment by Seldaek** [comment]
That's why I use {} as delimiters always.. because they are already special chars that you need to escape, and don't cause fuckups like this. Just convert the `#` delimiter to `{`/`}` and it should fix this issue as far as I can tell.

**Comment by staabm** [comment]
:+1:

**Pull request merged**
