### PR TITLE
Allow Symfony 5

### PR DESCRIPTION
**Pull request by kylekatarnls**

### CODE REVIEW

**Comment by kylekatarnls** [comment]
The `continuous-integration/appveyor/pr — AppVeyor build failed` error seems not related to this change as it downloads symfony 2.* version.

**Comment by Seldaek** [comment]
Thanks

**Comment by peter-gribanov** [comment]
When can i expect a release with this feature?

**Comment by Seldaek** [comment]
When it's done. But most likely soon.

**Comment by TomasVotruba** [comment]
This block my Symfony 5.0 build :/

**Comment by brianfreytag** [comment]
@Seldaek Do you have an update on this? I'm still trying to get my 5.0 upgrade going, but this is holding us up.

**Comment by kylekatarnls** [comment]
🙏 Please a minor version with this PR.

**Comment by Seldaek** [comment]
1.10.0-RC is out now.. Please note that you could also have required `"composer/composer": "^1.10@dev"` to use pre-release code without pestering us about a release..

Anyway now you can use `"composer/composer": "^1.10@RC"` which is rather future proof, or if you are using composer as a CLI util `composer self-update --preview`

**Comment by kylekatarnls** [comment]
Thanks @Seldaek but sorry it's not the same, when you deliver a library using composer/composer and wanting to be compatible with symfony 5, requiring `"^1.10@dev"` won't make your library compatible with Symfony 5 for users that stay on `"minimum-statbility": "stable"` you can only choose `@dev` if you're on the end of the chain. And it requires to undertake the instability risk.

So I would say, providing dev/alpha/beta/RC channels is nice and I thank your for it. But it can't exactly substitute stable releases. Until a stable release, composer is still not compatible with Symfony 5.

Of course releasing an RC before the stable and waiting for feedback on it is the right move.

So thanks!

**Comment by Seldaek** [comment]
Yup fair enough for libraries this is trickier, although it would let you fix your build at least.. and let users who really want also require composer/composer `@dev` or `@RC` to allow it to install. But anyway I hope there are not too many issues with the RC and we can move on to a final release soon.

**Comment by barryvdh** [comment]
Don't want to rush/pressure you, but do you happen to have an ETA for the release of 1.10? Since it's also not compatible with Laravel 7. If not anytime soon, I'll just workaround using a different Classmap generator.

**Comment by Seldaek** [comment]
Early next week 90% sure :)

**Comment by Seldaek** [comment]
1.10.0 is out now

**Comment by barryvdh** [comment]
Thank you very much!

**Pull request merged**
