### PR TITLE
Cleanup of old compression algo

### PR DESCRIPTION
**Pull request by Seldaek**
Follow-up to https://github.com/composer/composer/pull/7904 - needs all packages to have been re-dumped though before it can be merged.

### CODE REVIEW

**Comment by stof** [comment]
@Seldaek idea to reduce the file size for packagist files: skip the dumping of `require-dev` constraint. Composer only cares about the dev requirements of the root package, and the metadata of the root package are available locally, not from Packagist.

Packagist already strips the `support` info of the package, which are actually more useful for composer (as `composer show` is then unable to display the support info)

**Comment by stof** [comment]
this PR should be rebased so that the diff does not include #7904

**Comment by stof** [comment]
@Seldaek idea for the new minification format: instead of dealing only with top-level keys, we could replicate the same algo on the second level for keys defining constraint (`require`, `conflict`, etc...). this way, adding a new requirement or changing a min version for a requirement does not need to include all other requirements again.

**Comment by naderman** [comment]
I would actually prefer we didn't strip any info, neither require-dev nor support, so they do remain available for inspection, I think this kind of mechanism should save enough space already. I do agree that it may be worth to investigate doing this on a second level as well.

**Comment by Seldaek** [comment]
@stof I tried applying the same diff algo to require/... - it doesn't help much, after gzip is done with the file it's hardly noticeable so I think it's best to leave it as is to avoid even more complexity and chance of bugs.

**Comment by stof** [comment]
well, if it does not make difference after gzip, this is fine then. That was just an idea.

**Comment by Seldaek** [comment]
Yup it was worth a shot

**Comment by staabm** [comment]
Regarding content-encoding: would it be worth to try brotli or similar more modern compression ?

**Comment by Seldaek** [comment]
I'd love to but nginx makes it a PITA so it's still on the backburner. Anyway this can be added later on without BC break so not critical for 2.0

**Comment by staabm** [comment]
Agree - its not critical for 2.0.
Side note: maybe packagist could use a cdn like cloudflare or similar and let this kind of feature be handled by the cdn?

**Pull request merged**
