### PR TITLE
Keep-Alive by curl (boost downloading speed)

### PR DESCRIPTION
**Pull request by hirak**
Hello. I came from Japan.

packagist.org (Belgium) is far from Japan. Round Trip Time is so long, it takes very long to `composer install`, I am frustrated.

So, I wrote a patch reusing TCP connection (Keep-Alive) by ext-curl. Download time can be shortened. In particular, in countries where it is from packagist.org farther (Japan such as ), the effect will be higher.

Before coding this patch, I read Pull Requests and Issues. It seems difficult to keep compatibility with past ideas. I tried to implement the curl RemoteFileSystem by emulating the default "http"/"https" streamWrapper.

Finally, since I send pull request first time to this repo, please let me know if my manners is wrong. 

relates:
- #704
- #3282 
- #3636
- #2696 more better ? it looks stopped.

### CODE REVIEW

**Comment by stof** [comment]
I don't like this approach replacing the http and https stream wrappers. It could create many weird behaviors for other libraries using PHP streams in the same process (either scripts called by Composer on some events, or cases where composer itself is used as a library by another project)

**Comment by hirak** [comment]
Uhh. You're right. I'll rethink the idea.

**Comment by stof** [comment]
IIRC, there is already a PR implementing the RemoteFilesystem class over curl.

**Comment by hirak** [comment]
I tried taking a simple benchmark. :-)
Keep-Alive help improve performance.
I will take a look at the other PR again. Thank you.

```bash
# prepare
$ mkdir composer-bench
$ cd composer-bench
```

### Keep-Alive off (original composer)
```bash
$ composer --version
Composer version 1.0-dev (475c84d4b1632653b115a4846125f276119db259) 2015-02-25 16:53:56

$ rm -rf ~/.composer/cache  #clear cache
$ rm -rf * #clear cache
$ composer require symfony/symfony --no-progress --profile
Using version ~2.6 for symfony/symfony
./composer.json has been created
[43.8MB/4.06s] Loading composer repositories with package information
[44.2MB/4.12s] Updating dependencies (including require-dev)
[133.4MB/10.76s]   - Installing psr/log (1.0.0)
[133.4MB/10.76s]     Downloading
[133.5MB/13.12s]
[133.5MB/13.12s]   - Installing twig/twig (v1.18.0)
[133.5MB/13.12s]     Downloading
[133.6MB/17.21s]
[133.6MB/17.21s]   - Installing doctrine/lexer (v1.0.1)
[133.6MB/17.21s]     Downloading
[133.6MB/19.36s]
[133.6MB/19.36s]   - Installing doctrine/annotations (v1.2.3)
[133.6MB/19.36s]     Downloading
[133.6MB/22.02s]
[133.6MB/22.03s]   - Installing doctrine/collections (v1.2)
[133.6MB/22.03s]     Downloading
[133.6MB/24.80s]
[133.6MB/24.80s]   - Installing doctrine/cache (v1.4.0)
[133.6MB/24.80s]     Downloading
[133.7MB/27.85s]
[133.6MB/27.86s]   - Installing doctrine/inflector (v1.0.1)
[133.6MB/27.86s]     Downloading
[133.7MB/30.62s]
[133.6MB/30.63s]   - Installing doctrine/common (v2.4.2)
[133.6MB/30.63s]     Downloading
[133.7MB/36.58s]
[133.7MB/36.59s]   - Installing symfony/symfony (v2.6.4)
[133.7MB/36.59s]     Downloading
[134.7MB/48.86s]
[133.1MB/51.05s] Writing lock file
[133.1MB/51.05s] Generating autoload files
Memory usage: 133.21MB (peak: 147.04MB), time: 51.07s
```

### Keep-Alive on (my patch)
```bash
$ composer --version
Composer version 1.0-dev (67c788dfc985871f34baaf8834bfe351cd38fa18) 2015-02-24 14:06:11

$ rm -rf ~/.composer/cache  #clear cache
$ rm -rf * #clear cache
$ composer require symfony/symfony --no-progress --profile
Using version ~2.6 for symfony/symfony
./composer.json has been created
[44.2MB/3.51s] Loading composer repositories with package information
[43.9MB/3.54s] Updating dependencies (including require-dev)
[136.3MB/8.54s]   - Installing psr/log (1.0.0)
[136.8MB/8.55s]     Downloading
[136.9MB/10.81s]
[136.9MB/10.81s]   - Installing twig/twig (v1.18.0)
[136.9MB/10.81s]     Downloading
[137.9MB/13.16s]
[137.8MB/13.16s]   - Installing doctrine/lexer (v1.0.1)
[137.8MB/13.16s]     Downloading
[137.0MB/13.77s]
[137.0MB/13.77s]   - Installing doctrine/annotations (v1.2.3)
[137.0MB/13.77s]     Downloading
[137.1MB/14.32s]
[137.0MB/14.33s]   - Installing doctrine/collections (v1.2)
[137.0MB/14.33s]     Downloading
[137.1MB/14.80s]
[137.0MB/14.81s]   - Installing doctrine/cache (v1.4.0)
[137.0MB/14.81s]     Downloading
[137.2MB/15.50s]
[137.1MB/15.51s]   - Installing doctrine/inflector (v1.0.1)
[137.1MB/15.51s]     Downloading
[137.1MB/16.13s]
[137.0MB/16.14s]   - Installing doctrine/common (v2.4.2)
[137.0MB/16.14s]     Downloading
[137.4MB/17.17s]
[137.4MB/17.18s]   - Installing symfony/symfony (v2.6.4)
[137.4MB/17.18s]     Downloading
[151.2MB/31.70s]
[149.6MB/33.41s] Writing lock file
[149.6MB/33.41s] Generating autoload files
Memory usage: 149.85MB (peak: 163.52MB), time: 33.43s
```

**Pull request closed without merging**
