### PR TITLE
Updated the version

### PR DESCRIPTION
**Pull request by ron4stoppable**
updated the version to the latest

### CODE REVIEW

**Comment by alcohol** [comment]
It's going to be tedious to update this on every new release. Maybe the output should just be made more generic.

**Comment by staabm** [comment]
@alcohol this looks like something which only makes sense when automated.

when composer would support some kind of "release" command and a corresponding scripts-hook this could be implemented as part of the release process.

**Comment by alcohol** [comment]
Considering our documentation isn't even tied to a specific version yet, this is not very feasible at the moment.

**Comment by Seldaek** [comment]
Yeah I don't really see the point anyway.. it's obviously an example in the docs.

**Comment by ron4stoppable** [comment]
okay, it should be more atomic version than like 1.0, 2.0, etc; right?

**Pull request closed without merging**
