### PR TITLE
[WIP] Progress Tracker

### PR DESCRIPTION
**Pull request by dantleech**
As discussed in https://github.com/composer/composer/issues/2809

This WIP PR adds a `WorkTracker` set of classes which allow progress to be registered and subsequently evaluated by a work tracker formatter.

Currently progress is only tracked for the dependency resolution process (i.e. all the time that passes before it starts installing packages).

- [x] Review the code
- [ ] Implement progress tracking for the rest of the installation process (?)
- [ ] Improve output formatters

## Work Trackers

Work trackers have the methods `complete` and `ping` (to register a progression) in addition to factory methods for creating *nested* work trackers. 

There are three work tracker classes. One is a contextual tracker, which is used to access the *current* tracker the other two are `BoundedWorktracker` for tracking progressions with a known number of steps and `UnboundedWorkTracker` for handling progressions of an undefined length.

Library classes that need to track their progress are always injected with the `ContextWorkTracker`.

## Output

The output is managed by a class implementing the `FormatterInterface`.

The output formatter that will be used is determined by the `--pretty` option.

Because the work trackers are nested it is possible to produce hierchical output.

````
$ ./bin/composer install --pretty=multi                                                                                                             ⏎
[5/5] Installing dependencies (including require-dev)                                                             
[81/160] Getting rules for "70" jobs with "80" installed packages                                                 
[1/-] Add rules for package symfony/yaml
````

There is also a verbose debug formatter:

````
$ ./bin/composer install --pretty=debug | less                                                                                                                 ⏎
  BEGIN: Dispatching pre update event
  DONE: Dispatching pre update event
  BEGIN: Adding repsoitories
  PING: [#000001] [2.0231s] Adding repsoitories
  DONE: Adding repsoitories
  BEGIN: Removing unstable packages from the local repository (if they don't match the current stablitity settings)
  PING: [#000001] [0.0002s] Removing unstable packages from the local repository (if they don't match the current stablitity settings)
  PING: [#000002] [0.0001s] Removing unstable packages from the local repository (if they don't match the current stablitity settings)
  PING: [#000003] [0.0001s] Removing unstable packages from the local repository (if they don't match the current stablitity settings)
  PING: [#000004] [0.0001s] Removing unstable packages from the local repository (if they don't match the current stablitity settings)
  PING: [#000005] [0.0001s] Removing unstable packages from the local repository (if they don't match the current stablitity settings)
  PING: [#000006] [0.0001s] Removing unstable packages from the local repository (if they don't match the current stablitity settings)
  PING: [#000007] [0.0001s] Removing unstable packages from the local repository (if they don't match the current stablitity settings)
  PING: [#000008] [0.0001s] Removing unstable packages from the local repository (if they don't match the current stablitity settings)
  PING: [#000009] [0.0001s] Removing unstable packages from the local repository (if they don't match the current stablitity settings)
  PING: [#000010] [0.0001s] Removing unstable packages from the local repository (if they don't match the current stablitity settings)
  PING: [#000011] [0.0001s] Removing unstable packages from the local repository (if they don't match the current stablitity settings)
  PING: [#000012] [0.0001s] Removing unstable packages from the local repository (if they don't match the current stablitity settings)
  PING: [#000013] [0.0000s] Removing unstable packages from the local repository (if they don't match the current stablitity settings)
  PING: [#000014] [0.0000s] Removing unstable packages from the local repository (if they don't match the current stablitity settings)
  DONE: Removing unstable packages from the local repository (if they don't match the current stablitity settings)
  BEGIN: Installing dependencies (including require-dev)
  PING: [#000001] [0.0001s] Installing dependencies (including require-dev)
  PING: [#000002] [0.0000s] Installing dependencies (including require-dev)
  PING: [#000003] [0.0000s] Installing dependencies (including require-dev)
  PING: [#000004] [0.0000s] Installing dependencies (including require-dev)
  PING: [#000005] [0.0000s] Installing dependencies (including require-dev)
  DONE: Installing dependencies (including require-dev)
Solving dependencies
  BEGIN: Getting rules for "70" jobs with "80" installed packages
    BEGIN: Whitelist from package
...
````

### CODE REVIEW

**Comment by neon64** [comment]
A few months ago I decided to bring this fork back up to date, finish integrating the work tracker, and fix up all the tests. You can see the results on my fork.

https://github.com/neon64/composer

I opened a pull request to @dantleech's fork (https://github.com/dantleech/composer/pull/1) but after 3 months I haven't heard anything. I wanted to ask around here whether or not the Composer developers think this is something worth getting into master.

Personally, I have been using the fork a little bit on large Laravel projects with lots of dependencies. With the fancy `--progress=global-progress-bar` option, it probably results in a slight loss of performance overall, but at least I can see what is going on.

With `npm` now showing a progress bar by default I think it has almost become the norm for package managers, so it would be nice to see composer keep up in that respect. (I'll probably get roasted for this but...)

**Comment by Seldaek** [comment]
Yeah pointing to npm given what we saw at https://github.com/npm/npm/issues/11283 isn't really a great role model :p

Anyway, I see you also have #3376 opened which is a competing implementation to this one. Would you say it's better or inferior? Why?

Both PRs are fairly intrusive though, and tbh the value of this feature is fairly dodgy to me, it is at best making people feel better because they see something move, but it's not a real indicator of anything meaningful, so if it's just about the psychological effect I think we could do it a lot easier and with less lines of code spread all over.

**Comment by neon64** [comment]
#3376 was a really quick implementation designed to output basic stats to a JSON file.
This PR has unlimited nesting of work trackers and probably a better API. Additionally I've now put more work into this one, and completed the user-facing side of things (controlling the output with `--progress=xyz`). So my old PR is definitely inferior (therefore I closed it).

I agree that integrating the work tracker system requires changes to basically every core file in Composer, however most of the time it is single liners (`$this->io->getWorkTracker()->createBound/createUnbound/complete()`) which could actually help understand of how loops are structured/what sections are slow. At the moment the default `--progress=empty` shouldn't actually output anything and therefore have little performance impact. (I need to test that though)

**Comment by Seldaek** [comment]
Thanks for the explanation and the work on this folks but the more I think about it the more I disagree we need this. So closing as won't fix.

**Pull request closed without merging**
