### PR TITLE
Add `composer i` shorthand for `composer install`

### PR DESCRIPTION
**Pull request by rellect**
In npm I really like this shorthand `npm i`
So thought it may also be convenient in composer

### CODE REVIEW

**Comment by apfelbox** [comment]
:+1:

it currently conflicts, as both `install` and `init` start with the same two letters. But I would argue that `install` is used way more often than `init` so we should optimize the common case.

Same thing please for `composer u` to link to `update` (Symfony Flex adds `unpack` which conflicts with `update`).

**Comment by Seldaek** [comment]
In principle I'm not against this, but I wish it could be done without adding those aliases in the list of commands. We already have a few duplicates in there like dump-autoload/dumpautoload, update/upgrade, clear-cache/clearcache. I'm happy to help people but it's slowly making the help output garbage.. 

Can anyone research if it isn't possible to avoid listing aliases in the list command? Or maybe we do the aliasing in bin/composer before starting the application?

**Comment by stof** [comment]
@Seldaek the Symfony ListCommand does not display aliases anymore in the list of commands (it displays the available aliases in the description of the listed commands itself). But the issue here is that the composer phar ships with symfony/console 2.8 (to make the phar compatible with PHP 5.3) and so does not benefit from changes done in 3.x

**Comment by Seldaek** [comment]
Ok thanks @stof for the update. In that case I'm fine merging this for now and the aliases will vanish in time.

**Comment by Seldaek** [comment]
@rellect would you mind adding `u` for the UpdateCommand too though? For completeness it probably makes sense.

**Comment by rellect** [comment]
@Seldaek Sure, done.

**Comment by Seldaek** [comment]
Thanks

**Pull request merged**
