### PR TITLE
Add dry run update and install events

### LINKED ISSUE #4650: Update event with --dry-run option
Actually, if we launch `update` command with `--dry-run` option, absolutely [no script events is launched](https://github.com/composer/composer/blob/master/src/Composer/Installer.php#L193-L197).

I think those events should be dispatched in any case, but with the `--dry-run` option value inside or, at least, add another events like `PRE_DRY_UPDATE_CMD` / `POST_DRY_UPDATE_CMD`.

This will permit plugins to get information about dry run install and update commands.

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Closes #4650.

### CODE REVIEW

**Comment by alcohol** [comment]
I personally don't think these should be different/new events. It makes more sense to me to fire the same events as we usually would; but the options that the command received should be passed along with it somehow (e.g. that it is a dry-run).

**Comment by Seldaek** [comment]
Yeah I agree this fix doesn't make sense to me. But obviously if we start firing the events and plugins do crazy shit (tm) it's not gonna be good either. I am not sure what the best way is.. but down the line a dry run shouldn't really need to trigger the scripts IMO. What's the use case really?

**Comment by Soullivaneuh** [comment]
> Yeah I agree this fix doesn't make sense to me.

I was thinking about that at start.

> But obviously if we start firing the events and plugins do crazy shit (tm) it's not gonna be good either.

Yeah. For example on Symfony projects, some scripts will be called on crash.

> but down the line a dry run shouldn't really need to trigger the scripts IMO. What's the use case really?

Maybe for project scripts, not for plugin. For the use case, I wrote a plugin that will show you outdated package after an update: https://github.com/Soullivaneuh/composer-versions-check

This will be useful if users can simulate an update just to see the plugin result.

**Comment by Seldaek** [comment]
For that use case I think it'd be better to allow plugins to add new 
commands (there's a PR for it already I believe). Having to do a dry run 
or even an update at all to see the output doesn't make so much sense I 
think.

**Comment by Soullivaneuh** [comment]
> For that use case I think it'd be better to allow plugins to add new
commands (there's a PR for it already I believe).

You got my curiosity. Can you tell me which PR?

> Having to do a dry run
or even an update at all to see the output doesn't make so much sense I
think.

If I can add a command through my plugin, in this case I agree.

But I think that dry-run events is still a good idea. Can be used by others.

**Comment by Soullivaneuh** [comment]
I found indeed too PR like that:

* https://github.com/composer/composer/pull/3377
* https://github.com/composer/composer/pull/4124

**Comment by Soullivaneuh** [comment]
I had to delete my fork to start a new one.

Tell me if I have to change something In this case, I'll open another PR.

**Comment by Seldaek** [comment]
Yeah I think those PRs are more the way to go, I don't want to add a copy of every event for dry run mode.

**Pull request closed without merging**
