### PR TITLE
Expose composer package version

### PR DESCRIPTION
**Pull request by lstrojny**
See #9963

### CODE REVIEW

**Comment by Seldaek** [comment]
Looks good to me, but will be stalled until we branch off 2.2.

**Comment by alcohol** [comment]
Not to nitpick, but could you please also update documentation as mentioned in the original issue?

> Also needs very good and clear documentation to avoid confusing the hell out of people with all these platform packages.

Thanks in advance!

**Comment by Seldaek** [comment]
@lstrojny can you please rebase this when you get a chance? If you do find time to also look at documenting this it'd be even better, but if not I guess I will have to do that.

**Comment by helhum** [comment]
Will rebase now and give the documentation a shot

**Comment by helhum** [comment]
Since I'm not allowed to push onto this PR and didn't want to create a PR for a PR, I created a [new PR](#10313).
I kept the commits as they were (except that I rebased) and added the docs as commit on top.

@lstrojny feel free to get the commit from my branch and push it on top here.

**Comment by Seldaek** [comment]
Thanks @lstrojny, closing as it is included in https://github.com/composer/composer/pull/10313

**Pull request closed without merging**
