### PR TITLE
Mention need to require autoloader in hooks using functions

### PR DESCRIPTION
**Pull request by jeskew**
Add a line and example to the documentation covering the need to require the autoloader file in order to use autoloaded files.

Addresses #4184

### CODE REVIEW

**Comment by alcohol** [comment]
This will fail if `autoload.php` does not exist yet.

**Comment by jeskew** [comment]
@alcohol As we discussed in the issue related to this PR, I believe the existing disclaimer about the state of the autoloader being undetermined in pre-install and pre-update commands covers the possible non-existence of `vendor/autoload.php`. I could repeat part of that disclaimer in the bullet point added in this PR if you believe it's unclear.

**Comment by alcohol** [comment]
Well at least set a good example :-(. 
Don't use string interpolation, `$vendorDir . '/autoload.php'` is cleaner.

Also I think the current wording is a bit vague as to what _kind_ of functions you are referring to. Remove the reiteration of the disclaimer (it's not necessary), and try to emphasise it's about functions that are normally only available via the `files` autoload attribute.

**Comment by jeskew** [comment]
What phrasing would you suggest is more clear than 'functions defined outside of a class'?

I've always found interpolation to be cleaner, and since there's [no performance difference](http://nikic.github.io/2012/01/09/Disproving-the-Single-Quotes-Performance-Myth) between interpolation and concatenation, we'll have to agree to disagree on the aesthetics.

**Comment by alcohol** [comment]
We can disagree on aesthetics, but we can agree on convention. So if you don't mind.

**Comment by alcohol** [comment]
As for phrasing, maybe it's better to turn it around and simply make it more clear that "must be autoloadable via Composer's autoload functionality" does not mean that the autoloader is actually loaded, but merely that the same mechanism is used and that this only applies to the `psr-0`, `psr-4` and `classmap` autoload types, not `files`.

**Comment by jeskew** [comment]
@alcohol Were there any other changes you wanted to see made?

**Comment by alcohol** [comment]
Well,

> If a defined callback relies on functions defined outside of a class, the callback itself is responsible for loading the appropriate files, as no files beyond those required for `psr-0`, `psr-4`, and `classmap` autoloading are loaded during Composer commands.

could probably better be phrased as

> Callbacks can only autoload classes from psr-0, psr-4 and classmap definitions. If a defined callback relies on functions defined outside of a class, the callback itself is responsible for loading the file containing these functions.

**Pull request merged**
