### PR TITLE
Fixed a minor glitch in console output in debug mode

### PR DESCRIPTION
**Pull request by sakshamsaxena**
This is a PR for #7437. Feel free to try this out and review how it looks (especially the downloading step).

### CODE REVIEW

**Comment by sakshamsaxena** [comment]
Running Composer first time when it downloads packages :
```
[6.2MiB/0.01s] Loading composer repositories with package information
[6.6MiB/1.12s] Updating dependencies (including require-dev)
[200.0MiB/48.71s] Dependency resolution completed in 0.073 seconds
[200.1MiB/48.71s] Analyzed 1137 packages to resolve dependencies
[200.1MiB/48.71s] Analyzed 102049 rules to resolve dependencies
[200.1MiB/48.71s] Package operations: 5 installs, 0 updates, 0 removals
[200.1MiB/48.71s] Installs: symfony/polyfill-mbstring:v1.10.0, symfony/contracts:v1.0.2, symfony/console:v4.2.4, psr/log:1.1.0, symfony/debug:v4.2.4
[200.1MiB/48.72s]   - Installing symfony/polyfill-mbstring (v1.10.0): [200.2MiB/50.26s] [200.2MiB/50.26s] [200.2MiB/50.27s] [200.2MiB/50.36s] [200.2MiB/50.36s] Downloading (100%)
[200.2MiB/50.36s]     Extracting archive
[200.2MiB/50.40s]   - Installing symfony/contracts (v1.0.2): [200.2MiB/52.09s] [200.3MiB/52.09s] [200.3MiB/52.18s] [200.3MiB/52.18s] [200.3MiB/52.18s] Downloading (100%)
[200.2MiB/52.18s]     Extracting archive
[200.2MiB/52.22s]   - Installing symfony/console (v4.2.4): [200.3MiB/54.98s] [200.3MiB/55.21s] [200.3MiB/55.49s] [200.3MiB/55.69s] [200.3MiB/55.90s] [200.3MiB/55.90s] [200.3MiB/56.08s] [200.4MiB/56.31s] [200.4MiB/56.50s] [200.4MiB/56.67s] [200.4MiB/56.68s] [200.4MiB/57.35s] [200.4MiB/57.53s] [200.4MiB/57.54s] [200.4MiB/57.71s] [200.5MiB/57.71s] [200.5MiB/58.35s] [200.5MiB/58.56s] [200.5MiB/58.56s] [200.5MiB/58.80s] [200.5MiB/58.80s] Downloading (100%)
[200.2MiB/58.80s]     Extracting archive
[200.2MiB/58.96s]   - Installing psr/log (1.1.0): [200.3MiB/60.41s] [200.3MiB/60.41s] [200.3MiB/60.41s] [200.2MiB/60.42s] Downloading (100%)
[200.2MiB/60.42s]     Extracting archive
[200.2MiB/60.44s]   - Installing symfony/debug (v4.2.4): [200.3MiB/62.15s] [200.3MiB/62.15s] [200.3MiB/62.15s] [200.3MiB/62.25s] [200.3MiB/62.25s] [200.3MiB/62.33s] [200.3MiB/62.41s] [200.3MiB/62.42s] [200.3MiB/62.50s] [200.3MiB/62.50s] [200.3MiB/62.51s] Downloading (100%)
[200.2MiB/62.51s]     Extracting archive
[151.6MiB/64.02s] symfony/contracts suggests installing psr/cache (When using the Cache contracts)
[151.6MiB/64.02s] symfony/contracts suggests installing psr/container (When using the Service contracts)
[151.6MiB/64.02s] symfony/contracts suggests installing symfony/cache-contracts-implementation
[151.6MiB/64.02s] symfony/contracts suggests installing symfony/service-contracts-implementation
[151.6MiB/64.02s] symfony/contracts suggests installing symfony/translation-contracts-implementation
[151.6MiB/64.02s] symfony/console suggests installing symfony/event-dispatcher
[151.6MiB/64.02s] symfony/console suggests installing symfony/lock
[151.6MiB/64.02s] symfony/console suggests installing symfony/process
[151.6MiB/64.02s] Writing lock file
[151.6MiB/64.02s] Generating autoload files
[151.6MiB/64.08s] Memory usage: 151.61MiB (peak: 200.79MiB), time: 64.08s
```

Running it again when it loads from cache :
```

[6.2MiB/0.01s] Loading composer repositories with package information
[6.6MiB/0.82s] Updating dependencies (including require-dev)
[200.0MiB/4.24s] Dependency resolution completed in 0.070 seconds
[200.1MiB/4.25s] Analyzed 1137 packages to resolve dependencies
[200.1MiB/4.25s] Analyzed 102049 rules to resolve dependencies
[200.1MiB/4.25s] Package operations: 5 installs, 0 updates, 0 removals
[200.1MiB/4.25s] Installs: symfony/polyfill-mbstring:v1.10.0, symfony/contracts:v1.0.2, symfony/console:v4.2.4, psr/log:1.1.0, symfony/debug:v4.2.4
[200.1MiB/4.25s]   - Installing symfony/polyfill-mbstring (v1.10.0): [200.2MiB/4.25s] Loading from cache
[200.2MiB/4.25s]     Extracting archive
[200.2MiB/4.29s]   - Installing symfony/contracts (v1.0.2): [200.2MiB/4.29s] Loading from cache
[200.2MiB/4.29s]     Extracting archive
[200.2MiB/4.33s]   - Installing symfony/console (v4.2.4): [200.2MiB/4.33s] Loading from cache
[200.2MiB/4.33s]     Extracting archive
[200.2MiB/4.46s]   - Installing psr/log (1.1.0): [200.2MiB/4.46s] Loading from cache
[200.2MiB/4.46s]     Extracting archive
[200.2MiB/4.48s]   - Installing symfony/debug (v4.2.4): [200.2MiB/4.48s] Loading from cache
[200.2MiB/4.48s]     Extracting archive
[151.6MiB/5.57s] symfony/contracts suggests installing psr/cache (When using the Cache contracts)
[151.6MiB/5.57s] symfony/contracts suggests installing psr/container (When using the Service contracts)
[151.6MiB/5.57s] symfony/contracts suggests installing symfony/cache-contracts-implementation
[151.6MiB/5.57s] symfony/contracts suggests installing symfony/service-contracts-implementation
[151.6MiB/5.57s] symfony/contracts suggests installing symfony/translation-contracts-implementation
[151.6MiB/5.57s] symfony/console suggests installing symfony/event-dispatcher
[151.6MiB/5.57s] symfony/console suggests installing symfony/lock
[151.6MiB/5.57s] symfony/console suggests installing symfony/process
[151.6MiB/5.58s] Writing lock file
[151.6MiB/5.58s] Generating autoload files
[151.6MiB/5.64s] Memory usage: 151.6MiB (peak: 200.3MiB), time: 5.64s

```

**Comment by alcohol** [comment]
Any idea why these lines look like this?

```
[200.1MiB/48.72s]   - Installing symfony/polyfill-mbstring (v1.10.0): [200.2MiB/50.26s] [200.2MiB/50.26s] [200.2MiB/50.27s] [200.2MiB/50.36s] [200.2MiB/50.36s] Downloading (100%)
```

**Comment by sakshamsaxena** [comment]
Existing behaviour looked even more shabby. I got around it a bit by ignoring profiling for backspaces and filler lines (I'm on Mac but still can't do without that "windows" fix), but still I'm missing something. I tried to tinker with `lastMessageErr`, but couldn't do much on this, yet.

**Comment by alcohol** [comment]
Yeah don't get me wrong, I appreciate your effort so far. But I think the scope of this issue is a little bit bigger than what you might have anticipated initially. Fixing the output in the verbose flow with profiling is not an easy task :sweat_smile:

**Comment by sakshamsaxena** [comment]
Haha, I understand that now :) Since I've already got my hands dirty with it, I won't mind fixing this till it's in the desirable state. If you could probably give a few cues on what the final stuff should look like (apart from that weird Downloading thingy), I can probably crack on right away. (_Totally_ new to Composer community, sorry. Picking up PHP after years.)

**Comment by alcohol** [comment]
Ideally, the profiling output only shows up as a prefix for each line once.

**Comment by sakshamsaxena** [comment]
@alcohol Well it looks much better now. Give it a try yourself. I've tested this in normal and verbose+profile modes.

**Comment by alcohol** [comment]
I'm at work right now, but I'll try and see if I got a moment later during the day. @Seldaek might also have an opinion about this though :-)

**Comment by Seldaek** [comment]
Thanks for the PR. That said, this seems overly complex IMO for what it's fixing. The issue it's fixing is kind of a non-issue to begin with, so it doesn't warrant adding complexity all over.. I'd say if we can reasonably skip the `[... MB/..]` output when $newline is false, then do that (should be a two line diff..), if that's not possible then I'd just close the issue as won't-fix.

**Comment by alcohol** [comment]
Does it? It doesn't look so complex to me.

**Comment by Seldaek** [comment]
It's adding flags to the functions, adding newlines which didn't exist before in the regular output. That's not worth fixing a slightly glitchy output in debug mode to me.

**Comment by sakshamsaxena** [comment]
> I'd say if we can reasonably skip the [... MB/..] output when $newline is false, then do that 

Well that's what I tried at the very beginning, but consider the case [here](https://github.com/composer/composer/pull/8043/files#diff-1fd0741f9ff8f463acdb944f4681c645R115). That's just there to actually _add_ a newline after the downloading messages are through with. So by this logic, it would anyway print the profiling info, which is something which we didn't want anyway at the end of the line. Thus I arrived at the current state of this PR.

Don't want to sound partial, but the benefit I see here is that there's backward compatibility in the new changes, as well as we have a proper function to tell us if we're in profiling mode or not. On the other hand, I personally haven't used Composer so much that I can advocate these changes as a "Nice to have" feature that might come handy one day. Neither would I mind if we leave this open till v2. So it's up to you guys :)

**Comment by Seldaek** [comment]
Yes.. perhaps in that case we should skip the profile too if the msg is empty.. That said most of this overwrite stuff + partial line output is gone from v2 already, so I think maybe it's best we simply close this and move on.. Sorry for wasting your time.

**Pull request closed without merging**
