### PR TITLE
Delete PORTING_INFO

### PR DESCRIPTION
**Pull request by jeffwidman**
I don't think this file is used anymore?

It was used during the initial port, but that was 12 years ago, so I suspect this is no longer relevant.

### CODE REVIEW

**Comment by jeffwidman** [comment]
To be clear: I am not 100% sure this change is safe, but I thought the best way to start that discussion was to open a PR. 😀

**Comment by Seldaek** [comment]
I'd tend to agree, but will defer to @naderman here :)

**Comment by naderman** [comment]
I actually still use this every once in a while when running into some obscure bug in the ported code. Sometimes helpful to look at the original C source for reference to see if this is a mistake when it was ported or if the bug was present in the original code too potentially. I don't see the harm in keeping this file, even if it's just for me? Guess could keep it somewhere else, just not sure where I won't eventually lose/forget it? :D

**Comment by Seldaek** [comment]
It's fine then, let's close I'd say.

**Comment by jeffwidman** [comment]
Makes sense @naderman thanks for clarifying.

**Pull request closed without merging**
