### PR TITLE
backport the legacy event api that allowed the substitue of rfs

### PR DESCRIPTION
**Pull request by elernonelma**
as found at https://getcomposer.org/apidoc/1.10.1/Composer/Plugin/PreFileDownloadEvent.html#method_setRemoteFilesystem

### CODE REVIEW

**Comment by Seldaek** [comment]
This is not going to be possible for v2 anymore, as the http downloader is doing async stuff we must have a unique instance so replacing it is not feasible.

We could perhaps add a setProcessedUrl so the URL can be modified and make sure that event dispatchers read the URL back before executing the request though?

That said.. it sounds like maybe building smth you can plug into HTTP_PROXY env var would have been easier than the mad hacks you had to pull to support flex and co there :)

**Comment by elernonelma** [comment]
Right, I agree - I'm closing this and will try to provide something that way.

Thank you @Seldaek for your time and have a nice day!

**Comment by Seldaek** [comment]
@elernonelma just in case, https://github.com/composer/composer/pull/8975 implements the setProcessedUrl I suggested above.

**Comment by elernonelma** [comment]
Ok thanks!

**Pull request closed without merging**
