### PR TITLE
Fix hg command to retrieve file content

### PR DESCRIPTION
**Pull request by Neurones67**
getFileContent generated command like hg cat -r hg cat -r  CHANGESET FILE that caused errors "Skipping missing sub" while fetching composer.json files in repositories containing subrepositories.

This fixes that error.

### CODE REVIEW

**Comment by Seldaek** [comment]
Looks good but can you please retarget this to the 1.4 branch?

**Comment by Neurones67** [comment]
Hum, it says that I want to merge 124 commits into the 1.4 branch... I'm not sure it's what you meant by "retarget to 1.4 branch"

Should I close this pull request, commit into the 1.4 branch and redo a pull request?

**Comment by Seldaek** [comment]
Nope you should `git rebase -i` the branch locally on top of 1.4  so you can just pick your single commit, but anyway if it's a hassle I guess I'll do it myself when merging just means I can't merge in the github UI so it'll take a bit longer for me to get to it..

**Comment by stof** [comment]
even easier than `git rebase -i`: `git rebase --onto 1.4 master` (which says "rebase commits which are not yet in master, but apply them on top of 1.4 rather than the latest master")

**Comment by Neurones67** [comment]
Not sure to understand... I cherry picked the commit on 1.4 branch and will do a new pull request.

**Pull request closed without merging**
