### PR TITLE
Feature/no api config

### PR DESCRIPTION
**Pull request by kathyoungaligent**
Allowing for the no-api flag to be used as a config value for all Github repos, not just on a repo by repo basis.

### CODE REVIEW

**Comment by alcohol** [comment]
Could you also update `doc/06-config.md` and the following file?

https://github.com/composer/composer/blob/0fca816d8f0a12775cfa567ffea793ff72eb1311/res/composer-schema.json#L97-L291

**Comment by kathyoungaligent** [comment]
@alcohol  - I will update the docs files shortly, thanks for pointing that out.

@Seldaek  - thank you for considering this feature and yes, you're right, it should be more self descriptive.  I'll rename the config.

**Comment by mrda** [comment]
Thanks for proposing this @kathyoungaligent - this will help a lot.

**Comment by Seldaek** [comment]
Thanks!

**Pull request merged**
