### PR TITLE
Extend travis matrix

### PR DESCRIPTION
**Pull request by alcohol**

### CODE REVIEW

**Comment by Seldaek** [comment]
What's the benefit of this? I doubt HHVM acts very differently according to this flag, and until we support php7 only it is probably just additional build overhead no?

**Comment by alcohol** [comment]
Mostly it was just to see if it would already reveal the error reported in the issue I linked. Unfortunately, it did not.

**Comment by Seldaek** [comment]
Ok so rather close for now I think, and have some pity for those travis workers :p

**Comment by stof** [comment]
@alcohol the issue is that HHVM on Precise is very old, and does not have the PHP 7 mode yet. You need to force this job to run on the Trusty environment (see the Symfony config file)

**Pull request closed without merging**
