### PR TITLE
Remove build platform from appveyor.yml

### PR DESCRIPTION
**Pull request by johnstevenson**
The platform config value is used for MSBuild, rather than providing an OS platform (which is always x64)

### CODE REVIEW

**Comment by johnstevenson** [comment]
The Appveyor cache is 1GB, so plenty of space for PHP, composer.phar and the Composer cache directory.

**Comment by Seldaek** [comment]
Not sure how to enable the cache? From what I read it seems to be enabled by default and you just need to configure which dirs are cached?

**Comment by johnstevenson** [comment]
I was only reading their docs (linked above). I think it is enabled for PRs, but it is hard to tell because I keep invalidating it by changing `appveyor.yml` with these PRS!

> Note: By default, saving cache is disabled in Pull Request builds. Use Save build cache in Pull Requests checkbox on the General tab of project settings if you need to save cache during PR builds. This setting is not exposed in YAML to prevent unauthorized cache modifications.

**Comment by Seldaek** [comment]
Yup I saw that checkbox, but I figured it's best to leave it off so that PRs don't update the cache which will reduce the chances it becomes full? Anyway I'll merge this then if it helps once master built?

**Comment by Seldaek** [comment]
It actually doesn't seem to work.. I built master twice and the second is still downloading everything. I'm not sure what PHP_CACHE_DIR is supposed to be but maybe I can add this to the cache in the appveyor settings?

**Comment by Seldaek** [comment]
Or am I supposed to define that env var myself? :)

**Comment by johnstevenson** [comment]
Not all all. PHP_CACHE_DIR is where php and composer.phar and shims end up, plus the Composer cache directory.

**Comment by Seldaek** [comment]
Oh it does say this at the end of the build:

```
Updating build cache...
Cache 'C:\tools\php' - Updated
Build success
```

Trying a new build..

**Comment by johnstevenson** [comment]
Seems to have kicked in now on https://ci.appveyor.com/project/Seldaek/composer/build/2443

**Comment by johnstevenson** [comment]
It took me a few builds too get it working on one of my repos.

**Comment by Seldaek** [comment]
Yup it worked that way, cool. It shaves off ~20seconds of build time. That just means we're stuck on PHP 7.2.0 forever though, not sure how bad that is.

**Comment by johnstevenson** [comment]
When chocolatey update to the next release, we just update `PHP_CHOCO_VERSION`. Not ideal but probably the safest way at the moment.

**Comment by Seldaek** [comment]
Ah I see the cache depends on the yaml file hash? I didn't realize that.

**Comment by johnstevenson** [comment]
There are other ways to do this. We could download a zipped PHP release, but it would still be a manual update process. What PHP versions would you like to test on?

**Comment by johnstevenson** [comment]
I think I misunderstood the disabling for PRs, because the cache is still used.

**Comment by Seldaek** [comment]
Oh no it's fine to be only testing on one version on windows IMO, I just worried that we'd never be able to update it without deleting the cache by hand, but if we can update the version number and it invalidates the cache it's fine.

As for the PR cache thing, it just means that PRs do not *update* the cache, but they still use it. That's good I think.

**Comment by johnstevenson** [comment]
Yup, that seems to be what happens and that's good.

For clarity, the env vars `PHP_CHOCO_VERSION`, `PHP_CACHE_DIR` and `PHP` are local to the script.

**Pull request merged**
