### PR TITLE
Issue #2384 allow 'prefer-stable' and 'minimum-stability' to be set 

### PR DESCRIPTION
**Pull request by sneako**
Now allows 'prefer-stable' and 'minimum-stability' to be set via composer config command

### CODE REVIEW

**Comment by Seldaek** [comment]
This does not work, as minimum-stability and prefer-stable are *not* part of the config key but top level keys. Reverting.

**Comment by Seldaek** [comment]
The proper fix for this would be #2415 which is waaay overdue to be reviewed and merged :/

**Comment by alcohol** [comment]
@seldaek got any notes/comments regarding that one, or would you just like to see it rebased and reviewed?

**Comment by Seldaek** [comment]
A rebase/review would be a good start, I don't remember what I think of it to be honest, I think it's probably fine to have as simply `composer property x y`, I am wondering if it shouldn't be merged in config though because I guess most people don't know what property is where (as evidenced by this PR and the fact it was merged :P).

**Comment by alcohol** [comment]
Yeah, well.... in my defense, it seemed like it should just work :p

**Comment by Seldaek** [comment]
Sure did, but those are the sneakiest PRs, the ones you think are 
obviously fine you should watch especially for :p

**Pull request merged**
