### PR TITLE
only urlencode $ if filename is not local

### LINKED ISSUE #4448: Composer stops working with Satis repository
Recently Composer stops working with custom repository generated with Satis. Repository is loaded locally from file system. Repository structure

archive/*
include/all$49d61ad9a8dd222cf20c3c355093f227da10b443.json
packages.json
{
    "packages": [],
    "includes": {
        "include/all$49d61ad9a8dd222cf20c3c355093f227da10b443.json": {
            "sha1": "49d61ad9a8dd222cf20c3c355093f227da10b443"
        }
    }
}

Error output after install/update operation:
  [Composer\Downloader\TransportException]                                                                                                                                                                                                                           
  The "file:///somepath/repository/include/all%2449d61ad9a8dd222cf20c3c355093f227da10b443.json" file could not be downloaded: failed to open stream: No such file or directory  

It looks that Composer is changing "$" into "%24" when trying to load json file. 

Let me know if you need more info.

### PR DESCRIPTION
**Pull request by alcohol**
closes #4448

### CODE REVIEW

**Comment by kaloyan-raev** [comment]
@alcohol How can I get a composer.phar with this change to test it?

**Comment by alcohol** [comment]
Simply clone my fork, checkout the branch, and run:
```
php composer.phar install
php bin/compile
```

Yes, ironically, you need composer to create a composer binary :p

**Comment by kaloyan-raev** [comment]
Thanks for the instructions. I will give it a try.

**Comment by alcohol** [comment]
Wait a moment though. Tests indicate I broke something. Not sure why though.

**Comment by alcohol** [comment]
Yeah my bad. Fixed.

**Comment by kaloyan-raev** [comment]
I can confirm that this PR fixes our issue. Thanks!

**Pull request merged**
