### PR TITLE
fix documentation which use a single pipe for a "logical OR"

### PR DESCRIPTION
**Pull request by Oliboy50**
As stated here: https://getcomposer.org/doc/articles/versions.md#range
A logical OR is done using a double pipe "||".

### CODE REVIEW

**Comment by alcohol** [comment]
Thanks

**Comment by stof** [comment]
Actually, both are allowed (the single pipe is older). But it is indeed better to be consistent regarding the documented one

**Comment by phansys** [comment]
@alcohol, is there any deprecation path at code for the old operator `|`?

**Comment by Seldaek** [comment]
@phansys not sure I understand your sentence, but we can not effectively deprecate operators as that would break all old packages/tags that use them. We can only document that they are deprecated to nudge people towards using newer operators.

**Comment by phansys** [comment]
Thank you for the response @Seldaek, you just understood my sentence as is. It comes from [this @fabpot's question](https://github.com/symfony/symfony/pull/18186#issuecomment-197299788).
The deprecations can not be handled here with `trigger_error()` alongside `E_USER_DEPRECATED` as in Symfony?

**Comment by Seldaek** [comment]
No we are not going to trigger warnings as that would not make any sense since you can not fix the warnings you would see when using old packages. `|` and `||` will work the same forever..

**Comment by phansys** [comment]
:+1: then, thank you for the clarification.

**Comment by phansys** [comment]
@Seldaek, do you thing it could have a related validator at `ValidatingArrayLoader` in order to show a warning when the old operator is used?

**Comment by curry684** [comment]
@phansys as there is no standard neither is old or deprecated.

**Comment by phansys** [comment]
Thanks @curry684, I see at [mojombo/semver](https://github.com/mojombo/semver) that there aren't any documentation about the operators since the spec tends to be agnostic to these implementation details.

**Pull request merged**
