### PR TITLE
Unlock symfony/console v6

### PR DESCRIPTION
**Pull request by WyriHaximus**
Not sure why all the other Symfony components were updated to include v6 and this wasn't, but this PR aims to correct that.

### CODE REVIEW

**Comment by Seldaek** [comment]
It was reverted as it caused issues as some type hints were added which we cannot yet add. https://github.com/composer/composer/pull/10343 resolves this.

**Comment by WyriHaximus** [comment]
Can probably work around that, but it's going to be very ugly 🤐 . #10343 will become 2.3 I suppose?

**Comment by Seldaek** [comment]
Yes, hoping to merge that in main next week latest

**Comment by Seldaek** [comment]
Yes, hoping to merge that in main next week latest

**Comment by Seldaek** [comment]
Yes, hoping to merge that in main next week latest

**Comment by WyriHaximus** [comment]
Hah awesome!

**Pull request closed without merging**
