### PR TITLE
[changelog] Add 2.2.18

### PR DESCRIPTION
**Pull request by captn3m0**
https://getcomposer.org/changelog/2.2.18 was returning a 404, this should fix it.

### CODE REVIEW

**Comment by usta** [comment]
@Seldaek ping ?

**Comment by captn3m0** [comment]
Could this be merged?

**Comment by Seldaek** [comment]
Is it really so urgent?

I am not super happy with the solution as it'd mean having to backport every changelog change from 2.2 branch into main.. I haven't yet had time to figure out a better solution tho, so it's in limbo.

**Comment by stof** [comment]
@Seldaek the issue is that the download page of the website has a changelog link for each version. But the website uses the file from the main branch to read the changelog, so the link fails for 2.2.18 as the changelog only exists in the 2.2 branch.

**Comment by stof** [comment]
The solution might be to merge 2.2 up into newer branches after releasing new 2.2 versions.

**Comment by captn3m0** [comment]
Not really urgent, just wanted to follow up.

**Comment by stof** [comment]
An option might be to make the changelog URL redirect to the GitHub release to see the changelog instead of parsing the changelog file of a given release.

**Comment by Seldaek** [comment]
Yup, that's a good idea @stof - tho I fetched it from API instead of redirecting, but maybe it should redirect if the API call failed due to rate limit just for safety ;)

**Pull request closed without merging**
