### PR TITLE
test cases for #5701

### PR DESCRIPTION
**Pull request by alcohol**

### CODE REVIEW

**Comment by Seldaek** [comment]
Huge diff just to add spaces around dots.. makes it harder to review for nothing really :/ Anyway looks fine to me except it fails to build on hhvm because obviously they are not 100% compatible.

**Comment by alcohol** [comment]
You can view diff without white-space changes ;-)

I'll look into the HHVM side of it in a moment.

**Comment by Seldaek** [comment]
I did check the diff without white-space yes, but I also could not **have to** :p

**Comment by alcohol** [comment]
Yeah yeah. I blame PhpStorm :p

**Pull request merged**
