### PR TITLE
Fixes #8065: Sort plugins deterministically before loading.

### LINKED ISSUE #8065: Race condition in how Composer plugins are activated leads to classmap errors
My `composer.json`:

```json
{
    "name": "example/demo",
    "description": "Composer installers error demo",
    "type": "project",
    "minimum-stability": "dev",
    "prefer-stable": true,
    "license": "GPL-2.0-only",
    "require": {
        "acquia/blt": "dev-issue-3148-demo",
        "composer/installers": "^1.2.0"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.8.4
PHP version: 7.2.15
PHP binary path: /usr/bin/php7.2
```

When I run this command:

```
composer install && composer --version
```

I get the following output:

```
Could not scan for classes inside "vendor/drupal/core/lib/Drupal.php" which does not appear to be a file nor a folder
```

And I expected this to happen:
No errors

Downstream issues with additional context:
- https://github.com/composer/installers/issues/427
- https://github.com/acquia/blt/issues/3148
- https://github.com/wikimedia/composer-merge-plugin/issues/139

What I think is going on here is a race condition in the way that Composer plugins are activated.

Both BLT and Composer Installers provide plugins. In the [minimum failing example](https://github.com/acquia/blt/tree/issue-3148-demo), BLT's plugin is completely empty. Composer Installers obviously is changing the directory where Drupal files are installed.

When you run the initial composer install, everything works fine because Composer activates the Installers plugin prior to BLT, due to the order of dependency resolution. But when you subsequently run `composer --version`, it's throwing errors because plugins are activated _alphabetically_. This means that Composer activates the BLT plugin before the Installers plugin. The BLT plugin itself doesn't do anything, but Composer mucks about with the autoloader / classmap as part of PluginManager::registerPackage(), and because this happens before the Installers plugin loads you get errors.

I don't know the exact best way to solve this, but I think it requires action on the part of Composer, because I can't think of any way to force one plugin to run before another (other than renaming it to be something like `zacquia/blt`, which actually does solve this problem, but obviously isn't viable.)

It seems to me that either there could be some sort of weight system or consideration of the dependency tree in activating plugins in order to make sure plugins like Installers run first, or Composer could simply fail more gracefully during the plugin activation process since it's highly likely that classes will be missing during out-of-order activation.

### PR DESCRIPTION
**Pull request by danepowell**
A second shot at fixing #8065, and follow-up to #8070

Should be pretty self-explanatory. `$packages` was previously sorted non-deterministically depending on the context in which Composer was run (sometimes alphabetically, sometimes according to dependency weight). This ensures that plugins are always loaded according to dependency weight.

### CODE REVIEW

**Comment by danepowell** [comment]
Not quite sure why automated tests are failing, but before I spend time debugging that I'd appreciate a sign-off on the general approach.

**Comment by danepowell** [comment]
You're right that I don't think this solves the problem for every edge case. If you have a composer.json that depends on a composer plugin that starts with letters "a" or "b" (let's call it bar) as well as composer installers, and bar doesn't declare a dependency on composer installers, this _might_ still occur. As a matter of practice, though, this seems unlikely, because with this patch composer installers is _always_ weighted such that it's installed first, even without an explicit dependency.

Even if it it doesn't fix every possible permutation of this bug, I think there's still a lot of value in this patch simply by loading plugins in a consistent and deterministic order.

**Comment by danepowell** [comment]
Ready for review again.

**Comment by danepowell** [comment]
@Seldaek would you mind taking another look? This has been a long and ugly problem for downstream projects with no other viable workaround, I'd love to get this (or any other solution) merged soon.

**Comment by danepowell** [comment]
I opened https://github.com/composer/composer/pull/8108 as a simpler alternative to this if you think that would be easier to review.

**Comment by Seldaek** [comment]
@danepowell Looks good to me now there is just one thing I am not sure is the array_reverse of the sort.. why is it? 

It sounds to me like both autoload and plugin registration should sort equally.. i.e. things with no dependencies should be loaded first, then things with dependencies should follow. The array_reverse being present in only one of them makes me think one of them is broken but maybe I missed something.

**Comment by danepowell** [comment]
Thanks for reviewing. Actually the autoloader uses array_reverse too, and this just matches that: https://github.com/composer/composer/blob/8288d2c456287d4ec2d746db1d285d6bd82d52ec/src/Composer/Autoload/AutoloadGenerator.php#L403

Basically, packages right now are sorted such that if package foo depends on bar, foo comes _before_ bar in the array. But for autoloading and plugin loading to work correctly, that needs to be reversed so dependencies come first.

Let me know if I'm missing something.

**Comment by danepowell** [comment]
@Seldaek please let me know if there's anything else you need to get this merged

**Comment by dgpalmer** [comment]
When can we expect an official release for this?

Thanks,
Donovan

**Comment by malikkotob** [comment]
Thanks for taking this on @danepowell and @Seldaek! This issue has been causing confusion and grief for awhile, and it's exciting to see it so close to the finish line. @Seldaek, any chance we can get this merged before next week?

**Comment by briantully** [comment]
Great to see that we're making progress on this frustrating and all-too-common issue. @Seldaek Are there any blockers preventing this from getting merged and released?

**Comment by Seldaek** [comment]
The blocker is as usual time, and wasting more of it with regular emails does not help. I know full well this needs merging, it's scheduled in the 1.8 milestone, it's not getting forgotten.

**Comment by malikkotob** [comment]
Glad to hear it. Thank you for your efforts, @Seldaek!

**Comment by Seldaek** [comment]
Ok, let's hope this doesn't have any unexpected adverse effects :) Thanks @danepowell for the PR and patience.

This will be available in snapshot builds shortly, I will try and finalize a 1.8 patch release early next week.

**Comment by danepowell** [comment]
Awesome, thanks so much for your commitment and time. I'm pretty confident this is safe, unless someone has been writing plugins that _rely_ on things being loaded alphabetically. In which case, I think they only have themselves to blame :smile:

**Comment by yyss8** [comment]
@danepowell I'm seeing the issue mentioned in acquia/blt#3148 again after updating composer to v1.9.0.
 Downgrading composer back to 1.8.6 seems to be a solution to remove those warnings at this time.

image

**Comment by danepowell** [comment]
Replied to the above comment in https://github.com/acquia/blt/pull/3701

**Pull request merged**
