### PR TITLE
Ignore xdebug.ini and process all files, #5995

### PR DESCRIPTION
**Pull request by johnstevenson**
@Seldaek I haven't implemented any further command-line ini handling here. It is a bit of a struggle trying to understand PHP's string quoting rules at the moment.

### CODE REVIEW

**Comment by Seldaek** [comment]
Do you mind rebasing this and retargetting on 1.3 branch? As it's a bugfix..

**Comment by johnstevenson** [comment]
I've retargetted to 1.3, there didn't seem to be anything to rebase onto?

**Comment by Seldaek** [comment]
Well yes, now you got all the master commits included :)

You need to `git rebase origin/1.3 -i` and then remove all commits but yours really to do this right.

**Comment by Seldaek** [comment]
Thanks

**Pull request merged**
