### PR TITLE
Docs: Fix sentence after reformulation

### PR DESCRIPTION
**Pull request by guilliamxavier**

### CODE REVIEW

**Comment by naderman** [comment]
@guilliamxavier can you rebase this onto master, as docs are only rendered from master now?

**Comment by naderman** [comment]
cherry-picked via https://github.com/composer/composer/commit/54a537e9b3ecca7c435c25d700e4b948c3342604

**Comment by guilliamxavier** [comment]
> docs are only rendered from master now

Well that seems unfortunate: I'm stuck on Composer 1 for now but the online docs are now for Composer 2, without indications of what is new/changed from 1.x nor a way to see the "old" version? 😕

> can you rebase this onto master

I can't rebase from the web UI, feel free to close this and redo it on master (I don't care authorship for that 😄)

**Comment by naderman** [comment]
No worries, already cherry picked it.

Why are you stuck on Composer 1? We have no way to distinguish versions on there currently.

**Comment by guilliamxavier** [comment]
> Why are you stuck on Composer 1?

I have to work on a number of more-or-less old projects, some of them still have warnings with Composer 1.10, and/or need `--ignore-platform-reqs` (or "fake" platform config), and/or depend on old plugins... It will certainly take a while before they are compatible with Composer 2 😞

> We have no way to distinguish versions on there currently.

I don't know your process, but seeing other projects, it may be feasible to generate the online doc for branch `1.10` in addition to `master`?

**Pull request closed without merging**
