### PR TITLE
Fixing local file VCS URLs with encoded characters 

### PR DESCRIPTION
**Pull request by markingman**
realpath() returns FALSE for paths with URL encoding like %20, and decoded path needs file:/// reapplied.

(this was originally pull request #5845)

### CODE REVIEW

**Comment by Seldaek** [comment]
I can see the use of the rawurldecode() but I don't quite see why you re-add the file:// prefix, as it is really not serving any purpose as far as I can see.

**Comment by markingman** [comment]
Thanks Seldaek...

Regarding the file://, sorry I think my testing was messed with the Composer cache at first.

Here's what's happening my end -- test is like:

../path-to-my-composer-source/bin/composer clear-cache 
rm -R vendor/my/project
../path-to-my-composer-source/bin/composer update

(I'm on OSX 10.9.5 and Subversion version 1.7.19)

When I do this I can toggle same error with or without the file:// prefix change.

Variable $url (with or without file:///) goes to Composer\Util\Svn->execute()

Then on line 105 (of Composer\Util\Svn) $svnCommand becomes like:
svn co --non-interactive  '/My/long/path/with spaces/trunk/@555' '/My/dev/sites/example/vendor/my/project'

That's sent for execution to Symfony\Component\Process\Process and ultimately on line 290 it's called as $commandline in PHP proc_open();

Composer command line shows red error like:

[RuntimeException]                                                                                                   
Package could not be downloaded,                                                                                     
svn: E125002: '/My/long/path/with spaces/trunk@555' does not appear to be a URL 

If I grab the $commandline variable value and try it manually it get the same error:

svn co --non-interactive  '/My/long/path/with spaces/trunk/@555' '/My/dev/sites/example/vendor/my/project'

...returns 'svn: E125002: '/My/long/path/with spaces/trunk@555' does not appear to be a URL'

svn co --non-interactive  'file:///My/long/path/with spaces/trunk/@555' '/My/dev/sites/example/vendor/my/project'

...processes as normal.

i.e. it appears a file:/// URL should go to the Subversion `svn co` command.

I presumed it had been removed to fix realpath(), and perhaps works in some cases so I set it to conditionally replace.

PS: apologies I just noted I used tabs as spacing when code is spaces – let me know if I should change :)

**Comment by Seldaek** [comment]
OK I see, maybe for svn it's needed then, if you can remove the spaces and rename `$is_file_protocol` to `$isFileProtocol` also then it should be mergeable for me.

**Comment by markingman** [comment]
Formatting updated - let me know if any issues...

**Comment by Seldaek** [comment]
Thanks

**Comment by markingman** [comment]
No probs :)

**Pull request merged**
