### PR TITLE
Fix ClassLoader to be serializable

### PR DESCRIPTION
**Pull request by Seldaek**
Refs https://github.com/sebastianbergmann/phpunit/issues/5117

### CODE REVIEW

**Comment by mariano-dagostino** [comment]
@Seldaek Thanks! I confirm this fixes the problem I reported here https://github.com/sebastianbergmann/phpunit/issues/5117

**Comment by stobrien89** [comment]
Will this be included in a new release today? Our Github CI is currently broken.

**Comment by Seldaek** [comment]
Yup, it's out now https://github.com/composer/composer/releases/tag/2.5.1

**Comment by stobrien89** [comment]
Thanks @Seldaek!

Can confirm the issue is resolved for us.

**Pull request merged**
