### PR TITLE
Add --vendor option to show/info command

### LINKED ISSUE #5212: composer info --vendor
The goal of `--vendor` option is to easily get vendor specific packages from `composer info` command.

Some examples:

```bash
$ composer info --vendor=sonata-project
sonata-project/admin-bundle              dev-nexy d2fcca4    Symfony SonataAdminBundle
sonata-project/block-bundle              2.3.9               Symfony SonataBlockBundle
sonata-project/cache                     1.0.7               Cache library
sonata-project/core-bundle               2.3.10              Symfony SonataCoreBundle
sonata-project/doctrine-extensions       1.0.2               Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle dev-nexy 483576b    Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.4.1               Lightweight Exporter library
sonata-project/intl-bundle               2.2.4               Symfony SonataIntlBundle
```

```bash
$ composer info --all --vendor=sonata-project
  sonata-project/admin-bundle
  sonata-project/admin-bundle-persistency-layer
  sonata-project/admin-search-bundle
  sonata-project/block-bundle
  sonata-project/cache
  sonata-project/cache-bundle
  sonata-project/classification-bundle
  sonata-project/comment-bundle
  sonata-project/composer-archive-creator
  sonata-project/core-bundle
  sonata-project/dashboard-bundle
  sonata-project/datagrid-bundle
  sonata-project/doctrine-extensions
  sonata-project/doctrine-mongodb-admin-bundle
  sonata-project/doctrine-orm-admin-bundle
  sonata-project/doctrine-phpcr-admin-bundle
  sonata-project/easy-extends-bundle
  sonata-project/ecommerce
  sonata-project/exporter
  sonata-project/formatter-bundle
  sonata-project/google-authenticator
  sonata-project/intl-bundle
  sonata-project/jquery-bundle
  sonata-project/markitup-bundle
  sonata-project/media-bundle
  sonata-project/news-bundle
  sonata-project/notification-bundle
  sonata-project/page-bundle
  sonata-project/propel-admin-bundle
  sonata-project/sandbox
  sonata-project/seo-bundle
  sonata-project/sonata-composer
  sonata-project/timeline-bundle
  sonata-project/translation-bundle
  sonata-project/user-bundle

installed:
  sonata-project/admin-bundle              dev-nexy d2fcca4    Symfony SonataAdminBundle
  sonata-project/block-bundle              2.3.9               Symfony SonataBlockBundle
  sonata-project/cache                     1.0.7               Cache library
  sonata-project/core-bundle               2.3.10              Symfony SonataCoreBundle
  sonata-project/doctrine-extensions       1.0.2               Doctrine2 behavioral extensions
  sonata-project/doctrine-orm-admin-bundle dev-nexy 483576b    Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
  sonata-project/easy-extends-bundle       2.1.10              Symfony SonataEasyExtendsBundle
  sonata-project/exporter                  1.4.1               Lightweight Exporter library
  sonata-project/intl-bundle               2.2.4               Symfony SonataIntlBundle
```

### PR DESCRIPTION
**Pull request by Soullivaneuh**
Closes #5212.

Examples:

```bash
$ ./bin/composer show --vendor=sebastian
sebastian/comparator        1.2.0 Provides the functionality to compare PHP values for equality
sebastian/diff              1.4.1 Diff implementation
sebastian/environment       1.3.5 Provides functionality to handle HHVM/PHP environments
sebastian/exporter          1.2.1 Provides the functionality to export PHP variables for visualization
sebastian/global-state      1.1.1 Snapshotting of global state
sebastian/recursion-context 1.0.2 Provides functionality to recursively process PHP variables
sebastian/version           1.0.6 Library that helps with managing the version number of Git-hosted PHP projects
```

```bash
$ ./bin/composer show --all --vendor=sebastian
available:
  sebastian/code-unit-reverse-lookup
  sebastian/comparator
  sebastian/de-legacy-fy
  sebastian/diff
  sebastian/environment
  sebastian/exporter
  sebastian/finder-facade
  sebastian/git
  sebastian/global-state
  sebastian/hhvm-wrapper
  sebastian/money
  sebastian/money-intl-formatter
  sebastian/object-enumerator
  sebastian/pdepend-process
  sebastian/peek-and-poke
  sebastian/phpcpd
  sebastian/phpdcd
  sebastian/phptok
  sebastian/recursion-context
  sebastian/resource-operations
  sebastian/version

installed:
  sebastian/comparator        1.2.0 Provides the functionality to compare PHP values for equality
  sebastian/diff              1.4.1 Diff implementation
  sebastian/environment       1.3.5 Provides functionality to handle HHVM/PHP environments
  sebastian/exporter          1.2.1 Provides the functionality to export PHP variables for visualization
  sebastian/global-state      1.1.1 Snapshotting of global state
  sebastian/recursion-context 1.0.2 Provides functionality to recursively process PHP variables
  sebastian/version           1.0.6 Library that helps with managing the version number of Git-hosted PHP projects

```

### CODE REVIEW

**Comment by OskarStark** [comment]
nice 👍

**Comment by greg0ire** [comment]
Can you please explain why you are doing this in your commit message, possibly like this :

```
Add --vendor option to show/info command

This can currently be done with grep, but implies having grep on the system,
and knowledge of advanced grep options to avoid false positives like with
unrelated-vendor-name-that-contains-the-vendor-name-i-am-looking-for.
```

**Comment by Soullivaneuh** [comment]
@greg0ire Commit updated. :wink:

**Comment by Seldaek** [comment]
Replaced by https://github.com/composer/composer/commit/21a9f21cc87a8173a8fa6c358b740b05fd9ad3c2

**Comment by Soullivaneuh** [comment]
Indeed, nice catch @Seldaek! :+1:

**Pull request closed without merging**
