### PR TITLE
Introduce COMPOSER_AUDIT_ABANDONED env var (for 2.6)

### LINKED ISSUE #11792: Introduce an environment variable for setting abandoned package reporting mode in composer audit
#11639 introduced an abandoned package reporting mode without providing an environment variable for customization. The default reporting mode is set to change to "fail" in [2.7.0](https://github.com/composer/composer/issues/11736). Rather than requiring code adjustments in every project to revert to the reporting mode via [configuration change in composer.json](https://getcomposer.org/doc/06-config.md#abandoned), it would be favorable to allow configuration through an environment variable in CI environments.

Another use case for implementing this environment variable is the ability to dynamically switch between reporting modes for specific CI jobs as needed (like use `fail` on PR review and `report`ing on nightly scanners that measures collected technical debt).

### PR DESCRIPTION
**Pull request by mxr576**
Closes #11792 for the 2.6 branch.

### CODE REVIEW

**Comment by mxr576** [comment]
The remaining PHPStan failures should be unrelated.

**Comment by Seldaek** [comment]
2.6 branch is closed now

**Comment by mxr576** [comment]
Well, I think it would be beneficial introducing the proposed feature in the latest version of 2.6.x, would help with moving projects to 2.7.0.

**Comment by Seldaek** [comment]
There will not be another 2.6. If you want to help migrating use `composer config audit.abandoned fail` or equivalent IMO, you've had a few months to do this..

**Comment by mxr576** [comment]
The related issue (#11792) contains more information about potential benefits of an environment variable based config override. Let's continue the discussion there.

**Pull request closed without merging**
