### PR TITLE
Fix for custom install directory can not remove when uninstall the package

### PR DESCRIPTION
**Pull request by breath-co2**
Fix for custom install directory can not remove when uninstall the package

### CODE REVIEW

**Comment by bilhackmac** [comment]
This PR (as #2637) need to be merged.

Without these changes all uninstalled packages that depend on `composer/installer` or any custom installer was not removed.

This bug was introduce by 661df121d9687fcebe76897e8efc4bc279613502 that make, I think, BC !

**Comment by Seldaek** [comment]
Finally fixed this as getPackageBasePath now uses getInstallPath so installer plugins only overriding that should work fine now.

**Comment by bilhackmac** [comment]
It's work like a charm. Thanks. :+1:

**Comment by redthor** [comment]
I think I have an problem due to this change...

https://github.com/composer/composer/commit/d98b134dc3ef7d5bd4b6e37c9621a811f8f1599d#commitcomment-14518456

**Pull request closed without merging**
