### PR TITLE
Allow duplicate dashes in package names (1.10)

### LINKED ISSUE #8749: Package naming in 2.0 and the asset ecosystem
Hi, I wanted to make you aware of an impact of the package naming restriction in 2.0, which is going to affect users of https://asset-packagist.org/ and [composer-asset-plugin](https://github.com/fxpio/composer-asset-plugin/issues/333). This is not about whether one should use these (I know your opinion on this @Seldaek :smiley:) but the fact that upgrading to Composer 2.0 becomes really hard (currently impossible) for people on this ecosystem.

### The issue

Composer 2.0 will restrict the use of `-` (dashes). When converting npm package names which include a vendor name (`vendor/package`) we can not keep the `/` because having multiple `/` in a package name has obvious issues (as discussed in #7975). Currently the `/` is converted to `--` (see [docs](https://github.com/fxpio/composer-asset-plugin/blob/fe3943dfddbb599d77002734a7077dc5d98cfe4f/Resources/doc/index.md#work-with-the-npm-scopes)). Double dashes however are not valid anymore in Composer 2.0.

### How to solve this issue?

There are two ways to solve this:

1. The easiest solution: allow multiple dashes in package names.
2. Come up with a different replacement when converting package names in `composer-asset-plugin`. 
  Given that we find a replacement that matches the naming restrictions and does not cause other problems (which is already quite hard), this also means a lot of upgrade work as people need to rename all their package requirements.
  We also we need a breaking change in the repository of asset-packagist as well as a new major version of composer-asset-plugin, which is incompatible with the current version, meaning a composer.json file will work either with version 1 or 2 but never with both. The fact that the plugin needs to be installed globally will make it very hard to work on two projects with different state. 

Allowing multiple dashes in package names is not a huge problem for composer and does not introduce any overhead as far as I see. Compared to the amount of work needed to make the composer-asset-plugin/asset-packagist ecosystem compatible with Composer 2.0.

Thank you!

Btw, docs should be adjusted:

https://github.com/composer/composer/blob/master/doc/04-schema.md#name

(I can help with that once this issue is solved)

### PR DESCRIPTION
**Pull request by cebe**
This is #8750 but for the 1.10 branch and including tests.

fixes #8749

### CODE REVIEW

**Comment by Seldaek** [comment]
Thanks

**Comment by schmunk42** [comment]
@Seldaek 
What's about the 1.x branch and packagist? 
Would this have to be ported to fix the warnings they are issuing?

**Comment by Seldaek** [comment]
This is the port to 1.x?!

**Comment by schmunk42** [comment]
Ah sorry, I missed that - so it will also make it to packagist.

I am getting errors for this repo https://packagist.org/packages/dmstr/yii2-vue-shufflejs-widget

**Comment by Seldaek** [comment]
@schmunk42 fixed now

**Pull request merged**
