### PR TITLE
persisting memory_limit when executing composer with xdebug enabled

### PR DESCRIPTION
**Pull request by oleg-andreyev**
My first PR to composer. Great achievementent 🥇 

This PR contains fix for #6004

### CODE REVIEW

**Comment by staabm** [comment]
Should a fix to this problem pass all the `-d` params along?

**Comment by johnstevenson** [comment]
How do we obtain all the -d params?

**Comment by oleg-andreyev** [comment]
it's possible to use `ini_get_all` and iterate all values but I don't think it's a great solution.
Another solution to get all -d params passed from commands is to parse command string

**Comment by staabm** [comment]
Not sure whether those are provided via $argv

**Comment by johnstevenson** [comment]
Or you could just raise the memory-limit in the ini file?

**Comment by oleg-andreyev** [comment]
@staabm $argv doesn't contain information which is passed before composer.
@johnstevenson just raising memory_limit isn't a solution

**Comment by johnstevenson** [comment]
How about using the `COMPOSER_ALLOW_XDEBUG` environment variable then, so the process doesn't restart. Or not having xdebug enabled in the first place? 

Because we can never know what was passed on the command line as ini options, we will never be able to satisfy everyone by adding extra params. That's my view, any way.

**Comment by oleg-andreyev** [comment]
Yes `COMPOSER_ALLOW_XDEBUG` will work. But I think this issue should be solved anyway, because before this improvement/workaround everything was working, so could be considered as bug.

**Comment by staabm** [comment]
Underlying issue was fixed with https://github.com/composer/composer/commit/2c39c43a9e9c0ebf8b0477adcfdafc26b94116d7

**Comment by Seldaek** [comment]
Yup sorry I missed this PR and did the fix in another way..

**Pull request closed without merging**
