### PR TITLE
add back the warning about missing unzip

### PR DESCRIPTION
**Pull request by mindplay-dk**
display an error-message on non-Windows OS if unzip is unavailable, per #7383

### CODE REVIEW

**Comment by JKetelaar** [comment]
Great change, I was wondering the same, but you already made the PR!

But what if there's a situation with the following conditions:
- Linux operating system
- `unzip` command not installed
- PHP `zip` extension not installed

Now you'll first see your warning:
```
As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Installing 'unzip' may remediate them.
```
But then the error from not having the PHP extension will also occur:
```
The zip extension and unzip command are both missing, skipping.
```

So in the end you'll have Composer first saying "_zip files are being unpacked using the PHP zip extension_" and then it will throw an error that it's not installed.

Wouldn't it be better to make the code like the following:
```
        if (null === self::$isWindows) {
            self::$isWindows = Platform::isWindows();
        }

        // Check if any ZIP module is installed
        if (!self::$hasZipArchive && !self::$hasSystemUnzip) {
            // php.ini path is added to the error message to help users find the correct file
            $iniMessage = IniHelper::getMessage();
            $error = "The zip extension and unzip command are both missing, skipping.\n" . $iniMessage;
            throw new \RuntimeException($error);

        // Warning that the OS unzip module isn't installed
        }elseif (!self::$isWindows && !self::$hasSystemUnzip) {
            $this->io->writeError("<warn>As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.</warn>");
            $this->io->writeError("<warn>This may cause invalid reports of corrupted archives. Installing 'unzip' may remediate them.</warn>");
        }
```

**Comment by mindplay-dk** [comment]
Instead of duplicating the conditions, I just swapped the tests around - if it throws because nothing is available, it won't reach the OS-specific test.

**Comment by Seldaek** [comment]
Thanks

**Comment by Seldaek** [comment]
Merged in 1.6 & master

**Pull request closed without merging**
