### PR TITLE
`composer status` improvement for unpushed changes

### LINKED ISSUE #2046: `status` should check for unpushed changes
We have had a couple of (thankfully minor) cases where we have run `php composer.phar up` and our components we had changed, committed, but not pushed to our Git server.

I know when you do `php composer.phar status`, it will tell you if you have uncommitted changes, but is there a way it can tell us if we are ahead of master branch (i.e. have not pushed changes / have not merged into origin) ?

This may help prevent cases where we change our component, commit but haven't yet pushed changes to our origin repo.

### PR DESCRIPTION
**Pull request by asgrim**
`composer status` now prevents overwriting Git package if changes have not been pushed. This change, if accepted, would resolve #2046.

I'm happy to make further modifications to this - please be nice, it's my first Composer PR :)

### CODE REVIEW

**Comment by asgrim** [comment]
Closing this as I don't really have time to update this and it's probably super out of date!

**Comment by greg0ire** [comment]
Oh that's too bad :disappointed:

**Comment by asgrim** [comment]
@greg0ire / anyone else: feel free to take my changes if you have time ;)

**Comment by greg0ire** [comment]
@asgrim : I'll try to rebase it soon, yeah.

**Comment by greg0ire** [comment]
There : I rebased and pushed [here](https://github.com/greg0ire/composer/tree/improve-status-for-unpushed-branches)

You'll notice I squashed all your "fix" commits into the first commit, so that the PR is easier to read, and we don't get these little mistakes nobody cares about in the history.

Will you replace your branch with mine and reopen this P.R. , or should I make a new P.R. myself ?

**Comment by greg0ire** [comment]
ping @asgrim

**Comment by asgrim** [comment]
Feel free to open PR yourself :) thank you

**Comment by greg0ire** [comment]
Done :)

**Comment by Seldaek** [comment]
Your zombie PR finally made it @asgrim :P #3633 Thanks

**Comment by asgrim** [comment]
oh nice :) thanks folks! :)

**Pull request closed without merging**
