### PR TITLE
Rename private packages page to better reflect content

### PR DESCRIPTION
**Pull request by PrinsFrank**
Split of from #9250 so this can be individually discussed.

### CODE REVIEW

**Comment by PrinsFrank** [comment]
@Seldaek, is there a way to redirect doc pages on the getcomposer.org site or do we always have to keep old pages to avoid breaking existing links?

**Comment by Seldaek** [comment]
We can definitely do a redirect somehow, but I'd avoid doing this too often :)

**Comment by PrinsFrank** [comment]
What would you recommend? The page is currently also referencing a private packagist server, and I was also planning to write some documentation about the new gitlab composer package registry. Should we split those up into three pages? Or can we link from the current page to the new page and hide the original one?

**Comment by Seldaek** [comment]
IMO feel free to rename the URL in the other PR, I'll make sure I add a fallback redirect before merging it. Closing this here then.

**Pull request closed without merging**
