### PR TITLE
simplified existing test, added a new test - related to #4795

### PR DESCRIPTION
**Pull request by alcohol**
Reproduces (and solves) an issue reported by @teohhanhui on the initial "fix" (#4817) for #4795.

### CODE REVIEW

**Comment by alcohol** [comment]
@naderman can you let me know if this solution is good enough?

**Comment by naderman** [comment]
Yeah this should be fine :-)

**Comment by naderman** [comment]
@alcohol did you just remove c because it made no difference or was the test actually failing with c still there?

**Comment by alcohol** [comment]
I removed `c` cause it made no difference for the test.

**Pull request merged**
