### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by paladox**
Replace deprecated psr-0 with psr-4

### CODE REVIEW

**Comment by hkdobrev** [comment]
@paladox You would also need to update the hash in the lock file. You could use `composer update --lock`.

**Comment by hkdobrev** [comment]
@paladox You should also fix the PSR-4 syntax in `composer.json`. I believe you should add `\\` to the end of namespaces when using PSR-4. Like so:

``` json
{
     "autoload": {
         "psr-4": { "Composer": "src/" }
     },
     "autoload-dev": {
         "psr-4": { "Composer\\Test": "tests/" }
     }
}
```

Here is the error in Travis CI, because of that:

```
PHP Fatal error:  Uncaught exception 'InvalidArgumentException' with message 'A non-empty PSR-4 prefix must end with a namespace separator.'
```

Here is the relevant documentation: https://getcomposer.org/doc/04-schema.md#psr-4

**Comment by alcohol** [comment]
Also PSR-4 does not work like that. You would have to point to the directory you are aliasing.

E.g.

```
// source
"Composer\\": "src/Composer"

// tests
"Composer\\Test\\": "tests/Composer/Test"
```

**Comment by alcohol** [comment]
For what it is worth, if @Seldaek is ok with switching to `psr-4`, I would personally prefer to see `tests/Composer/Test` just become `tests`, and changing **autoload-dev** to `"Composer\\": "tests"`. There is no need for the extra `Test` namespace, as all test classes can just "live" in the same namespace as the target class they are testing (there should not be any name conflicts).

**Pull request closed without merging**
