### PR TITLE
Add --prefer-stable and --prefer-lowest to "require" command

### LINKED ISSUE #5314: Add --prefer-stable and --prefer-lowest to "require" command
The `require` command should support the `--prefer-stable` and `--prefer-lowest` flags similar to the `update` command.

### PR DESCRIPTION
**Pull request by mbrodala**
Fixes #5314

Not sure about tests here.

### CODE REVIEW

**Comment by Seldaek** [comment]
Thanks, I merged it in master as 1.1 is bugfix only.

**Comment by mbrodala** [comment]
Ah yeah, sorry about that and thanks. :-)

Is there a reason why 1.1 is the main branch on Github instead of master?

**Comment by Seldaek** [comment]
Yes because most people don't pay attention and so for minor fixes that I
wanna merge via GitHub 1.1 is usually the right thing. I usually check new
features locally first.

**Comment by mbrodala** [comment]
Gotcha. :-)

**Pull request closed without merging**
