### PR TITLE
Support alternative scp-like syntax in http-secure check

### PR DESCRIPTION
**Pull request by ktomk**
Also support ssh:// URIs.

References:

- Report: #5173

- URL syntax: https://www.git-scm.com/docs/git-clone#_git_urls_a_id_urls_a

- Scheme syntax: http://tools.ietf.org/html/rfc3986#section-3.1

### CODE REVIEW

**Comment by ktomk** [comment]
@Seldaek: I think this PR is more interesting atm. ;)

Right now it's not possible to use `ssh:// ...` URLs or URLs like `git:Department/Repo.git` w/o disabling http-secure. The report is a bit hidden inside the (non-) issue I reported initially.

**Comment by curry684** [comment]
Isn't this an awful lot of extra code just for the edgy case that someone decides to name their SSH alias after one of the four known insecure protocols? Surely we can solve this with less than 154 lines of code?  :wink:

**Comment by ktomk** [comment]
Well it's perhaps because the original author wasn't able to create a one-liner PCRE expression that did the check firsthand ;)

If you think it's useful to inline at the current place in time, I'm happy to do so, it should reduce the non-test code to ca. 10-15 lines. I somewhat had the feeling that there might be other places (e.g. via. #3338) that in the end there is more benefit of a new type. Also a new type is easier to unit-test, but that's more showing my lazyness.

So just let me know if you would like to have this inlined (or as a PCRE one-liner even).

**Comment by Seldaek** [comment]
Fixed in d5158d943f60c54e0964fc8febed37171f3e345a

**Pull request closed without merging**
