### PR TITLE
Bugfix for #3874

### PR DESCRIPTION
**Pull request by DHager**
This attempts to fix issues #3874 and #3703.

In summary, these changes will:

1. When updating a git-repository within the vendor folder, always update the "origin" remote. (As opposed to only during the initial cloning, which git does automatically.)
2. Consider a git-repository in the vendor folder in need of updating whenever the source repo-URL changes. (Without this change, it will not notice if the revision-hash is the same.)

### CODE REVIEW

**Comment by stof** [comment]
Composer never use the ``origin`` remote for its operation. and there is no reason to force an UpdateOperation in case the source url changed if we already have the right commit (we may need to update the lock file and the installed.json metadata, but this is a totally different topic)

**Comment by DHager** [comment]
> there is no reason to force an UpdateOperation in case the source url changed if we already have the right commit

I agree that `UpdateOperation` may be too heavy-weight, but *something* needs to happen, because the commit-hash is not enough to uniquely/accurately identify the state of a vendor-folder, dev-mode repository.

The same hash means you have the same files in your repo, but it does not mean you have the same remotes for when you start editing those files.

> Composer never use the  `origin`  remote for its operation.

True, but *developers* do. It seems editing inside `vendor/` and pushing the changes to a remote is fairly common advice when it comes to complex projects and co-developed packages.

Composer might not care, but having an `origin` unexpectedly pointing to a wrong or obsolete location is potentially very bad, because developers' work will be getting based-on/changing the wrong repository as they pull and push.

**Comment by stof** [comment]
> The same hash means you have the same files in your repo, but it does not mean you have the same remotes for when you start editing those files.

Composer does not care about the remote at all. and it does not set it at all

> True, but developers do. It seems editing inside vendor/ and pushing the changes to a remote is fairly common advice when it comes to complex projects and co-developed packages.

but half of the time, you won't be allowed to push to the repo used by Composer when installing anyway, and would need to push to your own fork on Github instead.
In this case, resetting the remote url on each composer operation actually makes things harder for the developer

**Comment by DHager** [comment]
> Composer does not care about the remote at all. and it does not set it at all

I'm confused, then what's the source/significance of the remote labeled `composer`? (The other one being `origin`.)

> In this case, resetting the remote url on each composer operation actually makes things harder for the developer

It only resets the remotes once, when the repository-location (not the version) changes. If that happens, it usually implies a significant shift in development, such as a developer editing their local `composer.json` to point to their own version of the repo. 

When that happens, I'd argue it's safer to refresh the remotes than to leave them at historical values.

**Comment by Seldaek** [comment]
Closing this as I don't think it's an appropriate fix, let's discuss again in your issue.

**Pull request closed without merging**
