### PR TITLE
LocalChanges for ArchiveFiles

### PR DESCRIPTION
**Pull request by hectorprats**
Added LocalChanges detector for ArchiveFiles
Passed php-cs-fixer

### CODE REVIEW

**Comment by hectorprats** [comment]
can anyone to check it?

**Comment by staabm** [comment]
this PR would be easier to review if it would not contain CS changes

**Comment by hectorprats** [comment]
You are right, I will prepare a version without CS fixer, but I only did the good practices that you put in the contributor doc

**Comment by staabm** [comment]
my comment was just a tip on how you can increase likelyhood of your change beeing considered/reviewed. you did a great job, thx for contributing.

> but I only did the good practices that you put in the contributor doc.

in which file exactly did you find it? maybe we need to fix them

**Comment by hectorprats** [comment]
at the end of https://github.com/composer/composer/blob/master/.github/CONTRIBUTING.md

**Comment by hectorprats** [comment]
> my comment was just a tip on how you can increase likelyhood of your change beeing considered/reviewed.

Maybe I'm not reponse well, but only is cause of my poor english. Sorry, and thanks :-)

**Comment by staabm** [comment]
No worries. Lets see what the maintainers say...

**Comment by hectorprats** [comment]
I create new PR without CS fixes in https://github.com/composer/composer/pull/7191

**Pull request closed without merging**
