### PR TITLE
Cache: clear cache using removeDirectory

### PR DESCRIPTION
**Pull request by bmax**
fixes: #6362

cc/ @barbazul @Seldaek @stof 

Hello! This is my first PR. As directed in issue #6362 I introduced a separate function for clearing the cache and just used `removeDirectory` directly instead of the `gc` command. 
 
_*Note*_: If `cache-dir` is the root directory of `cache-files-dir`, `cache-repo-dir` and `cache-vcs-dir` than it tries to remove something that is not there -- possible to optimize more?

Let me know if any questions or concerns. thanks.

### CODE REVIEW

**Comment by alcohol** [comment]
> Note: If cache-dir is the root directory of cache-files-dir, cache-repo-dir and cache-vcs-dir than it tries to remove something that is not there -- possible to optimize more?

Not sure what you mean by "something that is not there"?

**Comment by bmax** [comment]
@alcohol It tries to remove a directory that doesn't exist because it's already been removed. For example cache-dir = /cache and cache-repo-dir = /cache/repo than when it iterates through those directories it removes /cache first and gets a does not exist for the /cache/repo directory.

**Comment by alcohol** [comment]
Ah, right. Well I think that is a non-issue. But I'd have to glance over the code again to make sure. Will do so later today.

**Comment by alcohol** [comment]
Maybe make `cache-dir` the last entry of the array which is iterated rather than the first? That way we first empty the specific cache directories, and after that the general (possibly root) cache directory.

**Comment by bmax** [comment]
> Maybe make cache-dir the last entry of the array which is iterated rather than the first in the ClearCacheCommand? That way we first empty the specific cache directories, and after that the general (possibly root) cache directory. This should solve any issues mentioned above.

Done @alcohol  cc\ @Seldaek

**Comment by Seldaek** [comment]
Thanks, looks good to me.

**Comment by barbazul** [comment]
Very nice! 👏

**Pull request merged**
