### PR TITLE
 Refactor the handling of conflict rules in the solver 

### PR DESCRIPTION
**Pull request by stof**
This is an implementation of my idea from #7452.

My profiling shows a very small increase in the timing when doing `composer update --dry-run`. I haven't yet run it on a project where the conflict rules might have loaded a bunch of metadata for non-required packages (where we could see an actual win, as the loading of metadata is 3x longer than the SAT solving in my cases).

While it does not improve performance much, it actually fixes https://github.com/composer/composer/issues/3754 without performance regression (the behavior change reported in this issue is the side-effect of an optimization implemented in 1.0-alpha8)

### CODE REVIEW

**Comment by staabm** [comment]
I tested this change against the same workload I used to generate the blackfire profile of https://github.com/composer/composer/issues/7452

the resulting profiles dont look "better" then before, no performance improvement.
(just to let you know)

**Comment by stof** [comment]
@staabm yeah, looks like this does not improve performance much. But it fixes the bug introduced by a previous optimization, without performance regression, which is why I still submitted it.

**Comment by stof** [comment]
And there is still one case for which the "conflict" rules are still created in the first pass. It is for the obsolete providers. But I'm not sure this case can be moved safely. And lots of conflict rules seems to be coming from this place.
I will need to discuss with @naderman to see whether this part can be optimized or no.

**Comment by alcohol** [comment]
Could you resolve the conflicts?

**Comment by stof** [comment]
@alcohol done

**Comment by alcohol** [comment]
Not sure if this should target the 1.7 branch or master btw. Is it an improvement purely? Or also a bugfix?

**Comment by naderman** [comment]
@stof thanks, will take some time to really review this for any unintended side effects.

**Comment by stof** [comment]
It fixes a bug introduced in February 2015 when optimizing composer. This implementation manages to keep the same level of performance, without sacrificing correctness (which was the case for the past few years).
The intended side effect is that some existing broken setup related to `replace` rule will now fail properly (like the one reported in the test).

I originally wanted to improve performance with that, but it does not improve it compared to the incorrect implementation (it does compared to the old non-optimized but correct implementation, of course, as it preserves the optimization). So for now, it is more a bugfix than a perf improvement.
Reworking the case of "obsolete providers" might unlock some improvements, but I don't understand that part enough to touch it (as it can both create require rules or conflict rules). I don't know what these "obsolete providers" actually are and the commit introducing this was not very explanatory.

**Comment by alcohol** [comment]
If it is indeed a bugfix, I think it would be better to target the 1.7 branch, cause that makes it easier for @Seldaek to merge it back into master as well.

**Comment by alcohol** [comment]
@stof can you rebase this on top of 1.7 ?

**Comment by stof** [comment]
@alcohol done

**Comment by naderman** [comment]
This looks good to me! Didn't test the performance, but I think functionality wise this makes a lot of sense. As a nice side effect this should also remove unnecessary repository lookups for conflicting packages which are not required anywhere if using a private composer repo. :-)

**Comment by Seldaek** [comment]
And as I mentioned to @naderman a while back.. now that this is in a release, it's breaking things. See https://github.com/composer/composer/issues/7764 - not much we can do except help people out of the mess I guess.

**Comment by barryvdh** [comment]
I ran into this issue also. After searching it does indeed seem that I have a conflict in my requirements and the `replace` entry in a library. The only thing which is a bit confusing is that it doesn't state WHY it cannot resolve those packages:

```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - don't install twbs/bootstrap v3.3.0|don't install magento/magento2-base 2.2.6
    - don't install twbs/bootstrap v3.3.1|don't install magento/magento2-base 2.2.6
    - don't install twbs/bootstrap v3.3.2|don't install magento/magento2-base 2.2.6
    - don't install twbs/bootstrap v3.3.4|don't install magento/magento2-base 2.2.6
    - don't install twbs/bootstrap v3.3.5|don't install magento/magento2-base 2.2.6
    - don't install twbs/bootstrap v3.3.6|don't install magento/magento2-base 2.2.6
    - don't install twbs/bootstrap v3.3.7|don't install magento/magento2-base 2.2.6
    - magento/product-community-edition 2.2.6 requires magento/magento2-base 2.2.6 -> satisfiable by magento/magento2-base[2.2.6].
    - Installation request for magento/product-community-edition 2.2.6 -> satisfiable by magento/product-community-edition[2.2.6].
    - Installation request for twbs/bootstrap ^3.3 -> satisfiable by twbs/bootstrap[v3.3.0, v3.3.1, v3.3.2, v3.3.4, v3.3.5, v3.3.6, v3.3.7].
```

Not sure how hard it would be, but stating that `magento/magento2-base 2.2.6` replaces ` twbs/bootstrap 3.1.0` would be helpful in this case.

**Comment by naderman** [comment]
Hey @barryvdh I think that's a great suggestion for improving that error message, can you just paste the same example and your suggestion in https://github.com/composer/composer/pull/7454 for 2.0?

**Comment by barryvdh** [comment]
You mean #7779 I guess? Posted it there. Thanks!

**Comment by naderman** [comment]
Oops, sorry not sure what I did there, yes thanks :-)

**Pull request merged**
