### PR TITLE
Update the autoloader PHPDoc: PSR-4 instead of PSR-0

### PR DESCRIPTION
**Pull request by dunglas**
Just a minor doc update.

### CODE REVIEW

**Comment by Seldaek** [comment]
Well technically it implements both, and classmap support as well :)

**Comment by TomasVotruba** [comment]
@Seldaek What would prefer to mention then. All 3?

**Comment by Seldaek** [comment]
Well if we want to be complete yes

**Comment by dunglas** [comment]
Changed ;-)

**Comment by Seldaek** [comment]
Thanks

**Comment by TomasVotruba** [comment]
Awesome!

**Pull request merged**
