### PR TITLE
Allow easier manipulation of RootAliasPackage

### PR DESCRIPTION
**Pull request by bd808**
While implementing https://github.com/wikimedia/composer-merge-plugin/commit/f706e5ce863ee7f3cf61f165e120d547c64b1a78 I discovered that there was no way to modify the "conflict", "provide" and "replace" collections of a RootAliasPackage after construction. Since the "require" and "require-dev" collections already have support for post-construction changes I decided to propose this patch in the hope that the lack of setters for other cached collections was just a matter of them not having been needed before.

I also boldly added a commit to the pull request that extends RootPackageInterface and RootAliasPackage to expose methods of RootPackage that [composer-merge-plugin](https://github.com/wikimedia/composer-merge-plugin) uses internally. The Package interfaces generally stick to getters and omit setters, but RootPackageInterface did already specify some setter methods. If this part of the change is unwanted here I won't be too disappointed if I'm asked ot remove it before merging, but I though it would be worth proposing as well.

### CODE REVIEW

**Comment by alcohol** [comment]
Is there a reason you ignored current coding styles? Too many violations to comment on individually, but please fix them :-)

**Comment by bd808** [comment]
> Is there a reason you ignored current coding styles? 
Fixed I think. Sorry about that.

I added tests for RootAliasPackage as well to show that the new (and existing) setters actually effect their associated getters.

**Comment by alcohol** [comment]
Thanks :)

**Comment by Seldaek** [comment]
thanks

**Pull request merged**
