### PR TITLE
Outdated/Show: no dev option

### PR DESCRIPTION
**Pull request by tlamy**
This is my try for #8945, adding '--no-dev' to the outdated and show commands.

It works in my manual tests, but I'm pretty sure there is a nicer way to implement this, as I don't fully understand composer's architecture

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Do the markdown docs need updating too?

**Comment by GrahamCampbell** [comment]
Yes: https://github.com/composer/composer/blob/master/doc/03-cli.md#show.

**Comment by tlamy** [comment]
Will tackle that tomorrow

**Comment by Ayesh** [comment]
`composer show --tree` is currently broken, if you @tlamy get any test failures, they are probably unrelated to this PR.

**Comment by Seldaek** [comment]
Thanks - see the commit I added for my "review" :)

**Pull request merged**
