### PR TITLE
Add note regarding repositories on different drives

### PR DESCRIPTION
**Pull request by rquadling**

### CODE REVIEW

**Comment by alcohol** [comment]
Could you double check if that is actually necessary? I think, by default, if you don't provide `true` or `false`, it will automatically pick the right option in this scenario. But since I have no access to a windows dev machine I can't really verify. Would be great if you can double check :-)

**Comment by rquadling** [comment]
Confirmed as issue.

``C:\eetest\composer.json``

```json
{
    "name": "rquadling/ee-test",
    "description": "ee test",
    "license": "proprietary",
    "repositories": [
        {
            "type": "path",
            "url": "D:/Sources/PHP/eloquent-enumeration"
        }
    ],
    "require":{
        "eloquent/enumeration": "dev-feature/tool"
    },
    "autoload-dev": {
        "psr-4": {
            "Eloquent\\Enumeration\\Tools\\": "vendor/eloquent/enumeration/utils"
        }
    }
}
```

With the updated eloquent\enumeration composer.json as

```
{
    "name": "eloquent/enumeration",
    "description": "An enumeration implementation for PHP.",
    "keywords": ["enum", "enumeration", "set", "class", "multiton", "type"],
    "homepage": "https://github.com/eloquent/enumeration",
    "license": "MIT",
    "authors": [
        {
            "name": "Erin Millard",
            "email": "ezzatron@gmail.com",
            "homepage": "http://ezzatron.com/"
        }
    ],
    "require": {
        "php": ">=5.3",
        "symfony/console": "^2.8.0"
    },
    "require-dev": {
        "icecave/archer": "dev-develop",
        "phpunit/phpunit": "^4",
        "sami/sami": "^3"
    },
    "autoload": {
        "psr-4": {
            "Eloquent\\Enumeration\\": "src"
        }
    },
    "bin": [
        "bin/eetool"
    ],
    "autoload-dev": {
        "psr-4": {
            "Eloquent\\Enumeration\\Tools\\": "utils"
        }
    }
}
```

Results of ``composer install``

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/polyfill-mbstring (v1.2.0)
    Loading from cache

  - Installing symfony/console (v2.8.7)
    Loading from cache

  - Installing eloquent/enumeration (dev-feature/tool)
    Junctioned from D:/Sources/PHP/eloquent-enumeration

symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/process ()
symfony/console suggests installing psr/log (For using the console logger)
Writing lock file
Generating autoload files
```

Attempt to run eetool ...

```
[ 09/06/2016 13:00:19 ] [ C:\eetest ] >vendor\bin\eetool
Could not open input file: C:\eetest\vendor\bin\/d:/Sources/PHP/eloquent-enumeration/bin/eetool
```

Drop vendor and composer.lock, add in `"symlink" :false` option, compose and run eetool.

```
[ 09/06/2016 13:00:39 ] [ C:\eetest ] >rd vendor /s /q

[ 09/06/2016 13:01:06 ] [ C:\eetest ] >del composer.lock

[ 09/06/2016 13:01:08 ] [ C:\eetest ] >composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/polyfill-mbstring (v1.2.0)
    Loading from cache

  - Installing symfony/console (v2.8.7)
    Loading from cache

  - Installing eloquent/enumeration (dev-feature/tool)
    Mirrored from D:/Sources/PHP/eloquent-enumeration

symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/process ()
symfony/console suggests installing psr/log (For using the console logger)
Writing lock file
Generating autoload files

[ 09/06/2016 13:01:47 ] [ C:\eetest ] >vendor\bin\eetool
Eloquent Enumeration Tools

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Available commands:
  docblock  Tidy DocBlocks
  help      Displays help for a command
  list      Lists commands

[ 09/06/2016 13:02:04 ] [ C:\eetest ] >
```

**Comment by rquadling** [comment]
A better fix would be if \Composer\Downloader\PathDownloader::download() could determine if, when on Windows, the drives for the target and url are different. May not be easy to do, especially if network drives, junctions, etc. are already in play.

**Comment by alcohol** [comment]
Maybe @curry684 has some ideas/tips?

**Comment by curry684** [comment]
I agree the note shouldn't have to be there, it should just fall back to copy by default, and fail hard if symlinks are forced and you try to specify a source on a different or network drive. What surprises me about this is that it apparently doesn't do the second part at all, I would expect the Windows calls used to expose failure correctly, and junctions between drives are most certainly not allowed - it's a masked hardlink, not a symlink.

Imho this PR can be closed as it shouldn't be necessary, and https://github.com/composer/composer/issues/5417 reopened as the true issue needs to be solved. I'll happily make some time for it, just been terribly busy with other projects past few weeks so haven't been doing much work on Composer.

**Comment by rquadling** [comment]
Thank you.

**Pull request closed without merging**
