### PR TITLE
Support gitlab private-token for easier access via Gitlab API

### PR DESCRIPTION
**Pull request by moolex**
Support gitlab private-token (or personal-access-token) for easier access via Gitlab API

Config example:

$HOME/.composer/auth.json

```json
{
	"gitlab-token": {
		"gitlab.com": "YOUR-TOKEN-HERE"
	}
}
```

Gitlab API authentication doc: http://doc.gitlab.com/ce/api/README.html

### CODE REVIEW

**Comment by stof** [comment]
Too bad that they decided to use a custom header instead of putting this in the Authorization header...

You should also update the ConfigCommand to support configuring this auth setting (there are multiple places to update in the class)

**Comment by stof** [comment]
and you also need to update the json schema

**Comment by moolex** [comment]
@stof I have update docs and related config definitions, please help me to review it again. TKS

**Comment by moolex** [comment]
@stof Is there any other problem in my commits ?

**Comment by alcohol** [comment]
Aside from one PSR violation (but that's not for you to worry about), everything looks good to me.

**Comment by alcohol** [comment]
Could do with a test though, imho.

**Comment by Seldaek** [comment]
Thanks

**Pull request merged**
