### PR TITLE
Substituted wget commands with curl to support more platforms includi…

### PR DESCRIPTION
**Pull request by b23prodtm**
…ng Darwin

### CODE REVIEW

**Comment by alcohol** [comment]
Might want to include `-L` and `-s`.

**Comment by staabm** [comment]
I also stumbled over systems in the past which had curl but not wget.

not sure this change is worthwhile.

**Comment by alcohol** [comment]
Yeah. It's often one or the other (although most systems I own/use have both). Maybe we should just provide easy copy & paste instructions for both.

**Comment by Seldaek** [comment]
Thanks but nope, Ubuntu server for example comes with wget but no curl AFAIR. We can't please everyone either way, so rather keep it the way it is.

**Pull request closed without merging**
