### PR TITLE
Curl transfer

### PR DESCRIPTION
**Pull request by peteraba**
Added curl fallback for data transfer. Moved hard coded stream context calls into separate transfer class. Created interface for transfer classes. Added tests.

### CODE REVIEW

**Comment by wzrdtales** [comment]
+1

curl **MUST** be preferred over file_get_contents and not the other way around. In this current implementation of this PR it is the other way around. When curl is used over file_get_contents instead this PR is going to solve (if not all proxy isses) the following issues:

#4332
#704
#4701 

Thus to add: @Seldaek This PR is not a `Nice To Have`, it is a must and is also a bug fix of the buggy file_get_contents method. 

I needed to fork composer and we will use only our fork now instead and replace the transfer with curl as default, otherwise composer won't be able to download at all and falls back always to the slower git clone method.

**Comment by staabm** [comment]
@wzrdtales feel free to discuss and provide a PR for a possible curl integration..

**Comment by wzrdtales** [comment]
@staabm I was about to do that, but as there is already a PR for a curl implementation (this one here) I walked in here first instead of directly a new one.

**Comment by peteraba** [comment]
@staabm @wzrdtales I'm no longer part of the organization under which this PR was created, although we did use it intensively within the organization a while back. Feel free to pick it up, it's mostly abandoned anyway.

**Comment by wzrdtales** [comment]
I just saw the work of https://github.com/hirak/prestissimo/issues/67, glad I do not have to spend any time on this. Going to use his work, as it is also faster with the prefetching. Would recommend anyone to do the same even those who do not have problems with the fopen methods.

**Comment by avindra** [comment]
Thanks to @hirak and everyone else working on the curl replacement / killing off fopen calls to urls. I am waiting to test to see if it fixes two of our problems:

1) This error thanks to a new security requirement at our company:

```
The "https://packagist.org/packages.json" file could not be downloaded: allow_url_fopen must be enabled in php.ini (https:// wrapper is disabled in the server configuration by allow_url_fopen=0
failed to open stream: no suitable wrapper could be found)
```

2) Issue #4332 

If there are builds I can use to test, please let me know, I'd be glad to.

**Comment by avindra** [comment]
As a follow up, after installing `hirak/prestissimo`, not only are downloads faster, but they work with the proxy setup going on at my job. (I.e., it fixes Issue #4332). However, since prestissimo seems to only override how packages are fetched, commands like `composer outdated` still don't work if `allow_url_fopen` is disabled

**Comment by jduartedj** [comment]
Just did a fresh install and my server allows **curl** but not **allow_url_fopen**.

I got the **allow_url_fopen** error and was not able to proceed.

How can I install and use composer?

**Comment by peteraba** [comment]
Not even working with PHP much anymore. PR should have been closed a long time ago.

**Pull request closed without merging**
