### PR TITLE
add readme to support fields in the schema docs

### PR DESCRIPTION
**Pull request by tflori**
This change is related to https://github.com/composer/packagist/pull/750

It should also be added to the schema.json but I don't know where it is. Is it stored in this repo or generated? And where is the definition of it?

### CODE REVIEW

**Comment by Seldaek** [comment]
Thanks, the schema is at https://github.com/composer/composer/blob/1.6/res/composer-schema.json#L461 if you'd like to send a PR (please target the 1.6 branch)

**Comment by tflori** [comment]
good morning,

That was wrong. sorry, my fault. I thought the support nodes where under root but they have a own node support. Readme is under root node. Should I commit both to 1.6 or fix the documentation in master and only the schema in 1.6?

**Comment by Seldaek** [comment]
Oh yeah I totally missed that :) Please send a PR against 1.6, then I merge that in master.

**Comment by Seldaek** [comment]
Ah but the docs are not present in 1.6 so you can't fix that in a 1.6 PR.. then please two PRs

**Pull request merged**
