### PR TITLE
Environment variable for `--no-audit`.

### LINKED ISSUE #10997: Feature: Environment variable for --no-audit
Multiple Composer packages audits are performed from multiple angles (schedule jobs & CI jobs). I'd rather not see this audit messages during my local development. In addition, it saves unnecessary processes. So setting an environment variable `export COMPOSER_NO_AUDIT=1` would be nice.

### PR DESCRIPTION
**Pull request by cafferata**
Fixes #10997

### CODE REVIEW

**Comment by Seldaek** [comment]
Great, with docs and all  :) Thanks

**Comment by Seldaek** [comment]
The only comment I'd have is next time it'd be great to test the RC so you can give such feedback *before* the release is out, so we can make sure all features are in the .0 release ;)

**Comment by cafferata** [comment]
>*Great, with docs and all :) Thanks*

Thank you too!

>*The only comment I'd have is next time it'd be great to test the RC so you can give such feedback before the release is out*

I share your opinion, and I've been running the RC release for a while because of the `bump` command. It was your implementation https://github.com/composer/composer/commit/e43cae6231f2f9dc02f3f23b86c660bc4103c3df and the [blog post](https://blog.packagist.com/composer-2-4/) that triggered me to apply the same elaboration for `--no-audit`. I didn't know about the [Composer environment variables](https://getcomposer.org/doc/03-cli.md#environment-variables) before.

**Comment by Seldaek** [comment]
Hehe no worries :)

**Comment by jrfnl** [comment]
Thanks @cafferata and @Seldaek !

FYI: I've opened an issue in the typical GitHub Actions `setup-php` action runner to suggest adding the ENV variable by default.

See: https://github.com/shivammathur/setup-php/issues/635

**Pull request merged**
