### PR TITLE
Fix Satis example when using `"require-all": true`

### PR DESCRIPTION
**Pull request by dhensby**
When using `"require-all": true"` in `satis.json` if you don't also declare `{ "packagist": false }` in your list of repositories then satis will go through all packagist packages as well.

Here's an example output if you don't include `{ "packagist": false }` in your `satis.json` file (note none of these packages were declared in `repositories`:

```
$ php bin/satis build satis.json web/
Scanning packages
The contao-legacy/bit3basics * requirement did not match any package
The contao-legacy/diffiehellman * requirement did not match any package
The contao-legacy/hidepagetitle * requirement did not match any package
The contao-legacy/phpseclib * requirement did not match any package
The contao-legacy/ziparchivecto * requirement did not match any package
The crunchy/crunchysignup * requirement did not match any package
The dayax/collections * requirement did not match any package
The ellicom/mailgun * requirement did not match any package
The ellicom/markdown * requirement did not match any package
The google/adwords * requirement did not match any package
The henrikbjorn/flint * requirement did not match any package
The henrikbjorn/raekke * requirement did not match any package
The joomla/client * requirement did not match any package
The logsafe/composer-parameter-handler * requirement did not match any package
The lohini/browser-extension * requirement did not match any package
The lohini/curl-extension * requirement did not match any package
The lohini/forms-replicator * requirement did not match any package
The mmoreramerino/form-filler-bundle * requirement did not match any package
The mouf/utils.log.logger * requirement did not match any package
The nateabele/li3_mustache * requirement did not match any package
The njh/easyrdf * requirement did not match any package
The ocramius/zfphpcrodm * requirement did not match any package
The pastum/pagi * requirement did not match any package
The pastum/pami * requirement did not match any package
The pear-pear.php.net/console_getopt * requirement did not match any package
The pear-pear.php.net/pear * requirement did not match any package
The pear-pear/auth * requirement did not match any package
The popshack/popshack-common-stdlib * requirement did not match any package
The reinink/plates * requirement did not match any package
The silverstripe/frontend * requirement did not match any package
The symfony/doctrine-abstract-bundle * requirement did not match any package
The symfony/doctrine-bundle * requirement did not match any package
The undf/quizbundle * requirement did not match any package
The undf/utrans * requirement did not match any package
....
```

### CODE REVIEW

**Comment by alcohol** [comment]
Seems your satis version is out of date. By default packagist is not included.

https://github.com/composer/satis/blob/72356ac2d694e6458443c9d512535b400bf0a445/src/Console/Command/BuildCommand.php#L161-L162

**Comment by dhensby** [comment]
I literally checked out master yesterday

**Comment by dhensby** [comment]
Looks like it checked out 1.0.0-alpha2 automatically, which is strange.

I'd make the following comments:

1. That fix is not tagged yet, so documenting for unreleased (dev-master) features is unhelpful for users
2. This change would help people on older versions AND have no effect to new versions so is low risk/highly helpful change for users
3. master is PHP-5.6+ compat only, so those running on < 5.6 will have use an older version.

Overall, this change in the example doesn't break anything for anyone but helps people that it would experience an error without it.

**Comment by alcohol** [comment]
But you are wrong. The alpha unsets it too.

https://github.com/composer/satis/blob/1.0.0-alpha2/src/Composer/Satis/Command/BuildCommand.php#L160-L161

The alpha however does not take into account the new configuration key that more recent versions of Composer make use of.

**Comment by dhensby** [comment]
All I can do is act on my experience. As I've outlined when submitting the issue if you don't include `{ "packagist": false }` in your `satis.json` then it will attempt to download a lot of unrelated packages.

Have you been unable to reproduce this behaviour?

**Comment by alcohol** [comment]
I don't run the old alpha tag because it is outdated. Everything works fine on master. So yes, I have been unable to reproduce this behaviour.

**Comment by dhensby** [comment]
I'm trying to help people who will come across this issue and have no idea how to resolve it; it's a shame this noninvasive patch to the docs has been met with such resistance.

The alpha I'm using is the latest tag, therefore it is not outdated. If a release is classed as outdated as soon as a branch gets a new commit then you're operating a unusual release policy.

Ultimately the docs will fail at their objective of helping people use the software if common sense amendments are rejected because an unstable dev branch (which is liable to change) doesn't require it.

**Comment by alcohol** [comment]
My guess is you cloned the tag, and then updated the dependencies, which resulted in a broken environment. Not something we can guard against, and not something worth documenting.

**Comment by dhensby** [comment]
I've run `composer create-project composer/satis --stability=dev --keep-vcs`. No lock file ships with the alpha and so it'd be down to the composer constraints you have being too liberal.

Here's the output from the command:

```sh
$ composer create-project composer/satis --stability=dev --keep-vcs
Installing composer/satis (1.0.0-alpha2)
  - Installing composer/satis (1.0.0-alpha2)
    Cloning 10439c168643bd74d76fc894d61ae3291c999aee

Created project in /var/www/satis
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/process (v3.2.2)
    Loading from cache

  - Installing symfony/finder (v3.2.2)
    Loading from cache

  - Installing symfony/filesystem (v3.2.2)
    Loading from cache

  - Installing psr/log (1.0.2)
    Loading from cache

  - Installing symfony/debug (v3.2.2)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.3.0)
    Loading from cache

  - Installing symfony/console (v3.2.2)
    Loading from cache

  - Installing seld/phar-utils (1.0.1)
    Loading from cache

  - Installing seld/jsonlint (1.5.0)
    Loading from cache

  - Installing seld/cli-prompt (1.0.2)
    Loading from cache

  - Installing justinrainbow/json-schema (4.1.0)
    Loading from cache

  - Installing composer/spdx-licenses (1.1.5)
    Loading from cache

  - Installing composer/semver (1.4.2)
    Loading from cache

  - Installing composer/ca-bundle (1.0.6)
    Loading from cache

  - Installing composer/composer (1.3.1)
    Loading from cache

  - Installing twig/twig (v1.31.0)
    Loading from cache

  - Installing symfony/yaml (v3.2.2)
    Loading from cache

  - Installing sebastian/version (1.0.6)
    Loading from cache

  - Installing sebastian/global-state (1.1.1)
    Loading from cache

  - Installing sebastian/recursion-context (1.0.2)
    Loading from cache

  - Installing sebastian/exporter (1.2.2)
    Loading from cache

  - Installing sebastian/environment (1.3.8)
    Loading from cache

  - Installing sebastian/diff (1.4.1)
    Loading from cache

  - Installing sebastian/comparator (1.2.2)
    Loading from cache

  - Installing doctrine/instantiator (1.0.5)
    Loading from cache

  - Installing phpunit/php-text-template (1.2.1)
    Loading from cache

  - Installing phpunit/phpunit-mock-objects (2.3.0)
    Loading from cache

  - Installing phpunit/php-timer (1.0.8)
    Loading from cache

  - Installing phpunit/php-file-iterator (1.4.2)
    Loading from cache

  - Installing phpunit/php-token-stream (1.4.9)
    Loading from cache

  - Installing phpunit/php-code-coverage (2.2.4)
    Loading from cache

  - Installing webmozart/assert (1.2.0)
    Loading from cache

  - Installing phpdocumentor/reflection-common (1.0)
    Loading from cache

  - Installing phpdocumentor/type-resolver (0.2.1)
    Loading from cache

  - Installing phpdocumentor/reflection-docblock (3.1.1)
    Loading from cache

  - Installing phpspec/prophecy (v1.6.2)
    Loading from cache

  - Installing phpunit/phpunit (4.8.34)
    Downloading: 100%

  - Installing mikey179/vfsstream (v1.6.4)
    Loading from cache

symfony/console suggests installing symfony/event-dispatcher ()
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating autoload files
```

It is something you can guard against by updating the docs as per this PR.

Anyway, thanks for your time and looking over the PR.

**Comment by alcohol** [comment]
Correct, the version of Composer that introduced a change that was not entirely Satis compatible is still within the constraint range. That is why the master branch now comes with a lock file.

Anyway, your passive aggressive attitude is not helping your case. I'm unsubscribing from this issue.

**Pull request closed without merging**
