### PR TITLE
The real working install for windows

### PR DESCRIPTION
**Pull request by netroby**

### CODE REVIEW

**Comment by alcohol** [comment]
@johnstevenson care to comment?

**Comment by johnstevenson** [comment]
Sorry, but this is not very real for me:

```
'"@ECHO OFF"' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by curry684** [comment]
The echo command puts both on the same line while they should be separated.

**Comment by johnstevenson** [comment]
What is actually wrong with the original?

**Comment by alcohol** [comment]
@netroby please provide constructive reasoning behind your PR. Otherwise I have no choice but to close this.

**Comment by netroby** [comment]
qq 20161209081928
 While execute the official install command. with windows 10 powershell. 
It will not create a composer.bat file

**Comment by netroby** [comment]
qq 20161209083245
I just update doc, separate instruct for powershell user.

**Comment by alcohol** [comment]
Guys I have no clue what any of this does or means. I'll leave it up to your better judgement :>

**Comment by johnstevenson** [comment]
The latest version does not work in all situations (if a folder name has spaces in it).

In my view, there is no need to provide a Powershell one-liner at all, because you can simply type `cmd` in a Powershell window to drop into the command prompt, run the command you want, then exit back out. This is very basic stuff.

```sh
PS C:\users\john> cmd

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\users\john>echo @php "%~dp0composer.phar" %* > composer.bat
C:\users\john>exit

PS C:\users\john>
```

**Comment by netroby** [comment]
powershell will replace cmd in win10


Get Outlook for Android






On Fri, Dec 9, 2016 at 7:25 PM +0800, "John Stevenson" <notifications@github.com> wrote:












The latest version does not work in all situations (if a folder name has spaces in it).


In my view, there is no need to provide a Powershell one-liner at all, because you can simply type cmd in a Powershell window to drop into the command prompt, run the command you want, then exit back out. This is very basic stuff.
PS C:\users\john> cmd

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\users\john>echo @php "%~dp0composer.phar" %* > composer.bat
C:\users\john>exit

PS C:\users\john>

**Comment by johnstevenson** [comment]
> powershell will replace cmd in win10

What a ridiculous thing to say.

@alcohol I'd take a guess from the title of this PR, that this more about flaming `cmd.exe` than providing anything useful.

**Comment by alcohol** [comment]
Alright. Thanks guys :-)

**Pull request closed without merging**
