### PR TITLE
Remove the pear repository type from the JSON schema

### PR DESCRIPTION
**Pull request by stof**
This was missed in the removal.

### CODE REVIEW

**Comment by stof** [comment]
hmm, actually, it looks like the config is still meant to accept it, but throwing an exception.

**Comment by Seldaek** [comment]
Yeah I thought it's better to provide a decent error, but I think we can also remove it from the schema..

**Comment by cebe** [comment]
When removing it from the schema, the error message is quite cryptic now:

```
$ ../bin/composer install

                                                                                                                                                                    
  [Composer\Json\JsonValidationException]                                                                                                                           
  "./composer.json" does not match the expected JSON schema:                                                                                                        
   - repositories[0] : Must contain no more than 1 properties                                                                                                       
   - repositories[0].type : String value found, but a boolean is required                                                                                           
   - repositories[0].type : Does not have a value in the enumeration [false]                                                                                        
   - repositories[0].url : String value found, but a boolean is required                                                                                            
   - repositories[0].url : Does not have a value in the enumeration [false]                                                                                         
   - repositories[0].package : The property package is required                                                                                                     
   - repositories[0].type : Does not have a value in the enumeration ["package"]                                                                                    
   - repositories[0].type : Does not have a value in the enumeration ["composer"]                                                                                   
   - repositories[0].type : Does not have a value in the enumeration ["vcs","github","git","gitlab","git-bitbucket","hg","hg-bitbucket","fossil","perforce","svn"]  
   - repositories[0].type : Does not have a value in the enumeration ["path"]                                                                                       
   - repositories[0].type : Does not have a value in the enumeration ["artifact"]                                                                                   
   - repositories[0] : Failed to match exactly one schema                                                                                                           
                                                                                                                                                                    

```

**Comment by Seldaek** [comment]
Ok in that case not worth the cleanup IMO. Let's keep it for now.

**Pull request merged**
