### PR TITLE
Docs: clarify carret contraint with ^0.0.x constraint

### PR DESCRIPTION
**Pull request by glaubinix**
Make it clearer that `^0.0.3` does not allow installing `0.0.4`

### CODE REVIEW

**Comment by xabbuh** [comment]
This does not look correct to me. Where did you find this information?

**Comment by glaubinix** [comment]
Might be easier with an actual example:
```
{
    "repositories": [
        {"type": "package", "package": [
            {"name": "acme/test", "version": "0.0.2"},
            {"name":  "acme/test", "version": "0.0.1.1"},
            {"name": "acme/test", "version": "0.0.1"}
        ]}
    ],
    "require": {
        "acme/test": "^0.0.1"
    }
}
```
And then run `composer update --no-install`
```
composer update --no-install 
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking acme/test (0.0.1.1)
Writing lock file
```

**Comment by stof** [comment]
@xabbuh the major version 0 makes the next segment a major version as well. By that definition, it is recursive in case that next segment is itself 0.
Anyway, pre-1.0 versions are full of surprise in semver.

**Comment by Seldaek** [comment]
Thanks

**Pull request merged**
