### PR TITLE
Add prompt to require command if a package name is not found but there are similar names that could be used

### LINKED ISSUE #11279: interactive composer require
running `composer require phpunit` reports

```
$ composer require phpunit

In PackageDiscoveryTrait.php line 361:
                                   
  Could not find package phpunit.  
                                   
  Did you mean one of these?       
      phpunit/phpunit              
      phpunit/php-timer            
      phpunit/php-invoker          
      brianium/paratest            
      symfony/phpunit-bridge       
                                   

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dep
endencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]

```

I think it would be useful to let the user choose between the found packages when in a interactive session, instead of erroring hard

----

```
$ composer --version
Composer version 2.5.1 2022-12-22 15:33:54

mstaab@NB-COMPLEX-45 MINGW64 /c/dvl/Workspace/php-clxproductnet-phpstan (utils)
$ php --version
PHP 8.1.2 (cli) (built: Jan 19 2022 10:13:52) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
```

### PR DESCRIPTION
**Pull request by Seldaek**
Fixes #11279

cc @staabm

### CODE REVIEW

**Comment by staabm** [comment]
tested locally. the happy path looks good.


but a few nits:

- leaving it empty runs into a `Value "" is invalid` error

```
$ php bin/comp
compile   composer

mstaab@NB-COMPLEX-45 MINGW64 /c/dvl/Workspace/composer (pr/11284)
$ php bin/composer require phpunit
Info from https://repo.packagist.org: #StandWithUkraine
Could not find package phpunit.
Pick one of these or leave empty to abort:
  [0] phpunit/phpunit
  [1] phpunit/php-timer
  [2] phpunit/php-invoker
  [3] brianium/paratest
  [4] yoast/phpunit-polyfills
 >

  Value "" is invalid


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-
dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-
prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]
```

-----

- choosing `0`, so `phpunit/phpunit` returns a error that it cannot be installed because requirements are not met. composer still asks me whether I want to use `--dev` - even though its clear that it cannot be installed?

```
$ php bin/composer require phpunit
Info from https://repo.packagist.org: #StandWithUkraine
Could not find package phpunit.
Pick one of these or leave empty to abort:
  [0] phpunit/phpunit
  [1] phpunit/php-timer
  [2] phpunit/php-invoker
  [3] brianium/paratest
  [4] yoast/phpunit-polyfills
 >



  Value "" is invalid


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-audit] [--audit-format AUDIT-FORMAT] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-
dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-
prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>...]


mstaab@NB-COMPLEX-45 MINGW64 /c/dvl/Workspace/composer (pr/11284)
$ php bin/composer require phpunit
Could not find package phpunit.
Pick one of these or leave empty to abort:
  [0] phpunit/phpunit
  [1] phpunit/php-timer
  [2] phpunit/php-invoker
  [3] brianium/paratest
  [4] yoast/phpunit-polyfills
 > 0
0
Cannot use phpunit/phpunit's latest version 9.5.28 as it requires php >=7.3 which is not satisfied by your platform.
The package you required is recommended to be placed in require-dev (because it is tagged as "testing") but you did not use --dev.

```

thank you!

**Comment by Seldaek** [comment]
Regarding the second one, the `Cannot use phpunit/phpunit's latest version 9.5.28 as it requires php >=7.3 which is not satisfied by your platform.` bit is just a warning that the latest version cannot be used, but it asks because it will end up using another lower version that works with your PHP.

The first one yes saw it too but I am not sure how to fix this for just `""`, you kinda want an error if you enter any other invalid value though.

**Comment by staabm** [comment]
> Regarding the second one, the `Cannot use phpunit/phpunit's latest version 9.5.28 as it requires php >=7.3 which is not satisfied by your platform.` bit is just a warning that the latest version cannot be used, but it asks because it will end up using another lower version that works with your PHP.

I see.

> The first one yes saw it too but I am not sure how to fix this for just `""`, you kinda want an error if you enter any other invalid value though.

yeah - maybe its good enough. a error message like "aborting.." or similar might be better.

telling the user that he may leave it blank to abort and afterwards sending a error that blank input is a error might be a bit misleading :)

**Comment by stof** [comment]
To abort a `composer require`, you can instead abort the command in the native way: with Ctrl+C

**Comment by staabm** [comment]
thanks

**Pull request merged**
