### PR TITLE
Check if package URLs are up to date after composer update is done

### LINKED ISSUE #3214: Install command not working with renamed GitHub Repo
I am having trouble downloading a project from GitHub that is listed on packagist (https://packagist.org/packages/slm/exception).
The repo was originally named SlmErrorExceptions.git but has subsequently been renamed to SlmException.git 

If I run composer update then the package is checked out using the old repo name (github is internally redirecting it to the new repo):

```
  - Updating slm/exception (dev-master 408e6d8 => v0.1.0)
Executing command (/home/tom/Projects/PHP/zf2-SwitchSystems/vendor/slm/exception): git status --porcelain --untracked-files=no
    Checking out 408e6d87496ce71248c9f7d46703f02fa798bee8
Executing command (/home/tom/Projects/PHP/zf2-SwitchSystems/vendor/slm/exception): git remote -v
Executing command (/home/tom/Projects/PHP/zf2-SwitchSystems/vendor/slm/exception): git remote set-url composer 'git@github.com:juriansluiman/SlmErrorExceptions.git' && git fetch composer && git fetch --tags composer
Executing command (/home/tom/Projects/PHP/zf2-SwitchSystems/vendor/slm/exception): git branch -r
Executing command (/home/tom/Projects/PHP/zf2-SwitchSystems/vendor/slm/exception): git checkout 'v0.1.0'
Executing command (/home/tom/Projects/PHP/zf2-SwitchSystems/vendor/slm/exception): git reset --hard '408e6d87496ce71248c9f7d46703f02fa798bee8'
Executing command (/home/tom/Projects/PHP/zf2-SwitchSystems/vendor/slm/exception): git log 408e6d87496ce71248c9f7d46703f02fa798bee8..408e6d87496ce71248c9f7d46703f02fa798bee8 --pretty=format:"%h - %an: %s"
Executing command (/home/tom/Projects/PHP/zf2-SwitchSystems/vendor/slm/exception): git log 408e6d87496ce71248c9f7d46703f02fa798bee8..408e6d87496ce71248c9f7d46703f02fa798bee8 --pretty=format:"%h - %an: %s"
```

This update created the following lock file entry:

```
{
            "name": "slm/exception",
            "version": "v0.1.0",
            "source": {
                "type": "git",
                "url": "git@github.com:juriansluiman/SlmErrorExceptions.git",
                "reference": "408e6d87496ce71248c9f7d46703f02fa798bee8"
            },
            "dist": {
                "type": "zip",
                "url": "https://api.github.com/repos/juriansluiman/SlmErrorExceptions/zipball/408e6d87496ce71248c9f7d46703f02fa798bee8",
                "reference": "408e6d87496ce71248c9f7d46703f02fa798bee8",
                "shasum": ""
            },
            "require": {
                "php": ">=5.3.3.",
                "zendframework/zend-mvc": "~2.1"
            },
            "type": "library",
            "autoload": {
                "psr-0": {
                    "SlmException": "src/"
                },
                "classmap": [
                    "./Module.php"
                ]
            },
            "notification-url": "https://packagist.org/downloads/",
            "license": [
                "BSD-3-Clause"
            ],
            "authors": [
                {
                    "name": "Jurian Sluiman",
                    "email": "jurian@soflomo.com",
                    "homepage": "http://juriansluiman.nl"
                }
            ],
            "description": "Extensive exception handling for Zend Framework 2",
            "homepage": "https://github.com/juriansluiman/SlmException",
            "keywords": [
                "error",
                "exception",
                "zf2"
            ],
            "time": "2013-10-03 09:50:48"
        },
```

As you can see it has saved the old repo address into the lock file which means when I run a composer install this happens (it isnt redirecting to the updated repo url like it does with an update):

```
     [exec]   - Installing slm/exception (v0.1.0)
     [exec]     Downloading: connection...Failed to download slm/exception from dist: The "https://api.github.com/repos/juriansluiman/SlmErrorExceptions/zipball/408e6d87496ce71248c9f7d46703f02fa798bee8" file could not be downloaded (HTTP/1.1 404 Not Found)
     [exec] Now trying to download from source
     [exec]   - Installing slm/exception (v0.1.0)
     [exec]     Cloning 408e6d87496ce71248c9f7d46703f02fa798bee8
      
     [exec]   [RuntimeException]                                                                                                                                    
     [exec]   Failed to execute git clone --no-checkout 'git@github.com:juriansluiman/SlmErrorExceptions.git' '/home/jenkins/workspace/zf2-Users/vendor/slm/exception' && cd '/home/jenkins/workspace/zf2-Users/vendor/slm/exception' && git remote add composer 'git@github.com:juriansluiman/SlmErrorExceptions.git' && git fetch composer  
 
```

The project author has updated the Canonical URL on packagist and I have cleared my local composer cache but it still tries to use the old github repo url.

(See this issue for additional info: https://github.com/juriansluiman/SlmException/issues/5)

### PR DESCRIPTION
**Pull request by Seldaek**
Fixes #3214

### CODE REVIEW

**Comment by stof** [comment]
Does this work if the reference in my lock file is different from the reference on Packagist or would it replace the dist URL by the one for the new ref ?

**Comment by Seldaek** [comment]
@stof it would probably replace it by the latest always yes.. For source url it's not an issue, for dist it's ok so long as we have a github dist because those are altered anyway to use the dist reference, but for non-github we probably shouldn't update.

**Comment by Seldaek** [comment]
Done in https://github.com/composer/composer/commit/d426246b8000c503ad047186eb7fb5315bcf9771

**Comment by mpdude** [comment]
This seems to update all package URLs, also in the case of partial (selective? whitelisted?) updates. Did you write it that way intentionally?

**Comment by Seldaek** [comment]
Yes the goal is to make sure we always have the most up to date URLs even if a package wasn't technically updated, because otherwise lock files are created with outdated URLs and you get problems when you install later.

**Comment by mpdude** [comment]
I found it surprising that you might get changes to the .lock file even if you perform a selective update only for another package. 

On the other hand, this way you can probably "update nothing" and get all URLs updated without changing the versions installed (or even requiring newer versions to be available).

**Pull request merged**
