### PR TITLE
VersionSelector package order bug

### PR DESCRIPTION
**Pull request by webflo**
``composer require`` does not select the latest stable release in some situations. It looks like, the order of the packages in the Pool is important for the selection.

### CODE REVIEW

**Comment by webflo** [comment]
Related issue on Drupal.org https://www.drupal.org/node/2801413

**Comment by alcohol** [comment]
Fix your PR please. Bug fixes should be based on 1.2

**Comment by alcohol** [comment]
I'll see if I can debug the cause behind this in the meanwhile.

**Comment by webflo** [comment]
Closed in favour of #5726

**Pull request closed without merging**
