### PR TITLE
Integrated at-ease library to more gracefully handle warning suppression

### PR DESCRIPTION
**Pull request by curry684**
See #4203

### CODE REVIEW

**Comment by curry684** [comment]
The conflict is likely in composer.lock, wasn't sure how to handle that after changing composer.json

**Comment by Seldaek** [comment]
AFAIK the date_ call is the only one that has the potential fatal error, so I'd rather not add another dependency just for this. The idea of [changing the error_reporting](https://github.com/composer/composer/issues/4203#issuecomment-122562635) sounds less intrusive than that and would fix the `@` issue. date_default_timezone_get() triggers a warning, so if we set the error_reporting to `E_ALL & ~E_STRICT & ~E_WARNING` and then reset it after the call I think we are fine. Would you like to do this?

**Comment by curry684** [comment]
The dependency is a single file actually, for which the contents are trivial to duplicate inside Composer. I don't entirely agree that this specific call is the only one that needs to be fixed - I also fixed many of the other ones exactly because they could have similar issues, for example when a file was removed in a race condition. I think as a rule the `@` operator should be removed entirely in the end, as it always has the same issue - it hides fatal errors when its purpose is only to accept warnings silently. It should be noted that it also has severe performance issues.

Another problem I just noted is that at-ease is released under GPL2.0+ for those few lines of code, which can cause issues with Composer's MIT.

I will just replicate the functionality natively inside Composer and fix it that way.

**Comment by Seldaek** [comment]
I mean that the other calls you changed have no way to cause a fatal error AFAIK, so I don't really see the benefit of changing them if the `@` works fine.

As for the performance issue, I don't think it is *severe* unless you use it in a tight loop, but also the overhead it has is due to changing the error_reporting + the fact that it tends to make you generate more notices than you should (and generating notices costs cpu time too). All this is still true with at-ease as it still changes the error_reporting and you still generate the notices. And you add some php code overhead instead of @ which is at least native code.

**Comment by curry684** [comment]
Hmm issue got closed when I pushed a branch delete hehe, that wasn't intentional.

> I mean that the other calls you changed have no way to cause a fatal error AFAIK, so I don't really see the benefit of changing them if the @ works fine.

That is not true, see for example in `Composer/Factory.php`:

        foreach (array($home, $cacheDir) as $dir) {
            if (!file_exists($dir . '/.htaccess')) {
                if (!is_dir($dir)) {
                    @mkdir($dir, 0777, true);
                }
                @file_put_contents($dir . '/.htaccess', 'Deny from all');
            }
        }

The first one on `mkdir` suppresses warnings to prevent a nasty race condition, but also hides a fatal error if the disk is full or you're out of inodes. In both cases it will just die silently. The second one I don't even see the reason for the suppression, as you'll most certainly want to see everything that can go wrong there, but the solution is never to silently just create an insecure environment (perfectly illustrated by this example).

**Comment by Seldaek** [comment]
I guess you're right about mkdir, the other one is arguably an unnecessary call anyway so if it fails we don't really care but yeah I see your point. As you said GPL is an issue though so if you can work it out with a Composer\Util\Something class instead that sounds good.

**Comment by curry684** [comment]
Was already working on that  :)

**Comment by Seldaek** [comment]
@curry684 as this got closed don't forget to re-submit a new PR when you're done :)

**Pull request closed without merging**
