### PR TITLE
Update tablehelper to table

### PR DESCRIPTION
**Pull request by alcohol**
Refs #3760, pulled out of #3715

### CODE REVIEW

**Comment by alcohol** [comment]
Meh, silly timeout. The build actually succeeded.

**Comment by stof** [comment]
@Seldaek dropping the support for symfony/console 2.3 will create issues for Packagist, because it still uses Symfony 2.3

**Comment by alcohol** [comment]
It should be backwards compatible though, right?

**Comment by stof** [comment]
@alcohol what do you mean ?

**Comment by alcohol** [comment]
That it will not conflict. Since packagist will install symfony/symfony with Console at 2.3, and then because of the dependency on composer it will also install symfony/console 2.5.

**Comment by alcohol** [comment]
See related #3754

**Comment by stof** [comment]
@alcohol except that this is a bug in the solver (previous versions of the solver used to forbid this. it may be related to optimizations which have been done). If symfony/symfony replaces the symfony/console, installing both together is invalid.

**Comment by alcohol** [comment]
@Seldaek well that answers that mystery ^

**Comment by Seldaek** [comment]
Well either way I need to update packagist :)

**Pull request merged**
