### PR TITLE
test: Coverage for ValidateCommand

### PR DESCRIPTION
**Pull request by giulio-Joshi**
Greetings, I made an attempt at testing the ValidateCommand, as per request #10796 

I could test and successfully execute phpunit in local, still I understand this PR could be premature: I'd love some feedback about it.
My doubts include:

* `chmod()` could be troublesome to test on Windows OS.
* I might have stuck a deeper issue with an unreadable file, that gave me this output:

```
1) Composer\Test\Command\ValidateCommandTest::testUnaccessibleFile
RuntimeException: The file "./composer.json" is not readable.

/home/joshi/Projects/php/composer/src/Composer/Json/JsonFile.php:197
/home/joshi/Projects/php/composer/src/Composer/Factory.php:315
/home/joshi/Projects/php/composer/src/Composer/Factory.php:623
/home/joshi/Projects/php/composer/src/Composer/Console/Application.php:504
/home/joshi/Projects/php/composer/src/Composer/Command/BaseCommand.php:127
/home/joshi/Projects/php/composer/src/Composer/Command/BaseCommand.php:231
/home/joshi/Projects/php/composer/vendor/symfony/console/Command/Command.php:264
/home/joshi/Projects/php/composer/vendor/symfony/console/Application.php:1028
/home/joshi/Projects/php/composer/vendor/symfony/console/Application.php:299
/home/joshi/Projects/php/composer/src/Composer/Console/Application.php:376
/home/joshi/Projects/php/composer/vendor/symfony/console/Application.php:171
/home/joshi/Projects/php/composer/src/Composer/Console/Application.php:140
/home/joshi/Projects/php/composer/vendor/symfony/console/Tester/ApplicationTester.php:66
/home/joshi/Projects/php/composer/tests/Composer/Test/Command/ValidateCommandTest.php:62
```
(this is the reason I got the test marked as `skipped`)

Thanks a lot for your time, I'll be available to discuss my edits. 🙇🏼

### CODE REVIEW

**Comment by Seldaek** [comment]
Thanks, I did a few cleanups and fixed the skipped test. It will require some fixes on the main branch before it works tho, I'll get on that in a bit.

**Comment by Seldaek** [comment]
Ok looking good now, thanks :)

**Comment by giulio-Joshi** [comment]
Thanks to you!
 I wasn't sure on adding an exception management in the main application in the test PR.

**Comment by Seldaek** [comment]
Just realized I messed up the skip and did it the wrong way.. Will merge once build is confirmed green.

**Pull request merged**
