### PR TITLE
Add messages to junction tests to see failures

### PR DESCRIPTION
**Pull request by johnstevenson**
I'm trying to track down the seemingly random failures on Appveyor. This first step is to see if there is a single failing condition (which I doubt).

### CODE REVIEW

**Comment by johnstevenson** [comment]
Ha ha, perfect!

Despite the appveyor test on my fork succeeding (https://ci.appveyor.com/project/johnstevenson/composer/builds/27966702), the one for this PR failed (https://ci.appveyor.com/project/Seldaek/composer/builds/27966930)

More confusingly, it failed trying to remove the junction stating that:
```
... is not a junction and thus cannot be removed as one
```
having successfully tested that it is a junction 3 times.

**Comment by Seldaek** [comment]
See also #8366

**Comment by johnstevenson** [comment]
Yeah, I saw that after I'd opened the PR. I don't know if moving the clearstatcache call before the not-a-directory-or-is-a-link check would make much difference.

Would this PR be better on master or 1.9?

**Comment by Seldaek** [comment]
1.9 for bugfixes. The other PR seems to help so far but it's hard to say as
it's somewhat random.

**Comment by curry684** [comment]
The test would fail if the underlying filesystem is not NTFS. Unheard in the real world but possible...

**Pull request merged**
