### PR TITLE
Allow numeric author name

### LINKED ISSUE #3948: Composer init Author name not valid.
Hi,

Whenever I run composer init and want to accept the default suggestion for Author, composer says it's an invalid author string. I know this is because my Github username has numbers in it, but I always manually modify the composer.json to add those anyway. Could the validation be modified so that it also accepts numbers in the Author string?

### PR DESCRIPTION
**Pull request by alcohol**
Could also change it to just accept whatever. Do we really want to enforce strict rules regarding valid author names?

Closes #3948

### CODE REVIEW

**Comment by TomasVotruba** [comment]
:+1:

**Comment by stof** [comment]
:+1:

**Comment by Seldaek** [comment]
I don't think there should be too much garbage in there, and if it's the first problem reported until now I would say reality agrees :)

**Comment by Seldaek** [comment]
But thanks for the fix, numbers seem like a legit use case.

**Pull request merged**
