### PR TITLE
Fix abandoned package list JSON serialization

### LINKED ISSUE #11646: composer audit --format=json is broken on abanadoned packages
Composer version 2..6.3

The feature was introduced in #11639

`composer audit` outputs

```
Found 12 abandoned packages:
+----------------------------------------------------+----------------------------------------------------------------------------------+
| Abandoned Package                                  | Suggested Replacement                                                            |
+----------------------------------------------------+----------------------------------------------------------------------------------+
| doctrine/reflection                                | roave/better-reflection                                                          |
| fgrosse/phpasn1                                    | none                                                                             |
| simplesamlphp/simplesamlphp-module-authfacebook    | none                                                                             |
| simplesamlphp/simplesamlphp-module-authwindowslive | none                                                                             |
| simplesamlphp/simplesamlphp-module-oauth           | none                                                                             |
| simplesamlphp/simplesamlphp-module-riak            | none                                                                             |
| simplesamlphp/twig-configurable-i18n               | none                                                                             |
| swiftmailer/swiftmailer                            | symfony/mailer                                                                   |
| symfony/debug                                      | symfony/error-handler                                                            |
| symfony/inflector                                  | EnglishInflector from the String component                                       |
| twig/extensions                                    | none                                                                             |
| webmozart/path-util                                | symfony/filesystem                                                               |
+----------------------------------------------------+----------------------------------------------------------------------------------+

```

`composer audit --format=json` outputs

```
    "abandoned": {
        "57": {
            "id": -1
        },
        "161": {
            "id": -1
        },
        "290": {
            "id": -1
        },
        "293": {
            "id": -1
        },
        "308": {
            "id": -1
        },
        "311": {
            "id": -1
        },
        "316": {
            "id": -1
        },
        "323": {
            "id": -1
        },
        "331": {
            "id": -1
        },
        "344": {
            "id": -1
        },
        "375": {
            "id": -1
        },
        "391": {
            "id": -1
        }
    }

```

### PR DESCRIPTION
**Pull request by mxr576**
Fixes #11646

### CODE REVIEW

**Comment by Seldaek** [comment]
Woops, I totally forgot to check json output huh.. Thanks

**Comment by mxr576** [comment]
> Woops, I totally forgot to check json output huh.. Thanks

How about adding automated tests as a follow task for the JSON output? :)

**Comment by Seldaek** [comment]
Feel free if you like :)

**Comment by Seldaek** [comment]
Alrighty did it myself then :D Thanks for the fix tho

**Comment by mxr576** [comment]
Thx 👍 , I was referring to an actual follow up task, not part of this PR.
i also was not sure if this waiting any input from my side or just queued for the next release

**Comment by Seldaek** [comment]
Yeah no worries it took 2min, if i merge without then it gets forgotten :)

**Pull request merged**
