### PR TITLE
Updated validator

### PR DESCRIPTION
**Pull request by WouterJ**
It's really strange to say that `zendframework zend-eventmanager` is a full package name, since Composer always uses `zendframework/zend-eventmanager`.

### CODE REVIEW

**Comment by WouterJ** [comment]
Sorry for the delay, @naderman and @Seldaek.

I've now updated the PR. It now accepts both `acme/example ~2.3` and `acme/example` (and also `php >=5.6` and even `php`).

There were no tests for the command, so I've tested it locally.

**Comment by barryvdh** [comment]
I also came across this. Was a bit confusing what the expected input was, especially because the proposed packages are just `vendor/name`. I would think that if you leave the version constraint out, it should find the best suitable package, just like the current `composer require` behaviour.

**Comment by WouterJ** [comment]
@barryvdh that's exactly what this PR does. Not sure why it isn't merged yet

**Comment by barryvdh** [comment]
Ok cool, :+1:  for this then ;)

**Comment by WouterJ** [comment]
Any reason to not merge this PR? Got hit by this once again this morning :)

**Comment by Seldaek** [comment]
Just time folks, just time, but thanks @WouterJ :)

**Pull request merged**
