### PR TITLE
In a Windows host/Linux guest filesystem, adding the '/' creates a SY…

### PR DESCRIPTION
**Pull request by bilogic**
See #10578. Thank you.

### CODE REVIEW

**Comment by bilogic** [comment]
I just thought of a better commit message

`creates SYMLINKD instead of SYMLINK on Windows host/Linux guest filesystems`

**Comment by bilogic** [comment]
I just thought of a better commit message

`creates SYMLINKD instead of SYMLINK on Windows host/Linux guest filesystems`

**Comment by Seldaek** [comment]
Is this specific to VirtualBox? Because I think I tried exactly this patch before asking you to send a PR and I could not see any difference when running it on my WSL2 linux filesystem.

**Comment by Seldaek** [comment]
Merging already, thanks

**Comment by bilogic** [comment]
To answer your question, I have not tested on WSL2, but my setup is VirtualBox and it makes a difference on Windows host and did not have an impact on the Linux guest, so I guess yes, it is specific to VirtualBox.

Thank you.

**Pull request merged**
