### PR TITLE
Support ignore-platform-reqs in `composer outdated`

### LINKED ISSUE #10291: Support --ignore-platform-reqs in `outdated` command
Allowing `composer outdated` to ignore platform reqs and return absolute latest versions of packages allows developers to calculate better the pressure of shifting to a higher version of the language, for example from 7.4 -> 8.

Currently `outdated` would not inform you of new versions that require platform changes like upgrading PHP to a new version. If you are not looking for the "data that is not there" you may get a false sense of being fully updated.

A couple other tickets also mention this:
- #9631 
- #9602
- #9688

### PR DESCRIPTION
**Pull request by rdohms**
This allows users to also find libraries that require major platform
changes to unlock updates.

Closes #10291.

### CODE REVIEW

**Comment by herndlm** [comment]
Hi, I think most of the other commands support also `ignore-platform-req` which can be specified multiple times. I'd expect that this command supports it too then. What do you think of adding it? See e.g. https://github.com/composer/composer/blob/main/src/Composer/Command/InstallCommand.php#L120

**Comment by rdohms** [comment]
@herndlm I pondered the same and if it was worth it.
Struggling to find the time to do the extra work, but if its a blocker I'll try to book some time.

**Comment by rdohms** [comment]
@herndlm had a boring meeting, managed to squeeze it in. Let me know how this looks.

**Comment by herndlm** [comment]
LGTM and seems to be working fine, thank you for the adaption :)

**Comment by Seldaek** [comment]
Thanks!

**Pull request merged**
