### PR TITLE
Fix: Update docs for validate command

### PR DESCRIPTION
**Pull request by localheinz**
This PR

* [x] updates the documentation for the validate command

Related to #4219, where I spotted that it's not up to date.

### CODE REVIEW

**Comment by naderman** [comment]
Since you're rewriting this already, mind actually explain what "complete" means? That explanation doesn't explain anything really.

**Comment by localheinz** [comment]
@naderman

Sure, will have a look tonight.

**Comment by localheinz** [comment]
@naderman 

Had a look and updated the docs - what do you think?

**Comment by naderman** [comment]
```
* **--no-check-all:** Do not emit a warning if requirements in `composer.json` use unbound version constraints.
* **--no-check-publish:** Do not emit an error if `composer.json` is unsuitable for publishing as a package on Packagist but is otherwise valid.
```

non-zero on error is implied I think.

**Comment by localheinz** [comment]
Thank you, @naderman!

**Pull request merged**
