### PR TITLE
Added backward compatibility for react/promise

### PR DESCRIPTION
**Pull request by glo71317**

### CODE REVIEW

**Comment by glo71317** [comment]
@naderman @Seldaek I would like to understand your point of view on this PR changes, As in current version 2.8.x we have remove `react/promise:^2.x` and now keeping only `react/promise:3.x` due to this several other packages are not backward compatible.
If we listing both supported versions as earlier `react/promise: ^2.8 || ^3` means that interoperability with other packages is maintained; Composer will pick the "best" version, which is typically the highest mutually-supported version. If we use ^3.0 only here, then we're forcing others to upgrade their packages in order for their coding standard to be used in conjunction with this product.

Can you share your point of view on this?

**Comment by Seldaek** [comment]
I'm not sure about this one. react/promise 3.x is not a very difficult migration, and requiring composer/composer is generally frowned upon, so why should we support 2.x still? What's the exact use case you're solving?

**Comment by glo71317** [comment]
> I'm not sure about this one. react/promise 3.x is not a very difficult migration, and requiring composer/composer is generally frowned upon, so why should we support 2.x still? What's the exact use case you're solving?

you may right react/promise 3.x is not a very difficult migration but we want to use composer:2.8 in adobe commerce but some other packages are not allowing to update the latest version of composer e.g. package `ezimuel/ringphp` requires react/promise:2.x and `opensearch-project/opensearch-php package depends on ezimuel/ringphp:1.2.2`.

As a result, these interdependent packages create a conflict, blocking the upgrade to the latest Composer version.

**Comment by Seldaek** [comment]
And have you reached out to ezimuel to see if he can bump his promise requirement to allow v3? Because that'd be a better fix imo (moving forward)

**Comment by glo71317** [comment]
> And have you reached out to ezimuel to see if he can bump his promise requirement to allow v3? Because that'd be a better fix imo (moving forward)

@Seldaek Yes, i tried to reach him but did not get any update https://github.com/ezimuel/ringphp/pull/12

**Comment by glo71317** [comment]
Hi @Seldaek As this PR https://github.com/ezimuel/ringphp/pull/12 is closed from maintainer side.

Are we planning to address the backward compatibility issue regarding react/promise:2.x? It may be beneficial to consider removing support for react/promise:2.x in a future major version of Composer. This would ensure that Composer 2.8.x (and later versions) can be used without introducing breaking changes for users who rely on the current version of react/promise.

Looking forward to feedback and suggestions on this approach.

**Comment by Seldaek** [comment]
Well if ringphp is deprecated and abandoned, I'd then go talk to opensearch-project/opensearch-php  about this because they should not use it anymore.

But yes I'll keep this open in the meantime and take a look whether I can reintroduce the promise v2 requirement or not, I don't quite recall why I removed it.

**Comment by Seldaek** [comment]
Ok it seems to run fine with 2.x, so I guess we can do this change.

**Comment by Seldaek** [comment]
I decided to drop react/promise 2.x again, as the situation upstream seems to have been resolved I hope you can now upgrade the needed dependencies.

**Pull request closed without merging**
