### PR TITLE
With-dependencies alias

### LINKED ISSUE #9213: Can we have an alias for --with-dependencies
My `composer.json`:

```json
Not Required
```

Output of `composer diagnose`:

```
Not Required
```

When I run this command:

```
composer update Repo/Package --with-dependencies
```

I get the following output:

```
I tend to mistype the word dependencies
```

And I expected this to happen:
I expect to have an alias like `-wd` which is much smaller and there are less chances of mistake.

I know its not just me, whose first language is not English. Many other devs including my team members / friends are facing this issue.

### PR DESCRIPTION
**Pull request by flavioheleno**
This PR adds aliases for `--with-dependencies` (`-w`) and `--with-all-dependencies` (`-W`).

Closes #9213.

### CODE REVIEW

**Comment by stof** [comment]
Maybe `-d` and `-D` would be better (referring to the word `dependencies` rather than `with`) if they are available?

**Comment by stof** [comment]
OK, answering my own comment: `-d` is already the shortcut for the global `--working-dir` option of Composer...

**Comment by flavioheleno** [comment]
@stof I've followed @Seldaek's suggestion from #9213 :-)

**Comment by stof** [comment]
yeah, he probably remembered from the start that `-d` was already used :smile:

**Comment by Seldaek** [comment]
Thanks

**Pull request merged**
