### PR TITLE
Added clear cache for windows, fix tests

### PR DESCRIPTION
**Pull request by proggga**

### CODE REVIEW

**Comment by curry684** [comment]
If memory serves me right (wrote this 3 years ago...) this change is irrelevant as `is_dir` and `is_link` will not 'lie' as their state is tightly coupled with PHP's native filesystem functions which properly update the caches. The `clearstatcache` is so important for the `lstat` because it has to detect the junctions which are created by invoking the external CLI commands, thus bypassing the cache and potentially making it stale.

So, I think the change is irrelevant. Is this fixing an actual issue you are having?

/cc @Seldaek

**Comment by proggga** [comment]
Im trying to fix bug in appveiour, looks like maybe it can help

**Comment by proggga** [comment]
From php doc: is_dir . and is_link can be cached
https://www.php.net/manual/en/function.clearstatcache.php

> Affected functions include stat(), lstat(), file_exists(), is_writable(), is_readable(), is_executable(), is_file(), is_dir(), is_link(), filectime(), fileatime(), filemtime(), fileinode(), filegroup(), fileowner(), filesize(), filetype(), and fileperms().

**Comment by curry684** [comment]
Yes but they don't check the bits that can 'lie', the mask we apply on the `lstat` result can.

**Comment by alcohol** [comment]
Considering there is no drawback to moving it before the methods of which it could possibly affect the outcome, I don't see why this change is irrelevant? Worst case scenario, nothing gained, nothing lost. The bug solving potential is enough IMHO.

**Comment by alcohol** [comment]
@proggga bugfixes should target the latest release branch though (1.9 in this case). Can you adjust and rebase?

**Comment by proggga** [comment]
Adjusted and rebased

**Comment by curry684** [comment]
I'm fine with the change, I was just explaining that the bug solving potential should be close to zero if PHP is working as documented. That in itself is always a gamble so indeed fine to change.

**Comment by proggga** [comment]
Sorry for asking, but will you merge it or no?

**Pull request merged**
