### PR TITLE
Composer should not send authorization header when following redirect

### PR DESCRIPTION
**Pull request by maartenba**
Fixes the issue described in #6716

### CODE REVIEW

**Comment by dulfe** [comment]
+1
Completely fixed the issue I had with authorization headers... thank you!

**Comment by Seldaek** [comment]
Merged as https://github.com/composer/composer/commit/128e424c90b9aad4ed7a86dd43b182aaddfd60d1 and then I realized we actually can do it much simpler by using the correct host to check for credentials at every request instead of re-using the originUrl .. https://github.com/composer/composer/commit/743153e862b7b82bd71f09be9775f460ca8d6ac0

Hopefully this won't break anything though, it's kinda sensitive code.

**Comment by maartenba** [comment]
@Seldaek do you happen to have the .phar somewhere?

**Comment by alcohol** [comment]
`composer self-update --snapshot`

**Comment by dulfe** [comment]
@Seldaek, it worked great. (I used @alcohol command to download the snapshot)

**Comment by maartenba** [comment]
Verified it as well, works just fine. Thanks @Seldaek !

**Comment by Seldaek** [comment]
Alright great thanks

**Pull request closed without merging**
