### PR TITLE
Display branches and tags if verbose is specified

### LINKED ISSUE #8113: Move reading of custom repository composer.json messages behind OutputInterface::VERBOSITY_VERBOSE
As pointed out in #8112, while iterating tags and branches of custom repositories, Composer prints out a message for each encountered. These individual messages are not behind any level of verbosity currently and are thus always printed. Because this can become quite lengthy in logs that do not support rewriting output, it would perhaps make sense to move them behind at least the first level of verbosity (`OutputInterface::VERBOSITY_VERBOSE`).

### PR DESCRIPTION
**Pull request by samlitowitz**
Resolves #8113

### CODE REVIEW

**Comment by alcohol** [comment]
I think the `getCachedPackageVersion` method should also be adjusted?

**Comment by alcohol** [comment]
Aside from that, looks good to me so far. :+1:

**Comment by samlitowitz** [comment]
@alcohol , `getCachedPackageVersion` has been updated.

**Comment by alcohol** [comment]
Nice work, thanks :-)
I'm not entirely sure if this should target master or 1.8. I think master is fine since it is not a bugfix.

**Comment by Riszin** [comment]
#`68ac50ed-1576-4f56-a8e6-eb0542eb6320`

**Pull request merged**
