### PR TITLE
Arbitrary deep on config extra properties (CLI)

### PR DESCRIPTION
**Pull request by alphp**
https://github.com/composer/composer/issues/7981

### CODE REVIEW

**Comment by alphp** [comment]
About checks:
AppVeyor: Composer\Test\Util\FilesystemTest::testJunctions => This PR is not the cause of the error
Travis: Fails on PHP-5.3. Why are they still testing EOL versions? http://php.net/supported-versions.php

**Comment by Seldaek** [comment]
This will decode/encode the entire file though, which might lose formatting and create more diffs than needed. I am not sure if we rather have that than not have the functionality at all.

**Comment by XedinUnknown** [comment]
☝️ Precisely the concern I have in mind when editing JSON.

**Comment by alphp** [comment]
I think the best way to maintain the composer.json format is to just rewrite it.

I have seen several times in which the program parse the configuration files and format them according to their style once validated.

For me it is a simple way to maintain a consistent format.

Whenever I have used json in my projects I leave PHP the parsing task json => array / array => json. If I need the json to be friendly with people, I use JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES and that's it.

**Comment by XedinUnknown** [comment]
IMO `composer.json`, while machine readable, is very often read and modified by humans, so it's important to keep unmodified parts. This is especially important since `composer.json` is most of the times committed to VCS. For example, if I want lists to be one item per line, re-encoding JSON may introduce maintainability problems. Although, this is probably not a concern if the editing happens in a CI/CD environment.

**Comment by alphp** [comment]
I would have liked to be able to use recursion with the addSubNode function, but I did not see it possible.

I did not want to make major modifications to addSubNode, and what I chose is to change the operation mode of addProperty when adding an "extra" property.

In this sense I would have liked to be able to limit the modifications of the json to the minimum possible, but I did not see the way to do it.

**Comment by Seldaek** [comment]
This is solved in composer2 using the new --json arg to config https://getcomposer.org/doc/03-cli.md#modifying-extra-values

**Pull request closed without merging**
