### PR TITLE
Get realpath for `ZipArchive`

### PR DESCRIPTION
**Pull request by jasonmccreary**
I came across a few open issues, notably #10099, and the fix commented by @Seldaek resolved the issue. However, it has yet to be PR'd since Satis is now replaced by [Private Packagist](https://packagist.com/).

Nonetheless, here is the PR to resolve the issue where the archive paths are incorrect due to `ZipArchive::archive` not using the `realpath()`. Notably on MacOS where `sys_get_temp_dir()` returns a symlinked path. This change is inline with `PharArchive::archive` as it uses `realpath()` [already](https://github.com/composer/composer/blob/main/src/Composer/Package/Archiver/PharArchiver.php#L41).

There are other instances in the codebase which use `sys_get_temp_dir()`. However, since they are only used for storage, and not pathing information, I don't believe they require changes.

### CODE REVIEW

**Comment by jasonmccreary** [comment]
Not sure the appropriate fix here for PHPStan as checking for `false` requires some kind of action, e.g. throwing an exception or using `$sources` as is.

**Comment by stof** [comment]
I suggest using `realpath($sources) ?: $sources`. If the resolution of the realpath fails, we should keep using the original one.

**Comment by jasonmccreary** [comment]
Haha, looks like PHPStan doesn't like short ternary.

**Comment by Seldaek** [comment]
Thanks

**Pull request merged**
