### PR TITLE
for github increasing the unauthenticated rate limit

### PR DESCRIPTION
**Pull request by jhyeon1010**
Some code for used github api
Section is [this](https://developer.github.com/v3/#increasing-the-unauthenticated-rate-limit-for-oauth-applications)

* Sample
```php
$io = new NullIO();
$config = Factory::createConfig();
$io->loadConfiguration($config);

$repository = new VcsRepository(['url' => $repoUrl, 'apiParam' => ['client_id' => 'Client ID', 'client_secret' => 'Client Secret']], $io, $config);
```

### CODE REVIEW

**Comment by stof** [comment]
why not simply authenticating on github ?

**Comment by jhyeon1010** [comment]
I'm making my own packagist using [composer/packagist](https://github.com/composer/packagist).
There is parameters for oauth in this package as "client_id" and "clien_secret".
I want to use these.

**Comment by stof** [comment]
@jhyeon1010 the client id and client secret in the parameters.yml are of Packagist are here to handle the oauth login on the website.
for the composer authentication, it will rely on the auth.json file available on the server, and so you can pass it a token.

**Comment by jhyeon1010** [comment]
@stof thank you for your answer.

**Comment by alcohol** [comment]
I think this can be closed as it is not really relevant anymore?

**Pull request closed without merging**
