### PR TITLE
Support tar.gz and tar.bz2 compressed archiver

### PR DESCRIPTION
**Pull request by hfcorriez**
Sometimes someone need tar.gz package to deploy the project or host the package.

### CODE REVIEW

**Comment by andrerom** [comment]
+1 would be nice addition, and as it it is different suffix then uncompressed files this does not have the ambiguity as the recently closed proposal for zip compression support had. /cc @Seldaek

**Comment by andrerom** [comment]
Related: zip compression is now possible when zip extension is enabled as of #2585

**Comment by Seldaek** [comment]
Yup fair enough, sorry for the delay looking at this @hfcorriez, and thanks for the PR :)

**Comment by hfcorriez** [comment]
It's OK, thanks for your job. I am using node as my main language now. I follow the PHP too.



On Mon, Feb 8, 2016 at 12:35 PM -0800, "Jordi Boggiano" <notifications@github.com> wrote:












Yup fair enough, sorry for the delay looking at this @hfcorriez, and thanks for the PR :)

**Pull request merged**
