### PR TITLE
Put the github token authentication back

### PR DESCRIPTION
**Pull request by matthiaz**
This was originally created here: https://github.com/composer/composer/pull/8747
But for some reason, this got removed in a merge 8b934a415f9b3787efe9a0201defaa011f8b68f9 to 1.10, not sure if this was on purpose.
re-adding, because this is breaking again.

### CODE REVIEW

**Comment by staabm** [comment]
Any chance to get this covered by a unit test, so it won‘t get accidentally removed again?

**Comment by Seldaek** [comment]
In master/2.0 it is done in AuthHelper, that's why it's not in RemoteFilesystem anymore. RemoteFilesystem is not meant to be used directly anymore, you should use HttpDownloader which abstracts over CurlDownloader or RemoteFilesystem/streams. See https://github.com/composer/composer/blob/master/src/Composer/Util/AuthHelper.php#L202-L207

The github-token option is also gone FWIW.

I am not sure how you got to this problem, but probably it's mis-use in a plugin or using composer as a library.

**Comment by matthiaz** [comment]
Thanks for pointing that out @Seldaek I missed that. 

github-token is still very much alive https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token

I'll dig deeper into this issue. But for now, this ticket can indeed be closed.

**Comment by Seldaek** [comment]
I mean passing the `github-token` to the composer downloader is gone. You should configure the auth for the right domain on the IO instance.

**Pull request closed without merging**
